mos = {
    "objectName": "DPACIMAGEDEVICE",
    "className": "psdi.app.dpldasset.TheOneMboSet",
    "description": "Deployed Assets Computers Image Devices - Converted Manufacturer",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": null,
    "primaryKeyColumns": [
        "DEVICEID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "DEPLOYEDASSET",
            "targetObject": "DPACIMAGEDEVICE",
            "parentKeys": "NODEID",
            "targetKeys": "NODEID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 7",
            "longDescription": null
        },
        {
            "objectName": "DPAIMAGEDEVICE",
            "targetObject": "DPACIMAGEDEVICE",
            "parentKeys": "DEVICEID",
            "targetKeys": "DEVICEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Deployed Image Device",
            "longDescription": null
        },
        {
            "objectName": "DPAMMANUVARIANT",
            "targetObject": "DPACIMAGEDEVICE",
            "parentKeys": "DPAMMANUVARIANTID",
            "targetKeys": "DPAMMANUVARIANTID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Variant",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "NODEID",
            "required": true,
            "persistent": true,
            "title": "Node Id",
            "remarks": "Node Id",
            "sameAsAttribute": "NODEID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "NODEID",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "NODEID"
        },
        {
            "attributeName": "DEVICEID",
            "required": true,
            "persistent": true,
            "title": "Device Id",
            "remarks": "Device Id",
            "sameAsAttribute": "DEVICEID",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "DEVICEID",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "DEVICEID"
        },
        {
            "attributeName": "DEVICETYPE",
            "required": false,
            "persistent": true,
            "title": "Device Type",
            "remarks": "Type of image device, such as printer, scanner, combo, etc.",
            "sameAsAttribute": "DEVICETYPE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "DEVICETYPE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "DEVICETYPE"
        },
        {
            "attributeName": "NAME",
            "required": false,
            "persistent": true,
            "title": "Device",
            "remarks": "System name of the image device.",
            "sameAsAttribute": "NAME",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "NAME",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "NAME"
        },
        {
            "attributeName": "ALIAS",
            "required": false,
            "persistent": true,
            "title": "Alias",
            "remarks": "System alias of the device (for example, LPT1).",
            "sameAsAttribute": "ALIAS",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "ALIAS",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "ALIAS"
        },
        {
            "attributeName": "CURRENTRAM",
            "required": false,
            "persistent": true,
            "title": "Current RAM",
            "remarks": "Amount of memory currently installed on the image device.",
            "sameAsAttribute": "CURRENTRAM",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "CURRENTRAM",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "CURRENTRAM"
        },
        {
            "attributeName": "MAXRAM",
            "required": false,
            "persistent": true,
            "title": "Maximum RAM",
            "remarks": "Maximum amount of memory that can be installed on the image device.",
            "sameAsAttribute": "MAXRAM",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "MAXRAM",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "MAXRAM"
        },
        {
            "attributeName": "RAMUNIT",
            "required": false,
            "persistent": true,
            "title": "RAM Unit",
            "remarks": "Unit of measurement for the RAM size, kilobytes (KB), megabytes (MB), or gigabytes (GB).",
            "sameAsAttribute": "RAMUNIT",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "RAMUNIT",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "RAMUNIT"
        },
        {
            "attributeName": "COLORDEPTHBIT",
            "required": false,
            "persistent": true,
            "title": "Color Depth Bit",
            "remarks": "Maximum color depth that the device can process. The number of colors that can be processed corresponds to the number of bits per pixel.",
            "sameAsAttribute": "COLORDEPTHBIT",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "COLORDEPTHBIT",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "COLORDEPTHBIT"
        },
        {
            "attributeName": "MAXWIDTH",
            "required": false,
            "persistent": true,
            "title": "Maximum Paper Width",
            "remarks": "Maximum paper width that the device can accommodate.",
            "sameAsAttribute": "MAXWIDTH",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "MAXWIDTH",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "MAXWIDTH"
        },
        {
            "attributeName": "MAXLENGTH",
            "required": false,
            "persistent": true,
            "title": "Maximum Paper Length",
            "remarks": "Maximum paper length that the device can accommodate.",
            "sameAsAttribute": "MAXLENGTH",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "MAXLENGTH",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "MAXLENGTH"
        },
        {
            "attributeName": "SIZEUNIT",
            "required": false,
            "persistent": true,
            "title": "Size Unit",
            "remarks": "Unit of measurement for the paper size.",
            "sameAsAttribute": "SIZEUNIT",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "SIZEUNIT",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "SIZEUNIT"
        },
        {
            "attributeName": "VERTICALDPI",
            "required": false,
            "persistent": true,
            "title": "Vertical DPI",
            "remarks": "Device's maximum vertical resolution, in dots per inch (DPI).",
            "sameAsAttribute": "VERTICALDPI",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "VERTICALDPI",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "VERTICALDPI"
        },
        {
            "attributeName": "HORIZONTALDPI",
            "required": false,
            "persistent": true,
            "title": "Horizontal DPI",
            "remarks": "Device's maximum horizontal resolution, in dots per inch (DPI).",
            "sameAsAttribute": "HORIZONTALDPI",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "HORIZONTALDPI",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "HORIZONTALDPI"
        },
        {
            "attributeName": "PRINTCAPABLE",
            "required": true,
            "persistent": true,
            "title": "Print Capable",
            "remarks": "Specifies whether the device is capable of printing. If the check box is selected, the device is able to print; if the check box is cleared, the device cannot print.",
            "sameAsAttribute": "PRINTCAPABLE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "PRINTCAPABLE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "PRINTCAPABLE"
        },
        {
            "attributeName": "FAXCAPABLE",
            "required": true,
            "persistent": true,
            "title": "Fax Capable",
            "remarks": "Specifies whether the device is capable of sending faxes. If the check box is selected, the device is able to send faxes; if the check box is cleared, the device cannot send faxes.",
            "sameAsAttribute": "FAXCAPABLE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "FAXCAPABLE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "FAXCAPABLE"
        },
        {
            "attributeName": "SCANCAPABLE",
            "required": true,
            "persistent": true,
            "title": "Scan Capable",
            "remarks": "Specifies whether the device is capable of scanning. If the check box is selected, the device can be used as a scanner; if the check box is cleared, the device cannot be used as a scanner.",
            "sameAsAttribute": "SCANCAPABLE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "SCANCAPABLE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "SCANCAPABLE"
        },
        {
            "attributeName": "COPYCAPABLE",
            "required": true,
            "persistent": true,
            "title": "Copy Capable",
            "remarks": "Specifies whether the device can be used as a copier. If the check box is selected, the device can be used as a copier; if the check box is cleared, the device cannot be used as a copier.",
            "sameAsAttribute": "COPYCAPABLE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "COPYCAPABLE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "COPYCAPABLE"
        },
        {
            "attributeName": "NUMBEROFTRAYS",
            "required": false,
            "persistent": true,
            "title": "Number of Trays",
            "remarks": "Number of paper trays on the device.",
            "sameAsAttribute": "NUMBEROFTRAYS",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "NUMBEROFTRAYS",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "NUMBEROFTRAYS"
        },
        {
            "attributeName": "INTERFACE",
            "required": false,
            "persistent": true,
            "title": "Interface",
            "remarks": "Connection interface between the imaging device and the computer system (for example, USB, parallel, etc.).",
            "sameAsAttribute": "INTERFACE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "INTERFACE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "INTERFACE"
        },
        {
            "attributeName": "SERIALNUMBER",
            "required": false,
            "persistent": true,
            "title": "Serial Number",
            "remarks": "Serial number of the image device.",
            "sameAsAttribute": "SERIALNUMBER",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "SERIALNUMBER",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "SERIALNUMBER"
        },
        {
            "attributeName": "ASSETTAG",
            "required": false,
            "persistent": true,
            "title": "Asset Tag",
            "remarks": "Asset tag of the image device.",
            "sameAsAttribute": "ASSETTAG",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "ASSETTAG",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "ASSETTAG"
        },
        {
            "attributeName": "MAKEMODEL",
            "required": false,
            "persistent": true,
            "title": "Make/Model",
            "remarks": "Make or model (product name) of the image device. Sometimes the make or model field contains the name of the manufacturer of the device.",
            "sameAsAttribute": "MAKEMODEL",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "MAKEMODEL",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "MAKEMODEL"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Describes the image device. This description contains relevant data that is not provided in other fields or that identifies the device in more detail. The data in this field is dependent on the discovery tool used to collect the device information; the field might be empty or might consist of several concatenated pieces of information.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "DESCRIPTION",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "CREATEDATE",
            "required": true,
            "persistent": true,
            "title": "Created Date",
            "remarks": "Create Date",
            "sameAsAttribute": "CREATEDATE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "CREATEDATE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "CREATEDATE"
        },
        {
            "attributeName": "CHANGEDATE",
            "required": true,
            "persistent": true,
            "title": "Changed Date",
            "remarks": "Change Date",
            "sameAsAttribute": "CHANGEDATE",
            "sameAsObject": "DPAIMAGEDEVICE",
            "viewColumnName": "CHANGEDATE",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "CHANGEDATE"
        },
        {
            "attributeName": "VMAXRAMSIZE",
            "required": false,
            "persistent": false,
            "title": "Maximum RAM Size",
            "remarks": "Maximum amount of memory that can be installed on the image device.",
            "sameAsAttribute": "VMAXRAMSIZE",
            "sameAsObject": "DPAIMAGEDEVICE"
        },
        {
            "attributeName": "VCURRENTRAMSIZE",
            "required": false,
            "persistent": false,
            "title": "Current RAM Size",
            "remarks": "Amount of memory currently installed on the image device.",
            "sameAsAttribute": "VCURRENTRAMSIZE",
            "sameAsObject": "DPAIMAGEDEVICE"
        },
        {
            "attributeName": "VMAXWIDTH",
            "required": false,
            "persistent": false,
            "title": "Maximum Paper Width",
            "remarks": "Maximum paper width that the device can accommodate.",
            "sameAsAttribute": "VMAXWIDTH",
            "sameAsObject": "DPAIMAGEDEVICE"
        },
        {
            "attributeName": "VMAXLENGTH",
            "required": false,
            "persistent": false,
            "title": "Maximum Paper Length",
            "remarks": "Maximum paper length that the device can accommodate.",
            "sameAsAttribute": "VMAXLENGTH",
            "sameAsObject": "DPAIMAGEDEVICE"
        },
        {
            "attributeName": "CMANUFACTURER",
            "required": true,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Name of manufacturer of the image device.",
            "sameAsAttribute": "MANUFACTURERNAME",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "CMANUFACTURER",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "MANUFACTURERNAME"
        },
        {
            "attributeName": "MANUFACTURER",
            "required": true,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Manufacturer",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "MANUFACTURER",
            "tableName": "DPAIMAGEDEVICE",
            "tableColumnName": "MANUFACTURER"
        },
        {
            "attributeName": "MANUFACTURERVAR",
            "required": true,
            "persistent": true,
            "title": "Manufacturer Variant",
            "remarks": "Manufacturer Var",
            "sameAsAttribute": "MANUFACTURERVAR",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "MANUFACTURERVAR",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "MANUFACTURERVAR"
        },
        {
            "attributeName": "DPAMMANUVARIANTID",
            "required": true,
            "persistent": true,
            "title": "Manufacturer Variant Id",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "DPAMMANUVARIANTID",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "DPAMMANUVARIANTID",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "DPAMMANUVARIANTID"
        }
    ],
    "viewinfo": {
        "autosect": false,
        "viewwhere": "dpaimagedevice.manufacturer=dpammanuvariant.manufacturervar",
        "viewselect": "select dpaimagedevice.nodeid,dpaimagedevice.deviceid,dpaimagedevice.devicetype,dpaimagedevice.name,dpaimagedevice.alias, dpaimagedevice.currentram,dpaimagedevice.maxram,dpaimagedevice.ramunit,dpaimagedevice.colordepthbit,dpaimagedevice.maxwidth, dpaimagedevice.maxlength,dpaimagedevice.sizeunit,dpaimagedevice.verticaldpi,dpaimagedevice.horizontaldpi, dpaimagedevice.printcapable,dpaimagedevice.faxcapable,dpaimagedevice.scancapable,dpaimagedevice.copycapable, dpaimagedevice.numberoftrays,dpaimagedevice.interface,dpaimagedevice.serialnumber,dpaimagedevice.assettag, dpaimagedevice.makemodel,dpaimagedevice.manufacturer,dpaimagedevice.description,dpaimagedevice.createdate, dpaimagedevice.changedate,dpaimagedevice.rowstamp,dpammanuvariant.manufacturername as cmanufacturer, dpammanuvariant.manufacturervar,dpammanuvariant.dpammanuvariantid,dpammanuvariant.rowstamp as rowstamp1",
        "viewfrom": "from dpaimagedevice,dpammanuvariant"
    },
    "outgoingRelationships": [],
    "incomingRelationships": [
        {
            "name": "DPAIMAGEDEVICE",
            "source": "DPACOMPUTER",
            "remarks": null,
            "whereClause": "nodeid=:nodeid",
            "cardinality": "UNDEFINED"
        }
    ]
}