mos = {
    "objectName": "WOSAFETYLINK",
    "className": "psdi.app.workorder.WoSafetyLinkSet",
    "description": "Hazard or Tag Out linked to a WO with As/Loc assc.",
    "longDescription": null,
    "isView": false,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": "WOSAFETYLINKID",
    "primaryKeyColumns": [
        "SITEID",
        "WOSAFETYLINKID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "ASSET",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "SITEID, ASSETNUM",
            "targetKeys": "SITEID, ASSETNUM",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 176",
            "longDescription": null
        },
        {
            "objectName": "HAZARD",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "ORGID, HAZARDID",
            "targetKeys": "ORGID, HAZARDID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Safety Hazards due to Asset or Location",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "SITEID, LOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Safety Link Location",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        },
        {
            "objectName": "TAGOUT",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "SITEID, TAGOUTID",
            "targetKeys": "SITEID, TAGOUTID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Safety Tag-Outs due to Asset or Location",
            "longDescription": null
        },
        {
            "objectName": "WOHAZARD",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "SITEID, WONUM, HAZARDID, WOSAFETYDATASOURCE",
            "targetKeys": "SITEID, WONUM, HAZARDID, WOSAFETYDATASOURCE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Work Order Safety Hazards introduce through the Asset or Location.",
            "longDescription": null
        },
        {
            "objectName": "WORKORDER",
            "targetObject": "WOSAFETYLINK",
            "parentKeys": "SITEID, WONUM",
            "targetKeys": "SITEID, WONUM",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 102",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "WOSAFETYLINKID",
            "required": true,
            "persistent": true,
            "title": "Work Link ID",
            "remarks": "Identifies a Safety Term linked with a Work Order. That is, a WO linked with a Hazard and/or Tag Out and optionally with an Asset or Loc. Key field. Autogenerated.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "WONUM",
            "required": true,
            "persistent": true,
            "title": "Work Order",
            "remarks": "Identifies the Work Order",
            "sameAsAttribute": "WONUM",
            "sameAsObject": "WORKORDER"
        },
        {
            "attributeName": "ASSETNUM",
            "required": false,
            "persistent": true,
            "title": "Related Asset",
            "remarks": "Identifies the related asset causing the hazard or requiring the Tag Out. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "ASSETNUM",
            "sameAsObject": "ASSET"
        },
        {
            "attributeName": "LOCATION",
            "required": false,
            "persistent": true,
            "title": "Related Location",
            "remarks": "Identifies the related location causing the hazard or requiring the tag out.",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS"
        },
        {
            "attributeName": "HAZARDID",
            "required": false,
            "persistent": true,
            "title": "Hazard",
            "remarks": "Identifies a hazard on the work order. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "HAZARDID",
            "sameAsObject": "HAZARD"
        },
        {
            "attributeName": "TAGOUTID",
            "required": false,
            "persistent": true,
            "title": "Tag Out",
            "remarks": "Identifier of the tag out procedure associated with the selected hazard. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "TAGOUTID",
            "sameAsObject": "TAGOUT"
        },
        {
            "attributeName": "APPLYSEQ",
            "required": false,
            "persistent": true,
            "title": "Apply Sequence",
            "remarks": "Identifies the order in which tag out procedures should be performed. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "APPLYSEQ",
            "sameAsObject": "SAFETYLEXICON"
        },
        {
            "attributeName": "REMOVESEQ",
            "required": false,
            "persistent": true,
            "title": "Remove Sequence",
            "remarks": "Identifies the order in which tag out procedures should be performed. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "REMOVESEQ",
            "sameAsObject": "SAFETYLEXICON"
        },
        {
            "attributeName": "WOSAFETYDATASOURCE",
            "required": true,
            "persistent": true,
            "title": "Source of Safety",
            "remarks": "Identifies the source of the safety information",
            "sameAsAttribute": "WOSAFETYDATASOURCE",
            "sameAsObject": "WOHAZARD"
        },
        {
            "attributeName": "ORGID",
            "required": true,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION"
        },
        {
            "attributeName": "SITEID",
            "required": true,
            "persistent": true,
            "title": "Site",
            "remarks": "Site Identifier",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE"
        },
        {
            "attributeName": "TAG08",
            "required": false,
            "persistent": false,
            "title": "Extra 8",
            "remarks": "TAG08",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG07",
            "required": false,
            "persistent": false,
            "title": "Extra 7",
            "remarks": "TAG07",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG06",
            "required": false,
            "persistent": false,
            "title": "Extra 6",
            "remarks": "TAG06",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG05",
            "required": false,
            "persistent": false,
            "title": "Extra 5",
            "remarks": "TAG05",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG04",
            "required": false,
            "persistent": false,
            "title": "Extra 4",
            "remarks": "TAG04",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG03",
            "required": false,
            "persistent": false,
            "title": "Extra 3",
            "remarks": "TAG03",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG02",
            "required": false,
            "persistent": false,
            "title": "Extra 2",
            "remarks": "TAG02",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAG01",
            "required": false,
            "persistent": false,
            "title": "Extra 1",
            "remarks": "TAG01",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ20",
            "required": true,
            "persistent": false,
            "title": "Extra 20",
            "remarks": "HAZ20",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ19",
            "required": false,
            "persistent": false,
            "title": "Extra 19",
            "remarks": "HAZ19",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ18",
            "required": false,
            "persistent": false,
            "title": "Extra 18",
            "remarks": "HAZ18",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ17",
            "required": false,
            "persistent": false,
            "title": "Extra 17",
            "remarks": "HAZ17",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ16",
            "required": false,
            "persistent": false,
            "title": "Extra 16",
            "remarks": "HAZ16",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ15",
            "required": false,
            "persistent": false,
            "title": "Extra 15",
            "remarks": "HAZ15",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ14",
            "required": false,
            "persistent": false,
            "title": "Extra 14",
            "remarks": "HAZ14",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ13",
            "required": false,
            "persistent": false,
            "title": "Extra 13",
            "remarks": "HAZ13",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ12",
            "required": false,
            "persistent": false,
            "title": "Extra 12",
            "remarks": "HAZ12",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ11",
            "required": false,
            "persistent": false,
            "title": "Extra 11",
            "remarks": "HAZ11",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ10",
            "required": false,
            "persistent": false,
            "title": "Extra 10",
            "remarks": "HAZ10",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ09",
            "required": false,
            "persistent": false,
            "title": "Extra 9",
            "remarks": "HAZ09",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ08",
            "required": false,
            "persistent": false,
            "title": "Extra 8",
            "remarks": "HAZ08",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ07",
            "required": false,
            "persistent": false,
            "title": "Extra 7",
            "remarks": "HAZ07",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ06",
            "required": false,
            "persistent": false,
            "title": "Extra 6",
            "remarks": "HAZ06",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ05",
            "required": false,
            "persistent": false,
            "title": "Extra 5",
            "remarks": "HAZ05",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ04",
            "required": false,
            "persistent": false,
            "title": "Extra 4",
            "remarks": "HAZ04",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ03",
            "required": false,
            "persistent": false,
            "title": "Extra 3",
            "remarks": "HAZ03",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ02",
            "required": false,
            "persistent": false,
            "title": "Extra 2",
            "remarks": "HAZ02",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZ01",
            "required": false,
            "persistent": false,
            "title": "Extra 1",
            "remarks": "HAZ01",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "REQUIREDSTATE",
            "required": false,
            "persistent": false,
            "title": "Required State",
            "remarks": "Required operational state the asset or location is in after you apply the tag out procedure. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAGOUTASSETDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description",
            "remarks": "TAGOUTASSETDESCRIPTION",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAGOUTDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description",
            "remarks": "Describes the tag out procedure.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAGOUTLOCATION",
            "required": false,
            "persistent": false,
            "title": "Location",
            "remarks": "TAGOUTLOCATION",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS"
        },
        {
            "attributeName": "TAGOUTASSETNUM",
            "required": false,
            "persistent": false,
            "title": "Asset",
            "remarks": "TAGOUTASSETNUM",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CONTACTRATING",
            "required": false,
            "persistent": false,
            "title": "Contact",
            "remarks": "Identifies the National Fire Protection Association contact rating. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "CONTACTRATING",
            "sameAsObject": "HAZARD"
        },
        {
            "attributeName": "REACTIVITYRATING",
            "required": false,
            "persistent": false,
            "title": "Reactivity",
            "remarks": "Identifies the National Fire Protection Association's reactivity rating. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "FLAMMABILITYRATING",
            "required": false,
            "persistent": false,
            "title": "Flammability",
            "remarks": "Identifies the National Fire Protection Association flammability rating. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HEALTHRATING",
            "required": false,
            "persistent": false,
            "title": "Health",
            "remarks": "Identifies the National Fire Protection Association health rating.You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "MSDSNUM",
            "required": false,
            "persistent": false,
            "title": "MSDS",
            "remarks": "Identifies the Material Safety Data Sheet.You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAGOUTENABLED",
            "required": true,
            "persistent": false,
            "title": "TagOut Enabled",
            "remarks": "TAGOUTENABLED",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "PRECAUTIONENABLED",
            "required": true,
            "persistent": false,
            "title": "Precaution Enabled",
            "remarks": "PRECAUTIONENABLED",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZMATENABLED",
            "required": true,
            "persistent": false,
            "title": "Hazardous Material Enabled",
            "remarks": "Check box indicating whether or not this hazard can have associated hazardous materials information on the work order. If your work plan contains a hazardous material, its associated hazard is listed in the Hazards and Precautions table and this check box is selected. If this box is selected for a hazard, Maximo copies hazardous material information to the Hazardous Materials subtab. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZARDTYPE",
            "required": false,
            "persistent": false,
            "title": "Hazard Type",
            "remarks": "Identifies the category of the hazard. Examples of hazard categories are health, mechanical, electrical, and property. Maximo copies the hazard type from the hazard record. You can edit this field if the work order's status allows safety information edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZARDDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Hazard Description",
            "remarks": "Description of the hazardous material. You can edit this field until the work order is in the status specified in the Edit Rules dialog box of Work Order Edit Options in the Organizations application.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "ASSETDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description",
            "remarks": "Describes the related asset or location.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "WOSL01",
            "required": false,
            "persistent": true,
            "title": "wosl01",
            "remarks": "Extra fields",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "WOSL02",
            "required": false,
            "persistent": true,
            "title": "wosl02",
            "remarks": "Extra fields",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "WOSL03",
            "required": false,
            "persistent": true,
            "title": "WOSL03",
            "remarks": "Extra fields",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "WOSL04",
            "required": false,
            "persistent": true,
            "title": "wosl04",
            "remarks": "Extra fields",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "WOSL05",
            "required": false,
            "persistent": true,
            "title": "wosl05",
            "remarks": "Extra fields",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HAZARDDESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Long description of hazard",
            "remarks": "The long description of hazard",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "ASSETDESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Long description of asset",
            "remarks": "The long description of asset",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAGOUTDESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Long description of tagout",
            "remarks": "The long description of tagout",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "TAGOUTASSETDESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Long Description of  tagout asset",
            "remarks": "The long description of tagout asset",
            "sameAsAttribute": null,
            "sameAsObject": null
        }
    ],
    "outgoingRelationships": [
        {
            "name": "ASSET",
            "target": "ASSET",
            "remarks": "Relationship to Asset for RecHover in Wotrack  / Safety Plan tab / WoHazPrec_table",
            "whereClause": "assetnum = :assetnum and siteid = :siteid",
            "cardinality": null
        },
        {
            "name": "DRILLDOWN",
            "target": "DRILLDOWN",
            "remarks": "Relationship from the WOSAFETYLINK to the non-persistent DrillDown table. (No where clause). The resulting set will contain zero objects. This relationship is used when the DrillDown page is launched from a location or asset field.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "HAZARD",
            "target": "HAZARD",
            "remarks": "Relationship to psdi.app.safety.Hazard (hazard.hazardid = wosafetylink.hazardid). The result set will contain zero or one object.",
            "whereClause": "hazardid = :hazardid and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "TAGLOCK",
            "target": "TAGLOCK",
            "remarks": "Relationship to the taglock table, used to find all taglock for the tagout . The result set will contain zero or more objects.",
            "whereClause": "tagoutid=:tagoutid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "TAGOUT",
            "target": "TAGOUT",
            "remarks": "Relationship to psdi.app.safety.TagOut (tagout.tagoutid = wosafetylink.tagoutid). The result set will contain zero or one object.",
            "whereClause": "tagoutid = :tagoutid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWCONTINPUT",
            "target": "VIEWCONTINPUT",
            "remarks": "Relationship to the non-persistent ViewContInput",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWWOPMS",
            "target": "VIEWWOPMS",
            "remarks": "Relationship from the WOSAFETYLINK to the non-persistent VIEWWOPMS table. (No where clause.) The resulting set will contain zero objects. This relationship is used when the View Work Details dialog is launched from a location or asset field",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOHAZARD",
            "target": "WOHAZARD",
            "remarks": "Relationship to psdi.app.workorder.WoHazard (wohazard.wonum = wosafetylink.wonum and wohazard.hazardid = wosafetylink.hazardid and wohazard.wosafetydatasource = wosafetylink.wosafetydatasource). The result set will contain one object.",
            "whereClause": "wonum = :wonum and hazardid = :hazardid and wosafetydatasource = :wosafetydatasource and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOHAZARDPREC",
            "target": "WOHAZARDPREC",
            "remarks": "Relationship to psdi.app.workorder.WoHazardPrec WoHazardPrec} where the owner is a hazard ( wohazardprec.wonum = wosafetylink.wonum and wohazardprec.hazardid = wosafetylink.hazardid and ( (wohazardprec.wosafetydatasource = 'WP' and wosafetylink.wosafetydatasource = 'WP') or (wohazardprec.wosafetydatasource != 'WP' and wosafetylink.wosafetydatasource != 'WP') ) ). The result set will contain zero or more objects. If the owner of this mbo is Workorder and the relationship name is WOSLHAZPRECENABLED with the parent as workorder,\tthen getting this WoHazardPrec set is overridden and the Sql is actually NOT used. See psdi.app.workorder.WoSafetyLink#getMboSet(String).",
            "whereClause": "wonum = :wonum and hazardid = :hazardid and   ( (wosafetydatasource = 'WP' and :wosafetydatasource = 'WP') or (wosafetydatasource != 'WP' and :wosafetydatasource != 'WP') ) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOALLHAZARDPREC",
            "target": "WOHAZARDPREC",
            "remarks": "Relationship to WoAllHazardPrec table where the owner is a hazard ( wohazardprec.wonum = wosafetylink.wonum and ( (wohazardprec.wosafetydatasource = 'WP' and wosafetylink.wosafetydatasource = 'WP') or (wohazardprec.wosafetydatasource != 'WP' and wosafetylink.wosafetydatasource != 'WP') ) ). The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and   ( (wosafetydatasource = 'WP' and :wosafetydatasource = 'WP') or (wosafetydatasource != 'WP' and :wosafetydatasource != 'WP') ) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOLOCKOUT",
            "target": "WOLOCKOUT",
            "remarks": "Relationship to psdi.app.workorder.WoLockOut where the owner is a tagout (wolockout.wonum = wosafetylink.wonum and wolockout.lockoutid in (select wotaglock.lockoutid from wotaglock where wotaglock.wonum = wosafetylink.wonum and wotaglock.tagoutid = wosafetylink.tagoutid)). Used to find lockouts for this tagout. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and lockoutid in (select lockoutid from wotaglock where wonum = :wonum and tagoutid = :tagoutid and siteid=:siteid) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOPRECAUTIONS",
            "target": "WOPRECAUTION",
            "remarks": "Relationship to psdi.app.workorder.WoPrecaution where the owner is a hazard (woprecaution.wonum = wosafetylink.wonum and woprecaution.precautionid in (select wohazardprec.precautionid from wohazardprec where wohazardprec.wonum = wosafetylink.wonum and wohazardprec.hazardid = wosafetylink.hazardid)). The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and precautionid in (select precautionid from wohazardprec where wonum = :wonum and hazardid = :hazardid and siteid=:siteid) and siteid=:siteid ",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSAFETYLINKTAG",
            "target": "WOSAFETYLINK",
            "remarks": "Relationship to psdi.app.workorder.WoSafetyLink (wosafetylink.wonum = (this)wosafetylink.wonum and (wosafetylink.hazardid is null or hazardid = (this)wosafetylink.hazardid) and wosafetylink.tagoutid is not null and ((wosafetylink.assetnum is null and wosafetylink.location is null) or wosafetylink.assetnum = (this)wosafetylink.assetnum or wosafetylink.location = (this)wosafetylink.location)). Finds the tagouts for this hazard; these can be joined to WoTagOut. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and (hazardid is null or hazardid = :hazardid) and tagoutid is not null and  ((assetnum is null and location is null) or assetnum = :assetnum or location = :location) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOALLSAFETYLINKTAG",
            "target": "WOSAFETYLINK",
            "remarks": "Relationship to psdi.app.workorder.WoSafetyLink (wosafetylink.wonum = (this)wosafetylink.wonum and wosafetylink.tagoutid is not null). Finds the tagouts for this hazard; these can be joined to WoTagOut. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and tagoutid is not null and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOTAGLOCK",
            "target": "WOTAGLOCK",
            "remarks": "Relationship to psdi.app.workorder.WoTagLock where the owner is a tagout (wotaglock.wonum = wosafetylink.wonum and wotaglock.tagoutid = wosafetylink.tagoutid).\tThe result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and tagoutid = :tagoutid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOTAGOUT",
            "target": "WOTAGOUT",
            "remarks": "Relationship to psdi.app.workorder.WoTagOut where the owner is a tagout (wotagout.wonum = wosafetylink.wonum and wotagout.tagoutid = wosafetylink.tagoutid). The result set will contain one object.",
            "whereClause": "wonum = :wonum and tagoutid = :tagoutid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOTAGOUTS",
            "target": "WOTAGOUT",
            "remarks": "Relationship to psdi.app.workorder.WoTagOut WoTagOut} where the owner is a hazard (wotagout.wonum = wosafetylink.wonum and wotagout.tagoutid in\t(select wosl2.tagoutid from wosafetylink wosl2\twhere wosl2.wonum = wosafetylink.wonum and wosl2.hazardid = wosafetylink.hazardid and wosl2.tagoutid is not null)). Used to get the tagouts for thsi hazard. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and tagoutid in (select tagoutid from wosafetylink where wonum = :wonum and hazardid = :hazardid and siteid=:siteid and tagoutid is not null) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        }
    ],
    "incomingRelationships": [
        {
            "name": "WOSAFETYLINKMAIN",
            "source": "WOHAZARD",
            "remarks": "Relationship to link psdi.app.workorder.WoSafetyLink WoSafetyLink (wosafetylink.wonum = wohazard.wonum and wosafetylink.wosafetydatasource = wohazard.wosafetydatasource and wosafetylink.hazardid = wohazard.hazardid and wosafetylink.tagoutid is null ). This is the master WoSafetyLink for this hazard. The result set will contain one object.",
            "whereClause": "wonum = :wonum and wosafetydatasource = :wosafetydatasource and hazardid = :hazardid and tagoutid is null and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSAFETYLINKTAGOUTS",
            "source": "WOHAZARD",
            "remarks": "Relationship to psdi.app.workorder.WoSafetyLink WoSafetyLink (wosafetylink.wonum = wohazard.wonum and wosafetylink.hazardid = wohazard.hazardid and wosafetylink.tagoutid is not null). When the hazard is tagout enabled, these are the tagouts. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and hazardid = :hazardid and tagoutid is not null and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSAFETYLINK",
            "source": "WORKORDER",
            "remarks": "Relationship to the WoSafetyLink table, used to find all work order safetylinks for a work order. (WOSafetyLink.wonum = workorder.wonum). This resulting set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSLHAZMATENABLED",
            "source": "WORKORDER",
            "remarks": "Relationship to the WoSafetyLink table, used to find hazardous-material-enabled hazards. (WoSafetyLink.wonum = workorder.wonum and exists (select * from wohazard where wonum = workorder.wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and hazmatenabled = :yes)). This resulting set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and exists (select * from wohazard where wonum = :wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and hazmatenabled = :yes and siteid=:siteid) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSLHAZPRECENABLED",
            "source": "WORKORDER",
            "remarks": "Relationship to the  WoSafetyLink table, used to find precaution-enabled hazards. (WoSafetyLink.wonum = workorder.wonum and exists (select * from wohazard where wonum = workorder.wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and precautionenabled = :yes)). This is used for the Wotrack Safety tab, Hazard Prec subtab. This resulting set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and exists (select * from wohazard where wonum = :wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and precautionenabled = :yes and siteid=:siteid) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSLTAGENABLED",
            "source": "WORKORDER",
            "remarks": "Relationship to the WoSafetyLink table, used to find tagout-enabled hazards. (WoSafetyLink.wonum = workorder.wonum and exists (select * from wohazard where wonum = workorder.wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and tagoutenabled = :yes)). This is used for the Wotrack Safety tab, Tagout subtab. This resulting set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and tagoutid is null and exists (select * from wohazard where wonum = :wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and tagoutenabled = :yes and siteid=:siteid) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "TAGOUTENABLED",
            "source": "WORKORDER",
            "remarks": "Relationship to the WoSafetyLink table, used to find tagout-enabled hazards. (WoSafetyLink.wonum = workorder.wonum and exists (select * from wohazard where wonum = workorder.wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and tagoutenabled = :yes)). This is used for the Wotrack Safety tab, Tagout subtab. This resulting set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and tagoutid is not null and exists (select * from wohazard where wonum = :wonum and hazardid = wosafetylink.hazardid and wosafetydatasource = wosafetylink.wosafetydatasource and tagoutenabled = :yes) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSAFETYLINKTAG",
            "source": "WOSAFETYLINK",
            "remarks": "Relationship to psdi.app.workorder.WoSafetyLink (wosafetylink.wonum = (this)wosafetylink.wonum and (wosafetylink.hazardid is null or hazardid = (this)wosafetylink.hazardid) and wosafetylink.tagoutid is not null and ((wosafetylink.assetnum is null and wosafetylink.location is null) or wosafetylink.assetnum = (this)wosafetylink.assetnum or wosafetylink.location = (this)wosafetylink.location)). Finds the tagouts for this hazard; these can be joined to WoTagOut. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and (hazardid is null or hazardid = :hazardid) and tagoutid is not null and  ((assetnum is null and location is null) or assetnum = :assetnum or location = :location) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOALLSAFETYLINKTAG",
            "source": "WOSAFETYLINK",
            "remarks": "Relationship to psdi.app.workorder.WoSafetyLink (wosafetylink.wonum = (this)wosafetylink.wonum and wosafetylink.tagoutid is not null). Finds the tagouts for this hazard; these can be joined to WoTagOut. The result set will contain zero or more objects.",
            "whereClause": "wonum = :wonum and tagoutid is not null and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "WOSAFETYLINK",
            "source": "WOTAGOUT",
            "remarks": "Relationship to psdi.app.workorder.WoSafetyLink (wosafetylink.wonum = wotagout.wonum and wosafetylink.tagoutid = wotagout.tagoutid and wosafetylink.wosafetydatasource = wotagout.wosafetydatasource). The result set will contain zero or more object.",
            "whereClause": "wonum = :wonum and tagoutid = :tagoutid and wosafetydatasource = :wosafetydatasource and siteid=:siteid",
            "cardinality": "UNDEFINED"
        }
    ]
}