mos = {
    "objectName": "DPACSOFTWARE",
    "className": "psdi.app.dpldasset.TheOneMboSet",
    "description": "Deployed Assets Computers Software - Converted Software and Manufacturer",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": null,
    "primaryKeyColumns": [
        "SOFTWAREID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "DEPLOYEDASSET",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "NODEID",
            "targetKeys": "NODEID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 16",
            "longDescription": null
        },
        {
            "objectName": "DEPLOYEDASSET",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "SOFTWAREID",
            "targetKeys": "SOFTWAREID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Deployed Software",
            "longDescription": null
        },
        {
            "objectName": "DPAMMANUVARIANT",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "DPAMMANUVARIANTID",
            "targetKeys": "DPAMMANUVARIANTID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Variant",
            "longDescription": null
        },
        {
            "objectName": "DPAMSWSUITE",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "SUITEID",
            "targetKeys": "SUITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Deployed Assets Software Suite Setup",
            "longDescription": null
        },
        {
            "objectName": "DPAMSWVARIANT",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "DPAMSWVARIANTID",
            "targetKeys": "DPAMSWVARIANTID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Software Variant",
            "longDescription": null
        },
        {
            "objectName": "DPASOFTWARE",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "SOFTWAREID",
            "targetKeys": "SOFTWAREID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Deployed Software",
            "longDescription": null
        },
        {
            "objectName": "TLOAMSOFTWARE",
            "targetObject": "DPACSOFTWARE",
            "parentKeys": "TLOAMSOFTWAREID",
            "targetKeys": "TLOAMSOFTWAREID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Software",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "NODEID",
            "required": true,
            "persistent": true,
            "title": "Node Id",
            "remarks": "Node Id",
            "sameAsAttribute": "NODEID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "NODEID",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "NODEID"
        },
        {
            "attributeName": "SOFTWAREID",
            "required": true,
            "persistent": true,
            "title": "Software",
            "remarks": "Software Id",
            "sameAsAttribute": "SOFTWAREID",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "SOFTWAREID",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "SOFTWAREID"
        },
        {
            "attributeName": "SUITEID",
            "required": false,
            "persistent": true,
            "title": "Suite Id",
            "remarks": "Suite Id",
            "sameAsAttribute": "SUITEID",
            "sameAsObject": "DPAMSWSUITE",
            "viewColumnName": "SUITEID",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "SUITEID"
        },
        {
            "attributeName": "LANGUAGE",
            "required": false,
            "persistent": true,
            "title": "Language",
            "remarks": "Language version of the software, either the name of the language (in English) or the local identifier (LCID).",
            "sameAsAttribute": "LANGUAGE",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "LANGUAGE",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "LANGUAGE"
        },
        {
            "attributeName": "VERSION",
            "required": false,
            "persistent": true,
            "title": "Version",
            "remarks": "Software version and release levels. The data in this field is dependent on the discovery tool used to collect the software information. The field contains at least the software version and release, but it may contain additional detail levels, for example, 4.0.2.2717.",
            "sameAsAttribute": "VERSION",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "VERSION",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "VERSION"
        },
        {
            "attributeName": "LICENSEDORG",
            "required": false,
            "persistent": true,
            "title": "Licensed Organization",
            "remarks": "Name of the organization to which the software license is registered.",
            "sameAsAttribute": "LICENSEDORG",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "LICENSEDORG",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "LICENSEDORG"
        },
        {
            "attributeName": "LICENSEDUSER",
            "required": false,
            "persistent": true,
            "title": "Licensed User",
            "remarks": "Name of the user to which the software license is registered.",
            "sameAsAttribute": "LICENSEDUSER",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "LICENSEDUSER",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "LICENSEDUSER"
        },
        {
            "attributeName": "USAGECOUNT",
            "required": false,
            "persistent": true,
            "title": "Usage Count",
            "remarks": "Data in this field describes how frequently the software is used. Your administrator defines the values displayed in this field based on the usage counts provided by the asset discovery tool that collects asset data. If your administrator does not define values for usage frequency in the Software Usage Setup application, Maximo displays the usage number collected by the asset discovery tool.",
            "sameAsAttribute": "USAGECOUNT",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "USAGECOUNT",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "USAGECOUNT"
        },
        {
            "attributeName": "LASTUSAGEDATE",
            "required": false,
            "persistent": true,
            "title": "Last Usage Date",
            "remarks": "Last date on which the software was used.",
            "sameAsAttribute": "LASTUSAGEDATE",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "LASTUSAGEDATE",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "LASTUSAGEDATE"
        },
        {
            "attributeName": "INSTALLPATH",
            "required": false,
            "persistent": true,
            "title": "Install Path",
            "remarks": "Installation path for the software. For some operating systems, this may include a drive; for others it may include a volume name.",
            "sameAsAttribute": "INSTALLPATH",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "INSTALLPATH",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "INSTALLPATH"
        },
        {
            "attributeName": "INSTALLDATE",
            "required": false,
            "persistent": true,
            "title": "Installation Date",
            "remarks": "Date the software was installed on the computer",
            "sameAsAttribute": "INSTALLDATE",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "INSTALLDATE",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "INSTALLDATE"
        },
        {
            "attributeName": "SERIALNUMBER",
            "required": false,
            "persistent": true,
            "title": "Serial Number",
            "remarks": "Serial number of the application.",
            "sameAsAttribute": "SERIALNUMBER",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "SERIALNUMBER",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "SERIALNUMBER"
        },
        {
            "attributeName": "PRODUCTID",
            "required": false,
            "persistent": true,
            "title": "Product Id",
            "remarks": "Registration number recorded for this application.",
            "sameAsAttribute": "PRODUCTID",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "PRODUCTID",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "PRODUCTID"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Describes the application. This description contains relevant data that is not provided in other fields or that identifies the application in more detail. The data in this field is dependent on the discovery tool used to collect the application information; the field might be empty or might consist of several concatenated pieces of information.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "DESCRIPTION",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "CREATEDATE",
            "required": true,
            "persistent": true,
            "title": "Created Date",
            "remarks": "Create Date",
            "sameAsAttribute": "CREATEDATE",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "CREATEDATE",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "CREATEDATE"
        },
        {
            "attributeName": "CHANGEDATE",
            "required": true,
            "persistent": true,
            "title": "Changed Date",
            "remarks": "Change Date",
            "sameAsAttribute": "CHANGEDATE",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "CHANGEDATE",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "CHANGEDATE"
        },
        {
            "attributeName": "TYPE",
            "required": false,
            "persistent": true,
            "title": "Application Type",
            "remarks": "Type of software application, for example, word processing or accounting. The data is this field is dependent on the discovery tool used to collect software information. This field can be empty.",
            "sameAsAttribute": "TYPE",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "TYPE",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "TYPE"
        },
        {
            "attributeName": "SUITENAME",
            "required": false,
            "persistent": false,
            "title": "Suite",
            "remarks": "Software suite name. Data in this field does not originate from the discovery tool that scans for deployed assets. Instead, it is provided by a background process that detects software suites based on rules defined for their components. Administrators define these rules in Maximo's Software Suite Setup application.",
            "sameAsAttribute": "SUITENAME",
            "sameAsObject": "DPASOFTWARE"
        },
        {
            "attributeName": "VUSAGEDISPLAYTEXT",
            "required": false,
            "persistent": false,
            "title": "Usage",
            "remarks": "Data in this field describes how frequently the software is used. Your administrator defines the values displayed in this field based on the usage counts provided by the asset discovery tool that collects asset data. If your administrator does not define values for usage frequency in the Software Usage Setup application, Maximo displays the usage number collected by the asset discovery tool.",
            "sameAsAttribute": "VUSAGEDISPLAYTEXT",
            "sameAsObject": "DPASOFTWARE"
        },
        {
            "attributeName": "CSOFTWARENAME",
            "required": true,
            "persistent": true,
            "title": "Application",
            "remarks": "Name that identifies the software application.",
            "sameAsAttribute": "SOFTWARENAME",
            "sameAsObject": "DPAMSWVARIANT",
            "viewColumnName": "CSOFTWARENAME",
            "tableName": "DPAMSWVARIANT",
            "tableColumnName": "SOFTWARENAME"
        },
        {
            "attributeName": "SOFTWARENAME1",
            "required": true,
            "persistent": true,
            "title": "Target Software",
            "remarks": "Target name for the software application. Software names that match the variants specified in the software conversion record are translated to this target name when deployed asset data is displayed in Maximo and when reports are generated.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "SOFTWARENAME1",
            "tableName": "DPAMSOFTWARE",
            "tableColumnName": "SOFTWARENAME"
        },
        {
            "attributeName": "SOFTWARENAME",
            "required": true,
            "persistent": true,
            "title": "Application",
            "remarks": "Software Name",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "SOFTWARENAME",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "SOFTWARENAME"
        },
        {
            "attributeName": "SOFTWAREVARIANT",
            "required": true,
            "persistent": true,
            "title": "Software Variant",
            "remarks": "Software Variant",
            "sameAsAttribute": "SOFTWAREVARIANT",
            "sameAsObject": "DPAMSWVARIANT",
            "viewColumnName": "SOFTWAREVARIANT",
            "tableName": "DPAMSWVARIANT",
            "tableColumnName": "SOFTWAREVARIANT"
        },
        {
            "attributeName": "DPAMSWVARIANTID",
            "required": true,
            "persistent": true,
            "title": "Software Variant Id",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "DPAMSWVARIANTID",
            "sameAsObject": "DPAMSWVARIANT",
            "viewColumnName": "DPAMSWVARIANTID",
            "tableName": "DPAMSWVARIANT",
            "tableColumnName": "DPAMSWVARIANTID"
        },
        {
            "attributeName": "CMANUFACTURER",
            "required": true,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Name of manufacturer of the application.",
            "sameAsAttribute": "MANUFACTURERNAME",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "CMANUFACTURER",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "MANUFACTURERNAME"
        },
        {
            "attributeName": "MANUFACTURER",
            "required": true,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Manufacturer",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "MANUFACTURER",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "MANUFACTURER"
        },
        {
            "attributeName": "MANUFACTURERVAR",
            "required": true,
            "persistent": true,
            "title": "Manufacturer Variant",
            "remarks": "Manufacturer Var",
            "sameAsAttribute": "MANUFACTURERVAR",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "MANUFACTURERVAR",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "MANUFACTURERVAR"
        },
        {
            "attributeName": "DPAMMANUVARIANTID",
            "required": true,
            "persistent": true,
            "title": "Manufacturer Variant Id",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "DPAMMANUVARIANTID",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "DPAMMANUVARIANTID",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "DPAMMANUVARIANTID"
        },
        {
            "attributeName": "SOFTWAREID1",
            "required": true,
            "persistent": true,
            "title": "Software",
            "remarks": "Software ID",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "SOFTWAREID1",
            "tableName": "DPAMSOFTWARE",
            "tableColumnName": "SOFTWAREID"
        },
        {
            "attributeName": "COMPLIANCESETTING",
            "required": false,
            "persistent": true,
            "title": "Compliance Setting",
            "remarks": "Specifies whether the software application is authorized or prohibited in your enterprise. If the field is blank this means the software application is neither authorized nor prohibited.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "COMPLIANCESETTING",
            "tableName": "DPAMSOFTWARE",
            "tableColumnName": "COMPLIANCESETTING"
        },
        {
            "attributeName": "FIRSTENCOUNTERED1",
            "required": false,
            "persistent": true,
            "title": "First Encountered Date",
            "remarks": "Date software first encountered",
            "sameAsAttribute": "FIRSTENCOUNTERED1",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "FIRSTENCOUNTERED1",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "FIRSTENCOUNTERED1"
        },
        {
            "attributeName": "LASTENCOUNTERED1",
            "required": false,
            "persistent": true,
            "title": "Last Encountered Date",
            "remarks": "Date software last encountered",
            "sameAsAttribute": "LASTENCOUNTERED1",
            "sameAsObject": "DPASOFTWARE",
            "viewColumnName": "LASTENCOUNTERED1",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "LASTENCOUNTERED1"
        },
        {
            "attributeName": "TLOAMSOFTWAREID",
            "required": false,
            "persistent": true,
            "title": "Software",
            "remarks": "Link to the Software Catalog entry for the discovered software",
            "sameAsAttribute": "TLOAMSOFTWAREID",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMSOFTWAREID",
            "tableName": "DPASOFTWARE",
            "tableColumnName": "TLOAMSOFTWAREID"
        },
        {
            "attributeName": "TLOAMSWNAME",
            "required": false,
            "persistent": true,
            "title": "Software Name",
            "remarks": "Software name",
            "sameAsAttribute": "SWNAME",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMSWNAME",
            "tableName": "TLOAMSOFTWARE",
            "tableColumnName": "SWNAME"
        },
        {
            "attributeName": "TLOAMVERSION",
            "required": false,
            "persistent": true,
            "title": "Version",
            "remarks": "Version",
            "sameAsAttribute": "VERSION",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMVERSION",
            "tableName": "TLOAMSOFTWARE",
            "tableColumnName": "VERSION"
        },
        {
            "attributeName": "TLOAMRELEASE",
            "required": false,
            "persistent": true,
            "title": "Release",
            "remarks": "Release",
            "sameAsAttribute": "RELEASE",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMRELEASE",
            "tableName": "TLOAMSOFTWARE",
            "tableColumnName": "RELEASE"
        },
        {
            "attributeName": "TLOAMTYPE",
            "required": false,
            "persistent": true,
            "title": "Type",
            "remarks": "Type",
            "sameAsAttribute": "TYPE",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMTYPE",
            "tableName": "TLOAMSOFTWARE",
            "tableColumnName": "TYPE"
        },
        {
            "attributeName": "TLOAMPLATFORMBASE",
            "required": false,
            "persistent": true,
            "title": "Platform",
            "remarks": "Platform",
            "sameAsAttribute": "PLATFORMBASE",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMPLATFORMBASE",
            "tableName": "TLOAMSOFTWARE",
            "tableColumnName": "PLATFORMBASE"
        },
        {
            "attributeName": "TLOAMFUNC",
            "required": false,
            "persistent": true,
            "title": "Function",
            "remarks": "Function",
            "sameAsAttribute": "FUNC",
            "sameAsObject": "TLOAMSOFTWARE",
            "viewColumnName": "TLOAMFUNC",
            "tableName": "TLOAMSOFTWARE",
            "tableColumnName": "FUNC"
        }
    ],
    "viewinfo": {
        "autosect": false,
        "viewwhere": "(t800.tloamsoftwareid = dpasoftware.tloamsoftwareid) and (tloamsoftware.tloamsoftwareid = (case when (t800.targetsoftwareid is null or t800.targetsoftwareid=0) then (t800.tloamsoftwareid) else (t800.targetsoftwareid) end)) and (dpammanuvariant.manufacturervar=tloamsoftware.manufacturer)",
        "viewselect": "select dpasoftware.nodeid, dpasoftware.softwareid, dpasoftware.suiteid, dpasoftware.softwarename, dpasoftware.language, dpasoftware.version, dpasoftware.licensedorg, dpasoftware.licenseduser, dpasoftware.usagecount, dpasoftware.lastusagedate, dpasoftware.installpath, dpasoftware.installdate, dpasoftware.serialnumber, dpasoftware.productid, dpasoftware.manufacturer, dpasoftware.description, dpasoftware.createdate, dpasoftware.changedate, dpasoftware.type, dpasoftware.firstencountered1, dpasoftware.lastencountered1, dpasoftware.tloamsoftwareid, dpasoftware.rowstamp, t800.swname as softwarevariant, t800.tloamsoftwareid as dpamswvariantid, t800.rowstamp as rowstamp1, dpammanuvariant.manufacturername as cmanufacturer, dpammanuvariant.manufacturervar, dpammanuvariant.dpammanuvariantid, dpammanuvariant.rowstamp as rowstamp2, tloamsoftware.swname as csoftwarename, tloamsoftware.swname as swname1, tloamsoftware.tloamsoftwareid as softwareid1, tloamsoftware.managedas as compliancesetting, tloamsoftware.rowstamp as rowstamp3, tloamsoftware.swname as tloamswname, tloamsoftware.version as tloamversion, tloamsoftware.release as tloamrelease, tloamsoftware.type as tloamtype, tloamsoftware.platformbase as tloamplatformbase, tloamsoftware.func as tloamfunc",
        "viewfrom": "from dpasoftware, tloamsoftware t800, tloamsoftware, dpammanuvariant"
    },
    "outgoingRelationships": [],
    "incomingRelationships": [
        {
            "name": "TLOAMFILTERSW",
            "source": "COMPUTERSYSTEM",
            "remarks": "Relationship between Computersystem and dpacsoftware",
            "whereClause": "nodeid=:nodeid and compliancesetting not in(select value from synonymdomain where domainid = 'COMPLIANCESETTING' and maxvalue = 'Ignored')",
            "cardinality": null
        },
        {
            "name": "DPASOFTWARE",
            "source": "DPACOMPUTER",
            "remarks": null,
            "whereClause": "nodeid=:nodeid",
            "cardinality": "UNDEFINED"
        }
    ]
}