mos = {
    "objectName": "LNKCLAUSEATRNAME",
    "className": "psdi.app.rcnlnkrule.ReconLinkClauseSet",
    "description": "Joins Classspec and AssetAttribute",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": null,
    "primaryKeyColumns": [
        "CLASSSTRUCTUREID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "ASSETATTRIBUTE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "ASSETATTRID, ORGID, SITEID",
            "targetKeys": "ATTRIBUTENAME, ORGID, SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Linked Asset Attribute",
            "longDescription": null
        },
        {
            "objectName": "ASSETATTRIBUTE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "ASSETATTRID, ORGID, SITEID",
            "targetKeys": "ATTRIBUTENAME, ORGID, SITEID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 20",
            "longDescription": null
        },
        {
            "objectName": "ASSETATTRIBUTE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "ASSETATTRID, ORGID, SITEID",
            "targetKeys": "ATTRIBUTENAME, ORGID1, SITEID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 21",
            "longDescription": null
        },
        {
            "objectName": "ASSETATTRIBUTE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "ASSETATTRID, ORGID, SITEID",
            "targetKeys": "ATTRIBUTENAME, ORGID1, SITEID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 22",
            "longDescription": null
        },
        {
            "objectName": "CLASSSPEC",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "CLASSSTRUCTUREID, ASSETATTRID, SECTION, ORGID, SITEID",
            "targetKeys": "CLASSSTRUCTUREID, ATTRIBUTENAME, SECTION, ORGID, SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Class Specification",
            "longDescription": null
        },
        {
            "objectName": "CLASSSPEC",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "CLASSSTRUCTUREID, ASSETATTRID, SECTION, ORGID, SITEID",
            "targetKeys": "CLASSSTRUCTUREID, ATTRIBUTENAME, SECTION, ORGID, SITEID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 27",
            "longDescription": null
        },
        {
            "objectName": "CLASSSPEC",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "CLASSSTRUCTUREID, ASSETATTRID, SECTION, ORGID, SITEID",
            "targetKeys": "CLASSSTRUCTUREID, ATTRIBUTENAME, SECTION, ORGID1, SITEID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 28",
            "longDescription": null
        },
        {
            "objectName": "CLASSSPEC",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "CLASSSTRUCTUREID, ASSETATTRID, SECTION, ORGID, SITEID",
            "targetKeys": "CLASSSTRUCTUREID, ATTRIBUTENAME, SECTION, ORGID1, SITEID1",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Class Specification",
            "longDescription": null
        },
        {
            "objectName": "CLASSSTRUCTURE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "CLASSSTRUCTUREID",
            "targetKeys": "CLASSSTRUCTUREID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Class Structure",
            "longDescription": null
        },
        {
            "objectName": "MAXDOMAIN",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "DOMAINID",
            "targetKeys": "DOMAINID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 5",
            "longDescription": null
        },
        {
            "objectName": "MAXDOMAIN",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "DOMAINID",
            "targetKeys": "DOMAINID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 6",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID, SITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 112",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID, SITEID, ORGID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 113",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID, SITEID1, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 114",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID, SITEID1, ORGID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 115",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID1, SITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 116",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID1, SITEID, ORGID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 117",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID1, SITEID1, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 118",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "MEASUREUNITID1, SITEID1, ORGID1",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 119",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID",
            "targetKeys": "MEASUREUNITID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Measure Unit",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "MEASUREUNITID",
            "targetKeys": "MEASUREUNITID1",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Default Measure Unit",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID1",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "LNKCLAUSEATRNAME",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID1",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "CLASSSTRUCTUREID",
            "required": true,
            "persistent": true,
            "title": "Class Structure",
            "remarks": "Class Structure identifier",
            "sameAsAttribute": "CLASSSTRUCTUREID",
            "sameAsObject": "CLASSSTRUCTURE",
            "viewColumnName": "CLASSSTRUCTUREID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CLASSSTRUCTUREID"
        },
        {
            "attributeName": "MEASUREUNITID",
            "required": false,
            "persistent": true,
            "title": "Unit of Measure",
            "remarks": "Measure unit identifier",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "MEASUREUNITID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "MEASUREUNITID"
        },
        {
            "attributeName": "DOMAINID",
            "required": false,
            "persistent": true,
            "title": "Domain",
            "remarks": "Domain identifier",
            "sameAsAttribute": "DOMAINID",
            "sameAsObject": "MAXDOMAIN",
            "viewColumnName": "DOMAINID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "DOMAINID"
        },
        {
            "attributeName": "ATTRDESCPREFIX",
            "required": false,
            "persistent": true,
            "title": "Description Prefix",
            "remarks": "Prefix used with attribute in genereted asset descriptions",
            "sameAsAttribute": "ATTRDESCPREFIX",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "ATTRDESCPREFIX",
            "tableName": "CLASSSPEC",
            "tableColumnName": "ATTRDESCPREFIX"
        },
        {
            "attributeName": "CS01",
            "required": false,
            "persistent": true,
            "title": "Cs01",
            "remarks": "Cross-over field from AssetAttribute.AA01",
            "sameAsAttribute": "CS01",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "CS01",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CS01"
        },
        {
            "attributeName": "CS02",
            "required": false,
            "persistent": true,
            "title": "Cs02",
            "remarks": "Cross-over field from AssetAttribute.AA02",
            "sameAsAttribute": "CS02",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "CS02",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CS02"
        },
        {
            "attributeName": "CS03",
            "required": false,
            "persistent": true,
            "title": "Cs03",
            "remarks": "Cross-over field from AssetAttribute.AA03",
            "sameAsAttribute": "CS03",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "CS03",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CS03"
        },
        {
            "attributeName": "CS04",
            "required": false,
            "persistent": true,
            "title": "Cs04",
            "remarks": "Cross-over field from AssetAttribute.AA04",
            "sameAsAttribute": "CS04",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "CS04",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CS04"
        },
        {
            "attributeName": "CS05",
            "required": false,
            "persistent": true,
            "title": "Cs05",
            "remarks": "Cross-over field from AssetAttribute.AA05",
            "sameAsAttribute": "CS05",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "CS05",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CS05"
        },
        {
            "attributeName": "ORGID",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "DATATYPE",
            "required": false,
            "persistent": false,
            "title": "Data Type",
            "remarks": "DATATYPE",
            "sameAsAttribute": "DATATYPE",
            "sameAsObject": "CLASSSPEC"
        },
        {
            "attributeName": "SPECVALUE",
            "required": false,
            "persistent": false,
            "title": "Alphanumeric Value",
            "remarks": "SPECVALUE",
            "sameAsAttribute": "VALUE",
            "sameAsObject": "ALNDOMAIN"
        },
        {
            "attributeName": "SECTION",
            "required": false,
            "persistent": true,
            "title": "Section",
            "remarks": "Section for a Group of Attributes",
            "sameAsAttribute": "SECTION",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "SECTION",
            "tableName": "CLASSSPEC",
            "tableColumnName": "SECTION"
        },
        {
            "attributeName": "SITEID",
            "required": false,
            "persistent": true,
            "title": "Site",
            "remarks": "Site Identifier",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "SITEID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "SITEID"
        },
        {
            "attributeName": "CLASSSPECID",
            "required": true,
            "persistent": true,
            "title": "Classification",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "CLASSSPECID",
            "sameAsObject": "CLASSSPEC",
            "viewColumnName": "CLASSSPECID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "CLASSSPECID"
        },
        {
            "attributeName": "ASSETATTRIBUTEID",
            "required": true,
            "persistent": true,
            "title": "ASSETATTRIBUTEID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "ASSETATTRIBUTEID",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "ASSETATTRIBUTEID",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "ASSETATTRIBUTEID"
        },
        {
            "attributeName": "ATTRIBUTENAME",
            "required": true,
            "persistent": true,
            "title": "Attribute Name",
            "remarks": "Attribute Name",
            "sameAsAttribute": "ASSETATTRID",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "ATTRIBUTENAME",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "ASSETATTRID"
        },
        {
            "attributeName": "ASSETATTRID",
            "required": true,
            "persistent": true,
            "title": "Attribute",
            "remarks": "Asset attribute identifier",
            "sameAsAttribute": "ASSETATTRID",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "ASSETATTRID",
            "tableName": "CLASSSPEC",
            "tableColumnName": "ASSETATTRID"
        },
        {
            "attributeName": "DATATYPE1",
            "required": true,
            "persistent": true,
            "title": "Data Type",
            "remarks": "Data Type for attribute value",
            "sameAsAttribute": "DATATYPE",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "DATATYPE1",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "DATATYPE"
        },
        {
            "attributeName": "MEASUREUNITID1",
            "required": false,
            "persistent": true,
            "title": "Unit of Measure",
            "remarks": "Default Units for the attribute",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "MEASUREUNITID1",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "MEASUREUNITID"
        },
        {
            "attributeName": "DOMAINID1",
            "required": false,
            "persistent": true,
            "title": "Domain",
            "remarks": "Default Domain for the attribute",
            "sameAsAttribute": "DOMAINID",
            "sameAsObject": "MAXDOMAIN",
            "viewColumnName": "DOMAINID1",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "DOMAINID"
        },
        {
            "attributeName": "ATTRDESCPREFIX1",
            "required": false,
            "persistent": true,
            "title": "Prefix",
            "remarks": "Default Prefix Used with Attribute in Generated Asset Descriptions",
            "sameAsAttribute": "ATTRDESCPREFIX",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "ATTRDESCPREFIX1",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "ATTRDESCPREFIX"
        },
        {
            "attributeName": "ORGID1",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID1",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "SITEID1",
            "required": false,
            "persistent": true,
            "title": "Site",
            "remarks": "Site Identifier",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "SITEID1",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "SITEID"
        },
        {
            "attributeName": "TITLE",
            "required": false,
            "persistent": true,
            "title": "Title",
            "remarks": "Title",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "ASSETATTRIBUTE",
            "viewColumnName": "TITLE",
            "tableName": "ASSETATTRIBUTE",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "APPLYDOWNHIER",
            "required": true,
            "persistent": true,
            "title": "Apply Down Hierarchy",
            "remarks": "Apply Down Hierarchy? If true, then all child classspec records get this attribute.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "INHERITEDFROM",
            "required": false,
            "persistent": true,
            "title": "Inherited From",
            "remarks": "The Hierarchy Path of the classifications that this classification inherits from.",
            "sameAsAttribute": "HIERARCHYPATH",
            "sameAsObject": "CLASSSTRUCTURE"
        },
        {
            "attributeName": "INHERITEDFROMID",
            "required": false,
            "persistent": true,
            "title": "Inherited from ClassSpec Id",
            "remarks": "The referenced ClassSpec Id",
            "sameAsAttribute": "CLASSSPECID",
            "sameAsObject": "CLASSSPEC"
        },
        {
            "attributeName": "TABLEATTRIBUTE",
            "required": false,
            "persistent": true,
            "title": "Table Attribute",
            "remarks": "The attribute name for the table domain entered. It is required when the domain is populated.",
            "sameAsAttribute": "ATTRIBUTENAME",
            "sameAsObject": "MAXATTRIBUTE"
        }
    ],
    "viewinfo": {
        "autosect": false,
        "viewwhere": "classspec.assetattrid = assetattribute.assetattrid",
        "viewselect": "select classspec.classstructureid as classstructureid,classspec.assetattrid as assetattrid,classspec.measureunitid as measureunitid ,classspec.domainid as domainid,classspec.attrdescprefix as attrdescprefix,classspec.cs01 as cs01,classspec.cs02 as cs02,classspec.cs03 as cs03,classspec.cs04 as cs04 ,classspec.cs05 as cs05,classspec.orgid as orgid,classspec.section as section,classspec.siteid as siteid,classspec.classspecid as classspecid ,classspec.rowstamp as rowstamp,classspec.applydownhier as applydownhier,classspec.inheritedfrom as inheritedfrom, classspec.inheritedfromid as inheritedfromid,classspec.tableattribute as tableattribute,assetattribute.description as title,assetattribute.assetattributeid as assetattributeid ,assetattribute.assetattrid as attributename,assetattribute.datatype as datatype1,assetattribute.measureunitid as measureunitid1 ,assetattribute.domainid as domainid1,assetattribute.attrdescprefix as attrdescprefix1,assetattribute.orgid as orgid1 ,assetattribute.siteid as siteid1,assetattribute.rowstamp as rowstamp1",
        "viewfrom": "from classspec,assetattribute"
    },
    "outgoingRelationships": [],
    "incomingRelationships": []
}