mos = {
    "objectName": "PERSONGROUPVIEW",
    "className": "psdi.app.person.PersonGroupViewSet",
    "description": "View from person and persongroupteam",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": true,
    "uniqueId": null,
    "primaryKeyColumns": [
        "PERSONID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "ADDRESS",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "ORGID, ADDRESSCODE",
            "targetKeys": "LOCATIONORG, BILLTOADDRESS",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Bill To Address",
            "longDescription": null
        },
        {
            "objectName": "ADDRESS",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "ORGID, ADDRESSCODE",
            "targetKeys": "LOCATIONORG, SHIPTOADDRESS",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Ship To Address",
            "longDescription": null
        },
        {
            "objectName": "ADDRESS",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "ORGID, ADDRESSCODE",
            "targetKeys": "USEFORORG, BILLTOADDRESS",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 12",
            "longDescription": null
        },
        {
            "objectName": "ADDRESS",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "ORGID, ADDRESSCODE",
            "targetKeys": "USEFORORG, SHIPTOADDRESS",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 13",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Language for the record",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGUAGE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "person''s language preference",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "LOCATIONSITE, LOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Location",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "USEFORSITE, LOCATION",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 141",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "ORGID",
            "targetKeys": "LOCATIONORG",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Location''s Organization",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "ORGID",
            "targetKeys": "USEFORORG",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization the person is to be used for",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "DELEGATE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Delegate",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "PERSONID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Person",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "RESPPARTY",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Responsible Party",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "RESPPARTYGROUP",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Responsible Party Group",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "SUPERVISOR",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Supervisor",
            "longDescription": null
        },
        {
            "objectName": "PERSONGROUP",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONGROUP",
            "targetKeys": "PERSONGROUP",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Person Group",
            "longDescription": null
        },
        {
            "objectName": "PERSONGROUPTEAM",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "PERSONGROUPTEAMID",
            "targetKeys": "PERSONGROUPTEAMID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Person Group Team",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "SITEID",
            "targetKeys": "LOCATIONSITE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Location''s Site",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "PERSONGROUPVIEW",
            "parentKeys": "SITEID",
            "targetKeys": "USEFORSITE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site the person is to be used for",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "PERSONID",
            "required": true,
            "persistent": true,
            "title": "Person",
            "remarks": "Identifier of the person's record. This field must be unique.When you save a person record, this field becomes read only.",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "PERSONID",
            "tableName": "PERSON",
            "tableColumnName": "PERSONID"
        },
        {
            "attributeName": "STATUS",
            "required": true,
            "persistent": true,
            "title": "Status",
            "remarks": "The current status of the person. On inserting a new record, this field defaults to an active status.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "PERSON",
            "viewColumnName": "STATUS",
            "tableName": "PERSON",
            "tableColumnName": "STATUS"
        },
        {
            "attributeName": "DISPLAYNAME",
            "required": false,
            "persistent": true,
            "title": "Name",
            "remarks": "A nick name or a friendly name that this person can be identified with.This field is automatically populated when values are entered in the First Name and/or Last Name fields.",
            "sameAsAttribute": "DISPLAYNAME",
            "sameAsObject": "PERSON",
            "viewColumnName": "DISPLAYNAME",
            "tableName": "PERSON",
            "tableColumnName": "DISPLAYNAME"
        },
        {
            "attributeName": "FIRSTNAME",
            "required": false,
            "persistent": true,
            "title": "First Name",
            "remarks": "The first name of the person whose record this is.",
            "sameAsAttribute": "FIRSTNAME",
            "sameAsObject": "PERSON",
            "viewColumnName": "FIRSTNAME",
            "tableName": "PERSON",
            "tableColumnName": "FIRSTNAME"
        },
        {
            "attributeName": "LASTNAME",
            "required": false,
            "persistent": true,
            "title": "Last Name",
            "remarks": "The last name of the person whose record this is.",
            "sameAsAttribute": "LASTNAME",
            "sameAsObject": "PERSON",
            "viewColumnName": "LASTNAME",
            "tableName": "PERSON",
            "tableColumnName": "LASTNAME"
        },
        {
            "attributeName": "DEPARTMENT",
            "required": false,
            "persistent": true,
            "title": "Department",
            "remarks": "The department this person belongs to.",
            "sameAsAttribute": "DEPARTMENT",
            "sameAsObject": "PERSON",
            "viewColumnName": "DEPARTMENT",
            "tableName": "PERSON",
            "tableColumnName": "DEPARTMENT"
        },
        {
            "attributeName": "TITLE",
            "required": false,
            "persistent": true,
            "title": "Title",
            "remarks": "The job title of this person.",
            "sameAsAttribute": "TITLE",
            "sameAsObject": "PERSON",
            "viewColumnName": "TITLE",
            "tableName": "PERSON",
            "tableColumnName": "TITLE"
        },
        {
            "attributeName": "EMPLOYEETYPE",
            "required": false,
            "persistent": true,
            "title": "Employee Type",
            "remarks": "The type of employee this person is, such as full time or a part time employee.",
            "sameAsAttribute": "EMPLOYEETYPE",
            "sameAsObject": "PERSON",
            "viewColumnName": "EMPLOYEETYPE",
            "tableName": "PERSON",
            "tableColumnName": "EMPLOYEETYPE"
        },
        {
            "attributeName": "JOBCODE",
            "required": false,
            "persistent": true,
            "title": "Job Code",
            "remarks": "The job code of this person.",
            "sameAsAttribute": "JOBCODE",
            "sameAsObject": "PERSON",
            "viewColumnName": "JOBCODE",
            "tableName": "PERSON",
            "tableColumnName": "JOBCODE"
        },
        {
            "attributeName": "SUPERVISOR",
            "required": false,
            "persistent": true,
            "title": "Supervisor",
            "remarks": "The name of this person's supervisor.",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "SUPERVISOR",
            "tableName": "PERSON",
            "tableColumnName": "SUPERVISOR"
        },
        {
            "attributeName": "BIRTHDATE",
            "required": false,
            "persistent": true,
            "title": "Date of Birth",
            "remarks": "The date of this person's birth.",
            "sameAsAttribute": "BIRTHDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "BIRTHDATE",
            "tableName": "PERSON",
            "tableColumnName": "BIRTHDATE"
        },
        {
            "attributeName": "LASTEVALDATE",
            "required": false,
            "persistent": true,
            "title": "Last Evaluation",
            "remarks": "The date of this person's most recent evaluation.",
            "sameAsAttribute": "LASTEVALDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "LASTEVALDATE",
            "tableName": "PERSON",
            "tableColumnName": "LASTEVALDATE"
        },
        {
            "attributeName": "NEXTEVALDATE",
            "required": false,
            "persistent": true,
            "title": "Next Evaluation",
            "remarks": "The date of this person's next evaluation.",
            "sameAsAttribute": "NEXTEVALDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "NEXTEVALDATE",
            "tableName": "PERSON",
            "tableColumnName": "NEXTEVALDATE"
        },
        {
            "attributeName": "HIREDATE",
            "required": false,
            "persistent": true,
            "title": "Hire Date",
            "remarks": "The date that this person started working for the company.",
            "sameAsAttribute": "HIREDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "HIREDATE",
            "tableName": "PERSON",
            "tableColumnName": "HIREDATE"
        },
        {
            "attributeName": "TERMINATIONDATE",
            "required": false,
            "persistent": true,
            "title": "Termination Date",
            "remarks": "The date when this person's services are terminated.",
            "sameAsAttribute": "TERMINATIONDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "TERMINATIONDATE",
            "tableName": "PERSON",
            "tableColumnName": "TERMINATIONDATE"
        },
        {
            "attributeName": "LOCATION",
            "required": false,
            "persistent": true,
            "title": "Person's Location",
            "remarks": "The place where this person is located.",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS",
            "viewColumnName": "LOCATION",
            "tableName": "PERSON",
            "tableColumnName": "LOCATION"
        },
        {
            "attributeName": "LOCATIONSITE",
            "required": false,
            "persistent": true,
            "title": "Person's Site",
            "remarks": "The site to which this person belongs.",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "LOCATIONSITE",
            "tableName": "PERSON",
            "tableColumnName": "LOCATIONSITE"
        },
        {
            "attributeName": "LOCATIONORG",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization of the location",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "LOCATIONORG",
            "tableName": "PERSON",
            "tableColumnName": "LOCATIONORG"
        },
        {
            "attributeName": "SHIPTOADDRESS",
            "required": false,
            "persistent": true,
            "title": "Ship to Address",
            "remarks": "The shipping address of the person. This will be the default shipping address used for purchase transactions entered by this person.",
            "sameAsAttribute": "ADDRESSCODE",
            "sameAsObject": "ADDRESS",
            "viewColumnName": "SHIPTOADDRESS",
            "tableName": "PERSON",
            "tableColumnName": "SHIPTOADDRESS"
        },
        {
            "attributeName": "BILLTOADDRESS",
            "required": false,
            "persistent": true,
            "title": "Bill to Address",
            "remarks": "The billing address of this person. This will be used as the default billing address for purchase transactions entered by the user.",
            "sameAsAttribute": "ADDRESSCODE",
            "sameAsObject": "ADDRESS",
            "viewColumnName": "BILLTOADDRESS",
            "tableName": "PERSON",
            "tableColumnName": "BILLTOADDRESS"
        },
        {
            "attributeName": "DROPPOINT",
            "required": false,
            "persistent": true,
            "title": "Drop Point",
            "remarks": "The drop point for making deliveries.",
            "sameAsAttribute": "DROPPOINT",
            "sameAsObject": "MR",
            "viewColumnName": "DROPPOINT",
            "tableName": "PERSON",
            "tableColumnName": "DROPPOINT"
        },
        {
            "attributeName": "WFMAILELECTION",
            "required": false,
            "persistent": true,
            "title": "Workflow E-mail Notification",
            "remarks": "The person's choice of when to receive emailed workflow assignments. A value list field defining the circumstances in which this person will receive workflow related e-mail notification.",
            "sameAsAttribute": "WFMAILELECTION",
            "sameAsObject": "PERSON",
            "viewColumnName": "WFMAILELECTION",
            "tableName": "PERSON",
            "tableColumnName": "WFMAILELECTION"
        },
        {
            "attributeName": "TRANSEMAILELECTION",
            "required": true,
            "persistent": true,
            "title": "Notice of E-commerce Exceptions",
            "remarks": "The person's choice of when to receive transaction email.",
            "sameAsAttribute": "TRANSEMAILELECTION",
            "sameAsObject": "PERSON",
            "viewColumnName": "TRANSEMAILELECTION",
            "tableName": "PERSON",
            "tableColumnName": "TRANSEMAILELECTION"
        },
        {
            "attributeName": "DELEGATE",
            "required": false,
            "persistent": true,
            "title": "Workflow Delegate",
            "remarks": "The delegate for Workflow assignments for this person. If there is a value in this field and if the workflow assignment is received between the Delegate To and Delegate From date, Workflow sends the assignment to the delegate. Enter a value or click Detail Menu to select an option and retrieve a value",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "DELEGATE",
            "tableName": "PERSON",
            "tableColumnName": "DELEGATE"
        },
        {
            "attributeName": "DELEGATEFROMDATE",
            "required": false,
            "persistent": true,
            "title": "Delegate From",
            "remarks": "The first date from which this person's delegate takes over the workflow assignments.",
            "sameAsAttribute": "DELEGATEFROMDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "DELEGATEFROMDATE",
            "tableName": "PERSON",
            "tableColumnName": "DELEGATEFROMDATE"
        },
        {
            "attributeName": "DELEGATETODATE",
            "required": false,
            "persistent": true,
            "title": "Delegate To",
            "remarks": "The last date till which this person's delegate works on the workflow assignments. The value entered in this field must be either equal to or greater than the value in the Delegate From field.",
            "sameAsAttribute": "DELEGATETODATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "DELEGATETODATE",
            "tableName": "PERSON",
            "tableColumnName": "DELEGATETODATE"
        },
        {
            "attributeName": "PCARDNUM",
            "required": false,
            "persistent": true,
            "title": "Card #",
            "remarks": "The number on the person's company's credit card.",
            "sameAsAttribute": "PCARDNUM",
            "sameAsObject": "PERSON",
            "viewColumnName": "PCARDNUM",
            "tableName": "PERSON",
            "tableColumnName": "PCARDNUM"
        },
        {
            "attributeName": "PCARDTYPE",
            "required": false,
            "persistent": true,
            "title": "Card Type",
            "remarks": "The type of credit card used. Enter a value or click Select Value.",
            "sameAsAttribute": "PCARDTYPE",
            "sameAsObject": "PERSON",
            "viewColumnName": "PCARDTYPE",
            "tableName": "PERSON",
            "tableColumnName": "PCARDTYPE"
        },
        {
            "attributeName": "PCARDEXPDATE",
            "required": false,
            "persistent": true,
            "title": "Expiration Date",
            "remarks": "The expiration date of the company credit card.",
            "sameAsAttribute": "PCARDEXPDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "PCARDEXPDATE",
            "tableName": "PERSON",
            "tableColumnName": "PCARDEXPDATE"
        },
        {
            "attributeName": "PCARDVERIFICATION",
            "required": false,
            "persistent": true,
            "title": "Verification Value",
            "remarks": "The three- or four-digit code at the end of a credit card number; you can find this verification code on the back or front of the card.",
            "sameAsAttribute": "PCARDVERIFICATION",
            "sameAsObject": "PERSON",
            "viewColumnName": "PCARDVERIFICATION",
            "tableName": "PERSON",
            "tableColumnName": "PCARDVERIFICATION"
        },
        {
            "attributeName": "ADDRESSLINE1",
            "required": false,
            "persistent": true,
            "title": "Address",
            "remarks": "The address of this person.",
            "sameAsAttribute": "ADDRESSLINE1",
            "sameAsObject": "PERSON",
            "viewColumnName": "ADDRESSLINE1",
            "tableName": "PERSON",
            "tableColumnName": "ADDRESSLINE1"
        },
        {
            "attributeName": "ADDRESSLINE2",
            "required": false,
            "persistent": true,
            "title": "City",
            "remarks": "Address Line 2",
            "sameAsAttribute": "ADDRESSLINE2",
            "sameAsObject": "PERSON",
            "viewColumnName": "ADDRESSLINE2",
            "tableName": "PERSON",
            "tableColumnName": "ADDRESSLINE2"
        },
        {
            "attributeName": "ADDRESSLINE3",
            "required": false,
            "persistent": true,
            "title": "State/Province",
            "remarks": "Address Line 3",
            "sameAsAttribute": "ADDRESSLINE3",
            "sameAsObject": "PERSON",
            "viewColumnName": "ADDRESSLINE3",
            "tableName": "PERSON",
            "tableColumnName": "ADDRESSLINE3"
        },
        {
            "attributeName": "CITY",
            "required": false,
            "persistent": true,
            "title": "City",
            "remarks": "The city where this person resides.",
            "sameAsAttribute": "CITY",
            "sameAsObject": "PERSON",
            "viewColumnName": "CITY",
            "tableName": "PERSON",
            "tableColumnName": "CITY"
        },
        {
            "attributeName": "REGIONDISTRICT",
            "required": false,
            "persistent": true,
            "title": "Regional/District",
            "remarks": "Region/District",
            "sameAsAttribute": "REGIONDISTRICT",
            "sameAsObject": "PERSON",
            "viewColumnName": "REGIONDISTRICT",
            "tableName": "PERSON",
            "tableColumnName": "REGIONDISTRICT"
        },
        {
            "attributeName": "COUNTY",
            "required": false,
            "persistent": true,
            "title": "County",
            "remarks": "County",
            "sameAsAttribute": "COUNTY",
            "sameAsObject": "PERSON",
            "viewColumnName": "COUNTY",
            "tableName": "PERSON",
            "tableColumnName": "COUNTY"
        },
        {
            "attributeName": "STATEPROVINCE",
            "required": false,
            "persistent": true,
            "title": "State/Province",
            "remarks": "The state or province where this person resides; can be the two-character code or full spelling.",
            "sameAsAttribute": "STATEPROVINCE",
            "sameAsObject": "PERSON",
            "viewColumnName": "STATEPROVINCE",
            "tableName": "PERSON",
            "tableColumnName": "STATEPROVINCE"
        },
        {
            "attributeName": "COUNTRY",
            "required": false,
            "persistent": true,
            "title": "Country",
            "remarks": "The country where this person resides.",
            "sameAsAttribute": "COUNTRY",
            "sameAsObject": "PERSON",
            "viewColumnName": "COUNTRY",
            "tableName": "PERSON",
            "tableColumnName": "COUNTRY"
        },
        {
            "attributeName": "POSTALCODE",
            "required": false,
            "persistent": true,
            "title": "ZIP/Postal Code",
            "remarks": "The zip or postal code of this person.",
            "sameAsAttribute": "POSTALCODE",
            "sameAsObject": "PERSON",
            "viewColumnName": "POSTALCODE",
            "tableName": "PERSON",
            "tableColumnName": "POSTALCODE"
        },
        {
            "attributeName": "VIP",
            "required": false,
            "persistent": true,
            "title": "VIP",
            "remarks": "Indicates if this person is a VIP. This field displays a value indicating the level of importance of the VIP.",
            "sameAsAttribute": "VIP",
            "sameAsObject": "PERSON",
            "viewColumnName": "VIP",
            "tableName": "PERSON",
            "tableColumnName": "VIP"
        },
        {
            "attributeName": "STATUSDATE",
            "required": true,
            "persistent": true,
            "title": "Status Date",
            "remarks": "The date of the last status change.",
            "sameAsAttribute": "STATUSDATE",
            "sameAsObject": "PERSON",
            "viewColumnName": "STATUSDATE",
            "tableName": "PERSON",
            "tableColumnName": "STATUSDATE"
        },
        {
            "attributeName": "ACCEPTINGWFMAIL",
            "required": true,
            "persistent": true,
            "title": "Accepting E-mail",
            "remarks": "System-managed flag indicating whether a user is currently accepting emailed workflow assignments",
            "sameAsAttribute": "ACCEPTINGWFMAIL",
            "sameAsObject": "PERSON",
            "viewColumnName": "ACCEPTINGWFMAIL",
            "tableName": "PERSON",
            "tableColumnName": "ACCEPTINGWFMAIL"
        },
        {
            "attributeName": "WOPRIORITY",
            "required": false,
            "persistent": true,
            "title": "Default WO Priority",
            "remarks": "The default priority a work order receives when reported by this person.",
            "sameAsAttribute": "WOPRIORITY",
            "sameAsObject": "WORKORDER",
            "viewColumnName": "WOPRIORITY",
            "tableName": "PERSON",
            "tableColumnName": "WOPRIORITY"
        },
        {
            "attributeName": "LOCTOSERVREQ",
            "required": true,
            "persistent": true,
            "title": "Default Location to Service Request",
            "remarks": "Indicates if service requests reported by this person will default to the location associated with this person",
            "sameAsAttribute": "LOCTOSERVREQ",
            "sameAsObject": "PERSON",
            "viewColumnName": "LOCTOSERVREQ",
            "tableName": "PERSON",
            "tableColumnName": "LOCTOSERVREQ"
        },
        {
            "attributeName": "PERSONUID",
            "required": true,
            "persistent": true,
            "title": "PERSONUID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "PERSONUID",
            "sameAsObject": "PERSON",
            "viewColumnName": "PERSONUID",
            "tableName": "PERSON",
            "tableColumnName": "PERSONUID"
        },
        {
            "attributeName": "DISPLAYNAME_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Display Name Long Desc",
            "remarks": "NP long description field",
            "sameAsAttribute": "DISPLAYNAME_LONGDESCRIPTION",
            "sameAsObject": "PERSON"
        },
        {
            "attributeName": "NP_STATUSMEMO",
            "required": false,
            "persistent": false,
            "title": "Change Status Memo",
            "remarks": "Status change memo, temporary non-persistent field used by MEA",
            "sameAsAttribute": "MEMO",
            "sameAsObject": "WFTRANSACTION"
        },
        {
            "attributeName": "LANGCODE",
            "required": true,
            "persistent": true,
            "title": "Language Code",
            "remarks": "Language Column",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGCODE",
            "tableName": "PERSON",
            "tableColumnName": "LANGCODE"
        },
        {
            "attributeName": "SENDERSYSID",
            "required": false,
            "persistent": true,
            "title": "Sender System ID",
            "remarks": "Column used by ERP-Integration (APIs)",
            "sameAsAttribute": "SENDERSYSID",
            "sameAsObject": "PERSON",
            "viewColumnName": "SENDERSYSID",
            "tableName": "PERSON",
            "tableColumnName": "SENDERSYSID"
        },
        {
            "attributeName": "SOURCESYSID",
            "required": false,
            "persistent": true,
            "title": "Source System ID",
            "remarks": "Source System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "SOURCESYSID",
            "tableName": "PERSON",
            "tableColumnName": "SOURCESYSID"
        },
        {
            "attributeName": "OWNERSYSID",
            "required": false,
            "persistent": true,
            "title": "Owner System ID",
            "remarks": "Owner System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "OWNERSYSID",
            "tableName": "PERSON",
            "tableColumnName": "OWNERSYSID"
        },
        {
            "attributeName": "EXTERNALREFID",
            "required": false,
            "persistent": true,
            "title": "External Ref ID",
            "remarks": "External Ref ID",
            "sameAsAttribute": "EXTERNALREFID",
            "sameAsObject": "PERSON",
            "viewColumnName": "EXTERNALREFID",
            "tableName": "PERSON",
            "tableColumnName": "EXTERNALREFID"
        },
        {
            "attributeName": "DISPLAYFROM",
            "required": false,
            "persistent": false,
            "title": "Display From",
            "remarks": "Displays the current date. Starting from this date, the Available Work Hours table window displays the seven days of the week. You can modify this date to select a new starting date.",
            "sameAsAttribute": "DISPLAYFROM",
            "sameAsObject": "PERSON"
        },
        {
            "attributeName": "LANGUAGE",
            "required": false,
            "persistent": true,
            "title": "Language",
            "remarks": "This person's language preference for using Maximo.",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGUAGE",
            "tableName": "PERSON",
            "tableColumnName": "LANGUAGE"
        },
        {
            "attributeName": "LOCALE",
            "required": false,
            "persistent": true,
            "title": "Locale",
            "remarks": "The date format and the currency format used in the region where this person resides.",
            "sameAsAttribute": "LOCALE",
            "sameAsObject": "PERSON",
            "viewColumnName": "LOCALE",
            "tableName": "PERSON",
            "tableColumnName": "LOCALE"
        },
        {
            "attributeName": "TIMEZONE",
            "required": false,
            "persistent": true,
            "title": "Time Zone",
            "remarks": "The time zone of this person's location.",
            "sameAsAttribute": "TIMEZONE",
            "sameAsObject": "PERSON",
            "viewColumnName": "TIMEZONE",
            "tableName": "PERSON",
            "tableColumnName": "TIMEZONE"
        },
        {
            "attributeName": "PRIMARYEMAIL",
            "required": false,
            "persistent": false,
            "title": "Primary E-mail",
            "remarks": "The primary email address used to contact this person. To display all email addresses of this person, click the Show/Manage icon to display the Add/Modify Email Addresses dialog box. You can modify this email address directly in the Primay Email field if it is the only email address displayed in the Add/Modify Email Addresses dialog box for this person. The primary email address may not be deleted unless it is the only email address",
            "sameAsAttribute": "EMAILADDRESS",
            "sameAsObject": "EMAIL"
        },
        {
            "attributeName": "PRIMARYPHONE",
            "required": false,
            "persistent": false,
            "title": "Primary Phone",
            "remarks": "The primary phone number that is used to contact this person. To display all phone numbers of this person, click the Show/Manage icon to display the Add/Modify Phone Numbers dialog box. You can modify this number directly in the Primary Phone field if it is the only phone number displayed in the Add/Modify Phone Numbers dialog box for this person. The primary phone number may not be deleted unless it is the only phone number.",
            "sameAsAttribute": "PHONENUM",
            "sameAsObject": "PHONE"
        },
        {
            "attributeName": "PRIMARYCALORG",
            "required": false,
            "persistent": false,
            "title": "Calendar Organization",
            "remarks": "Primary Calendar Organization",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION"
        },
        {
            "attributeName": "PRIMARYCALNUM",
            "required": false,
            "persistent": false,
            "title": "Primary Calendar",
            "remarks": "The primary calendar record associated with this person. To display all calendar records of this person, click the Show/Manage icon to display the Calendars dialog box.",
            "sameAsAttribute": "CALNUM",
            "sameAsObject": "CALENDAR"
        },
        {
            "attributeName": "PRIMARYSHIFTNUM",
            "required": false,
            "persistent": false,
            "title": "Primary Shift",
            "remarks": "The primary shift record associated with this person.",
            "sameAsAttribute": "SHIFTNUM",
            "sameAsObject": "SHIFT"
        },
        {
            "attributeName": "HASLD",
            "required": true,
            "persistent": true,
            "title": "Has Long Description",
            "remarks": "Boolean flag to indicate if there is any long description for this record",
            "sameAsAttribute": "HASLD",
            "sameAsObject": "PERSON",
            "viewColumnName": "HASLD",
            "tableName": "PERSON",
            "tableColumnName": "HASLD"
        },
        {
            "attributeName": "RESPPARTYGROUP",
            "required": true,
            "persistent": true,
            "title": "Person",
            "remarks": "Identifier of the primary member of this person group.",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "RESPPARTYGROUP",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "RESPPARTYGROUP"
        },
        {
            "attributeName": "RESPPARTY",
            "required": true,
            "persistent": true,
            "title": "Person",
            "remarks": "Identifier of the alternate person for a primary member in this person group for Worklfow assignments and notifications.",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "RESPPARTY",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "RESPPARTY"
        },
        {
            "attributeName": "RESPPARTYGROUPSEQ",
            "required": false,
            "persistent": true,
            "title": "Sequence",
            "remarks": "A numerical value that indicates to Workflow the assignment sequence for this person.",
            "sameAsAttribute": "RESPPARTYGROUPSEQ",
            "sameAsObject": "PERSONGROUPTEAM",
            "viewColumnName": "RESPPARTYGROUPSEQ",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "RESPPARTYGROUPSEQ"
        },
        {
            "attributeName": "RESPPARTYSEQ",
            "required": true,
            "persistent": true,
            "title": "Sequence",
            "remarks": "A numerical value that indicates to Workflow the assignment sequence for this alternate person.",
            "sameAsAttribute": "RESPPARTYSEQ",
            "sameAsObject": "PERSONGROUPTEAM",
            "viewColumnName": "RESPPARTYSEQ",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "RESPPARTYSEQ"
        },
        {
            "attributeName": "USEFORORG",
            "required": false,
            "persistent": true,
            "title": "Use for Organization",
            "remarks": "The organization that this person is to be used for. If a value is entered in this field, the Use for Site field becomes read-only.",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "USEFORORG",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "USEFORORG"
        },
        {
            "attributeName": "USEFORSITE",
            "required": false,
            "persistent": true,
            "title": "Use for Site",
            "remarks": "The site that this person is to be used for. If a value is entered in this field, the Use for Organization field becomes read-only.",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "USEFORSITE",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "USEFORSITE"
        },
        {
            "attributeName": "GROUPDEFAULT",
            "required": true,
            "persistent": true,
            "title": "Group Default",
            "remarks": "Indicates that this person is the default person for this group. The first person entered in a group automatically becomes the group default.",
            "sameAsAttribute": "GROUPDEFAULT",
            "sameAsObject": "PERSONGROUPTEAM",
            "viewColumnName": "GROUPDEFAULT",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "GROUPDEFAULT"
        },
        {
            "attributeName": "ORGDEFAULT",
            "required": true,
            "persistent": true,
            "title": "Organization Default",
            "remarks": "Indicates that this person is the default person for an organization. Only one person in each organization can be designated as the default in that organization.",
            "sameAsAttribute": "ORGDEFAULT",
            "sameAsObject": "PERSONGROUPTEAM",
            "viewColumnName": "ORGDEFAULT",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "ORGDEFAULT"
        },
        {
            "attributeName": "SITEDEFAULT",
            "required": true,
            "persistent": true,
            "title": "Site Default",
            "remarks": "Indicates that this person is the default person for a site. Only one person in each site can be designated as the default in that site.",
            "sameAsAttribute": "SITEDEFAULT",
            "sameAsObject": "PERSONGROUPTEAM",
            "viewColumnName": "SITEDEFAULT",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "SITEDEFAULT"
        },
        {
            "attributeName": "PERSONGROUPTEAMID",
            "required": true,
            "persistent": true,
            "title": "PERSONGROUPTEAMID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "PERSONGROUPTEAMID",
            "sameAsObject": "PERSONGROUPTEAM",
            "viewColumnName": "PERSONGROUPTEAMID",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "PERSONGROUPTEAMID"
        },
        {
            "attributeName": "PERSONGROUP",
            "required": false,
            "persistent": true,
            "title": "Person Group",
            "remarks": "REPLACES PERSONGROUPID",
            "sameAsAttribute": "PERSONGROUP",
            "sameAsObject": "PERSONGROUP",
            "viewColumnName": "PERSONGROUP",
            "tableName": "PERSONGROUPTEAM",
            "tableColumnName": "PERSONGROUP"
        },
        {
            "attributeName": "CALNUM",
            "required": false,
            "persistent": false,
            "title": "Calendar",
            "remarks": "The calendar record associated with this person.",
            "sameAsAttribute": "CALNUM",
            "sameAsObject": "CALENDAR"
        },
        {
            "attributeName": "SHIFTNUM",
            "required": false,
            "persistent": false,
            "title": "Shift",
            "remarks": "The shift record associated with this person.",
            "sameAsAttribute": "SHIFTNUM",
            "sameAsObject": "SHIFT"
        },
        {
            "attributeName": "TKCOUNT",
            "required": false,
            "persistent": false,
            "title": "Open Work",
            "remarks": "Number of Open Tickets",
            "sameAsAttribute": null,
            "sameAsObject": null
        }
    ],
    "viewinfo": {
        "autosect": false,
        "viewwhere": null,
        "viewselect": "select person.personid as personid ,person.status as status ,person.displayname as displayname ,person.firstname as firstname ,person.lastname as lastname ,person.department as department ,person.title as title ,person.employeetype as employeetype ,person.jobcode as jobcode ,person.supervisor as supervisor ,person.birthdate as birthdate ,person.lastevaldate as lastevaldate ,person.nextevaldate as nextevaldate ,person.hiredate as hiredate ,person.terminationdate as terminationdate ,person.location as location ,person.locationsite as locationsite ,person.locationorg as locationorg ,person.shiptoaddress as shiptoaddress ,person.billtoaddress as billtoaddress ,person.droppoint as droppoint ,person.wfmailelection as wfmailelection ,person.transemailelection as transemailelection ,person.delegate as delegate ,person.delegatefromdate as delegatefromdate ,person.delegatetodate as delegatetodate ,person.pcardnum as pcardnum ,person.pcardtype as pcardtype ,person.pcardexpdate as pcardexpdate ,person.pcardverification as pcardverification ,person.addressline1 as addressline1 ,person.addressline2 as addressline2 ,person.addressline3 as addressline3 ,person.city as city ,person.regiondistrict as regiondistrict ,person.county as county ,person.stateprovince as stateprovince ,person.country as country ,person.postalcode as postalcode ,person.vip as vip ,person.statusdate as statusdate ,person.acceptingwfmail as acceptingwfmail ,person.wopriority as wopriority ,person.loctoservreq as loctoservreq ,person.personuid as personuid ,person.langcode as langcode ,person.sendersysid as sendersysid ,person.sourcesysid as sourcesysid ,person.ownersysid as ownersysid ,person.externalrefid as externalrefid ,person.language as language ,person.locale as locale ,person.timezone as timezone ,person.hasld as hasld ,person.rowstamp as rowstamp ,persongroupteam.resppartygroup as resppartygroup ,persongroupteam.respparty as respparty ,persongroupteam.resppartygroupseq as resppartygroupseq ,persongroupteam.resppartyseq as resppartyseq ,persongroupteam.usefororg as usefororg ,persongroupteam.useforsite as useforsite ,persongroupteam.groupdefault as groupdefault ,persongroupteam.orgdefault as orgdefault ,persongroupteam.sitedefault as sitedefault ,persongroupteam.persongroupteamid as persongroupteamid ,persongroupteam.persongroup as persongroup ,persongroupteam.rowstamp as rowstamp1",
        "viewfrom": "from persongroupteam  RIGHT OUTER JOIN person on  person.personid =persongroupteam.respparty"
    },
    "outgoingRelationships": [
        {
            "name": "PERSONCAL",
            "target": "PERSONCAL",
            "remarks": null,
            "whereClause": "personid=:personid",
            "cardinality": "UNDEFINED"
        }
    ],
    "incomingRelationships": [
        {
            "name": "PERSONS",
            "source": "PERSONSEARCH",
            "remarks": "Get person records based on search (Scheduler Application)",
            "whereClause": "1=1",
            "cardinality": null
        },
        {
            "name": "PERSONS",
            "source": "TICKET",
            "remarks": null,
            "whereClause": "1=1",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "PERSONS",
            "source": "WORKORDER",
            "remarks": null,
            "whereClause": "1=1",
            "cardinality": "UNDEFINED"
        }
    ]
}