mos = {
    "objectName": "SKDEXTRACAPCREWVIEW",
    "className": "com.ibm.tivoli.maximo.skd.app.SKDExtraCapCrewViewSet",
    "description": "View that combines SKDWORKPLANEXTCAP and AMCREW.",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": null,
    "primaryKeyColumns": [
        "ORGID1",
        "AMCREW"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "AMCREW",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, AMCREW",
            "targetKeys": "ORGID, AMCREW",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew",
            "longDescription": null
        },
        {
            "objectName": "AMCREW",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, AMCREW",
            "targetKeys": "ORGID1, AMCREW",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 22",
            "longDescription": null
        },
        {
            "objectName": "AMCREWT",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "AMCREWTYPE, ORGID",
            "targetKeys": "AMCREWTYPE, ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew Type",
            "longDescription": null
        },
        {
            "objectName": "AMCREWT",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "AMCREWTYPE, ORGID",
            "targetKeys": "AMCREWTYPE, ORGID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 15",
            "longDescription": null
        },
        {
            "objectName": "CALENDAR",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, CALNUM",
            "targetKeys": "ORGID, CALNUM",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew Calendar",
            "longDescription": null
        },
        {
            "objectName": "CALENDAR",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, CALNUM",
            "targetKeys": "ORGID1, CALNUM",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 24",
            "longDescription": null
        },
        {
            "objectName": "COMPANIES",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID, VENDOR",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Vendor on SKDEXTRACAPCREWVIEW",
            "longDescription": null
        },
        {
            "objectName": "COMPANIES",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID1, VENDOR",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Vendor on SKDEXTRACAPCREWVIEW",
            "longDescription": null
        },
        {
            "objectName": "CONTRACT",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "targetKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew Contract",
            "longDescription": null
        },
        {
            "objectName": "CONTRACT",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "targetKeys": "CONTRACTNUM, REVISIONNUM, ORGID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 64",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "RESOURCENAME, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew Item",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Record Language",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "ENDLOCSITEID, ENDLOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "SKD Extra Capacity Crew End Location",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "ENDLOCSITEID, STARTLOCATION",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 216",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "ENDLOCSITEID, WORKLOCATION",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 217",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "STARTLOCSITEID, ENDLOCATION",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 218",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "STARTLOCSITEID, STARTLOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "SKD Extra Capacity Crew Start Location",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "STARTLOCSITEID, WORKLOCATION",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 220",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "WORKSITE, ENDLOCATION",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 221",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "WORKSITE, STARTLOCATION",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 222",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "WORKSITE, WORKLOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "SKD Extra Capacity Crew Work Location",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID1",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization",
            "longDescription": null
        },
        {
            "objectName": "PERSONGROUP",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "PERSONGROUP",
            "targetKeys": "CREWWORKGROUP",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew Work Group",
            "longDescription": null
        },
        {
            "objectName": "SETS",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SETID",
            "targetKeys": "ITEMSETID",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Item Set",
            "longDescription": null
        },
        {
            "objectName": "SHIFT",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, SHIFTNUM",
            "targetKeys": "ORGID, SHIFTNUM",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Crew Shift",
            "longDescription": null
        },
        {
            "objectName": "SHIFT",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "ORGID, SHIFTNUM",
            "targetKeys": "ORGID1, SHIFTNUM",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 25",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID",
            "targetKeys": "ENDLOCSITEID",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 273",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID",
            "targetKeys": "STARTLOCSITEID",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 274",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SITEID",
            "targetKeys": "WORKSITE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Work Site",
            "longDescription": null
        },
        {
            "objectName": "SKDWORKPLANEXTCAP",
            "targetObject": "SKDEXTRACAPCREWVIEW",
            "parentKeys": "SKDWORKPLANEXTCAPID",
            "targetKeys": "SKDWORKPLANEXTCAPID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "SKD Work Plan Next Capacity",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "RANK",
            "required": false,
            "persistent": true,
            "title": "Rank",
            "remarks": "The rank associated with the skill level of a particular craft. The rank is in ascending order, 1 being the lowest.",
            "sameAsAttribute": "RANK",
            "sameAsObject": "CRAFTSKILL",
            "viewColumnName": "RANK",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "RANK"
        },
        {
            "attributeName": "ENDLOCATION",
            "required": false,
            "persistent": true,
            "title": "End Location",
            "remarks": "The last location in a street-level route.",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS",
            "viewColumnName": "ENDLOCATION",
            "tableName": "AMCREW",
            "tableColumnName": "ENDLOCATION"
        },
        {
            "attributeName": "ENDLOCSITEID",
            "required": false,
            "persistent": true,
            "title": "End Location Site Id",
            "remarks": "Start Location SiteId",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "ENDLOCSITEID",
            "tableName": "AMCREW",
            "tableColumnName": "ENDLOCSITEID"
        },
        {
            "attributeName": "AMCREWTYPE",
            "required": true,
            "persistent": true,
            "title": "Crew Type",
            "remarks": "Identifies the crew's type. The crew type defines the crafts, qualifications, and tools that must comprise the crew.",
            "sameAsAttribute": "AMCREWTYPE",
            "sameAsObject": "AMCREWT",
            "viewColumnName": "AMCREWTYPE",
            "tableName": "AMCREW",
            "tableColumnName": "AMCREWTYPE"
        },
        {
            "attributeName": "SKILLNAME",
            "required": false,
            "persistent": true,
            "title": "Skill Name",
            "remarks": "Unique ID of the skill.",
            "sameAsAttribute": "SKILLNAME",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "SKILLNAME",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKILLNAME"
        },
        {
            "attributeName": "STARTLOCATION",
            "required": false,
            "persistent": true,
            "title": "Start Location",
            "remarks": "The first location in a street-level route.",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS",
            "viewColumnName": "STARTLOCATION",
            "tableName": "AMCREW",
            "tableColumnName": "STARTLOCATION"
        },
        {
            "attributeName": "VALUE",
            "required": false,
            "persistent": true,
            "title": "Additional Capacity Required",
            "remarks": "The amount of extra resources that are required in order to complete the work during the specified time period.",
            "sameAsAttribute": "VALUE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "VALUE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "VALUE"
        },
        {
            "attributeName": "HASLD",
            "required": true,
            "persistent": true,
            "title": "Has Long Description",
            "remarks": "Boolean flag to indicate if there is any long description for this record",
            "sameAsAttribute": "HASLD",
            "sameAsObject": "AMCREW",
            "viewColumnName": "HASLD",
            "tableName": "AMCREW",
            "tableColumnName": "HASLD"
        },
        {
            "attributeName": "ENDDATE",
            "required": false,
            "persistent": true,
            "title": "End Date",
            "remarks": "Identifies the end date and time when this additional resource is required.",
            "sameAsAttribute": "ENDDATE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "ENDDATE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "ENDDATE"
        },
        {
            "attributeName": "CALNUM",
            "required": false,
            "persistent": true,
            "title": "Calendar",
            "remarks": "Identifies the work period for the crew. A calendar includes defined shifts. When you select a calendar value for the crew, Maximo also enters that value in the Shift field.",
            "sameAsAttribute": "CALNUM",
            "sameAsObject": "CALENDAR",
            "viewColumnName": "CALNUM",
            "tableName": "AMCREW",
            "tableColumnName": "CALNUM"
        },
        {
            "attributeName": "LANGCODE",
            "required": true,
            "persistent": true,
            "title": "Language Code",
            "remarks": "Language Code",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGCODE",
            "tableName": "AMCREW",
            "tableColumnName": "LANGCODE"
        },
        {
            "attributeName": "CREWDATE",
            "required": false,
            "persistent": false,
            "title": "Date",
            "remarks": "a snapshot date of the crew",
            "sameAsAttribute": "CREWDATE",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "ORGID",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier.",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "LBSLABORBASED",
            "required": true,
            "persistent": true,
            "title": "Use Labor Location",
            "remarks": "Determines whether the location is based on one of the labors on the crew and not on other factors, such as the location of the GPS in the truck.",
            "sameAsAttribute": "LBSLABORBASED",
            "sameAsObject": "AMCREW",
            "viewColumnName": "LBSLABORBASED",
            "tableName": "AMCREW",
            "tableColumnName": "LBSLABORBASED"
        },
        {
            "attributeName": "AVAILABILITY",
            "required": false,
            "persistent": false,
            "title": "Available Hours",
            "remarks": "Available Hours for a given date.",
            "sameAsAttribute": "AVAILABILITY",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "ITEMSETID",
            "required": false,
            "persistent": true,
            "title": "Item Set",
            "remarks": "Identifies the item set.",
            "sameAsAttribute": "SETID",
            "sameAsObject": "SETS",
            "viewColumnName": "ITEMSETID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "ITEMSETID"
        },
        {
            "attributeName": "PERCENTALLOC",
            "required": false,
            "persistent": false,
            "title": "Percent Allocated",
            "remarks": "Percentage of the crew's available hours that has been allocated.",
            "sameAsAttribute": "PERCENTALLOC",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "REVISIONNUM",
            "required": false,
            "persistent": true,
            "title": "Revision",
            "remarks": "Contract Revision Number",
            "sameAsAttribute": "REVISIONNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "REVISIONNUM",
            "tableName": "AMCREW",
            "tableColumnName": "REVISIONNUM"
        },
        {
            "attributeName": "VENDOR",
            "required": false,
            "persistent": true,
            "title": "Vendor",
            "remarks": "Vendor",
            "sameAsAttribute": "COMPANY",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "VENDOR",
            "tableName": "AMCREW",
            "tableColumnName": "VENDOR"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Describes the crew. To enter or view additional information, click the Long Description button.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "AMCREW",
            "viewColumnName": "DESCRIPTION",
            "tableName": "AMCREW",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "LBSINTERVAL",
            "required": false,
            "persistent": true,
            "title": "Location Refresh (in seconds)",
            "remarks": "The interval to refresh the location of a labor or a crew. For example, if you enter 5, the GPS location is refreshed every five seconds.",
            "sameAsAttribute": "LBSINTERVAL",
            "sameAsObject": "AMCREW",
            "viewColumnName": "LBSINTERVAL",
            "tableName": "AMCREW",
            "tableColumnName": "LBSINTERVAL"
        },
        {
            "attributeName": "RATE",
            "required": false,
            "persistent": true,
            "title": "Hourly Rate",
            "remarks": "The sum of the individual labor rates plus the asset rates that are assigned to the crew.",
            "sameAsAttribute": "RATE",
            "sameAsObject": "AMCREW",
            "viewColumnName": "RATE",
            "tableName": "AMCREW",
            "tableColumnName": "RATE"
        },
        {
            "attributeName": "STATUSDATE",
            "required": true,
            "persistent": true,
            "title": "Status Date",
            "remarks": "Date the status was last changed.",
            "sameAsAttribute": "STATUSDATE",
            "sameAsObject": "AMCREW",
            "viewColumnName": "STATUSDATE",
            "tableName": "AMCREW",
            "tableColumnName": "STATUSDATE"
        },
        {
            "attributeName": "RESOURCENAME",
            "required": false,
            "persistent": true,
            "title": "Resource Name",
            "remarks": "Identifies the craft, tool, or crew that is required to complete the work.",
            "sameAsAttribute": "ITEMNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "RESOURCENAME",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "RESOURCENAME"
        },
        {
            "attributeName": "SKDWORKPLANEXTCAPID",
            "required": true,
            "persistent": true,
            "title": "Unique Id",
            "remarks": "Unique Id",
            "sameAsAttribute": "SKDWORKPLANEXTCAPID",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "SKDWORKPLANEXTCAPID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKDWORKPLANEXTCAPID"
        },
        {
            "attributeName": "SHIFTNUM",
            "required": false,
            "persistent": true,
            "title": "Shift",
            "remarks": "Identifies the crew's shift. When you select a calendar value for the crew, Maximo also enters that value in the Shift field.",
            "sameAsAttribute": "SHIFTNUM",
            "sameAsObject": "SHIFT",
            "viewColumnName": "SHIFTNUM",
            "tableName": "AMCREW",
            "tableColumnName": "SHIFTNUM"
        },
        {
            "attributeName": "DISPLAYFROM",
            "required": false,
            "persistent": false,
            "title": "Display From",
            "remarks": "Displays the current date. Starting from this date, the Available Work Hours table window displays the seven days of the week. You can modify this date to select a new starting date.",
            "sameAsAttribute": "DISPLAYFROM",
            "sameAsObject": "PERSON"
        },
        {
            "attributeName": "ASSIGNED",
            "required": true,
            "persistent": false,
            "title": "Assigned",
            "remarks": "Indicates if crew with no availability during the date range is included in the available crew list.",
            "sameAsAttribute": "ASSIGNED",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "STARTLOCSITEID",
            "required": false,
            "persistent": true,
            "title": "Start Location Site Id",
            "remarks": "Start Location SiteId",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "STARTLOCSITEID",
            "tableName": "AMCREW",
            "tableColumnName": "STARTLOCSITEID"
        },
        {
            "attributeName": "ORGID1",
            "required": true,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization to which the crew belongs.The default value is the organization associated with the user's insert site.",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID1",
            "tableName": "AMCREW",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "DESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description Long description",
            "remarks": "Long Description for Description",
            "sameAsAttribute": "DESCRIPTION_LONGDESCRIPTION",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "ORATE",
            "required": false,
            "persistent": true,
            "title": "Override Hourly Rate",
            "remarks": "Specifies the rate for the crew and overrides the hourly rate. The override hourly rate takes priority over the hourly rate.",
            "sameAsAttribute": "ORATE",
            "sameAsObject": "AMCREW",
            "viewColumnName": "ORATE",
            "tableName": "AMCREW",
            "tableColumnName": "ORATE"
        },
        {
            "attributeName": "ENDDATE1",
            "required": false,
            "persistent": false,
            "title": "End Date",
            "remarks": "The end date for the date range of the completed work.",
            "sameAsAttribute": "ENDDATE",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "SKDPROJECTID",
            "required": false,
            "persistent": true,
            "title": "Project Id",
            "remarks": "Unique identifier of the Schedule.",
            "sameAsAttribute": "SKDPROJECTID",
            "sameAsObject": "SKDPROJECT",
            "viewColumnName": "SKDPROJECTID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKDPROJECTID"
        },
        {
            "attributeName": "DAY7",
            "required": false,
            "persistent": false,
            "title": "Day 7",
            "remarks": "Available hours for this crew on the sixth day after the scheduled work date.",
            "sameAsAttribute": "DAY7",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "CREWWORKGROUP",
            "required": false,
            "persistent": true,
            "title": "Crew Work Group",
            "remarks": "The identifier of the person group that is used in the Crews applications. You define crew work groups in the Person Groups application.",
            "sameAsAttribute": "PERSONGROUP",
            "sameAsObject": "PERSONGROUP",
            "viewColumnName": "CREWWORKGROUP",
            "tableName": "AMCREW",
            "tableColumnName": "CREWWORKGROUP"
        },
        {
            "attributeName": "STARTTIME",
            "required": false,
            "persistent": false,
            "title": "Start Time",
            "remarks": "Start time of available hours.",
            "sameAsAttribute": "STARTTIME",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "AMCREW",
            "required": true,
            "persistent": true,
            "title": "Crew",
            "remarks": "Identfies the crew. This value must be unique within an organization.",
            "sameAsAttribute": "AMCREW",
            "sameAsObject": "AMCREW",
            "viewColumnName": "AMCREW",
            "tableName": "AMCREW",
            "tableColumnName": "AMCREW"
        },
        {
            "attributeName": "STARTDATE",
            "required": false,
            "persistent": false,
            "title": "Start Date",
            "remarks": "The start date for the date range of the completed work.",
            "sameAsAttribute": "STARTDATE",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "DAY3",
            "required": false,
            "persistent": false,
            "title": "Day 3",
            "remarks": "Available hours for this crew on the second day after the scheduled work date.",
            "sameAsAttribute": "DAY3",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "DAY4",
            "required": false,
            "persistent": false,
            "title": "Day 4",
            "remarks": "Available hours for this crew on the third day after the scheduled work date.",
            "sameAsAttribute": "DAY4",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "SKILLLEVEL",
            "required": false,
            "persistent": true,
            "title": "Skill Level",
            "remarks": "Identifies the level of skill or expertise in a particular craft.",
            "sameAsAttribute": "SKILLLEVEL",
            "sameAsObject": "CRAFTSKILL",
            "viewColumnName": "SKILLLEVEL",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKILLLEVEL"
        },
        {
            "attributeName": "DAY5",
            "required": false,
            "persistent": false,
            "title": "Day 5",
            "remarks": "Available hours for this crew on the forth day after the scheduled work date.",
            "sameAsAttribute": "DAY5",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "LBSDATAFROMWO",
            "required": true,
            "persistent": true,
            "title": "Save Location with Work Order",
            "remarks": "If the audit history is enabled, and you select the Use Labor Location checkbox, the labor location is stored with the work order data in the LBSLOCATION table. To enable the audit history, configure the Database Configuration application.",
            "sameAsAttribute": "LBSDATAFROMWO",
            "sameAsObject": "AMCREW",
            "viewColumnName": "LBSDATAFROMWO",
            "tableName": "AMCREW",
            "tableColumnName": "LBSDATAFROMWO"
        },
        {
            "attributeName": "AMCREWID",
            "required": true,
            "persistent": true,
            "title": "Unique Id",
            "remarks": "Unique Id",
            "sameAsAttribute": "AMCREWID",
            "sameAsObject": "AMCREW",
            "viewColumnName": "AMCREWID",
            "tableName": "AMCREW",
            "tableColumnName": "AMCREWID"
        },
        {
            "attributeName": "DAY6",
            "required": false,
            "persistent": false,
            "title": "Day 6",
            "remarks": "Available hours for this crew on the fifth day after the scheduled work date.",
            "sameAsAttribute": "DAY6",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "CONTRACTNUM",
            "required": false,
            "persistent": true,
            "title": "Contract",
            "remarks": "The vendor contract number for the labor rate. Contracts are defined in the Labor Rate Contract application.",
            "sameAsAttribute": "CONTRACTNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTNUM",
            "tableName": "AMCREW",
            "tableColumnName": "CONTRACTNUM"
        },
        {
            "attributeName": "DAY1",
            "required": false,
            "persistent": false,
            "title": "Day 1",
            "remarks": "Available hours for this crew on the scheduled work date.",
            "sameAsAttribute": "DAY1",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "DAY2",
            "required": false,
            "persistent": false,
            "title": "Day 2",
            "remarks": "Available hours for this crew on the day after the scheduled work date.",
            "sameAsAttribute": "DAY2",
            "sameAsObject": "AMCREW"
        },
        {
            "attributeName": "STATUS",
            "required": true,
            "persistent": true,
            "title": "Status",
            "remarks": "The current status of the crew. When you create a crew, its default status is Active.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "AMCREW",
            "viewColumnName": "STATUS",
            "tableName": "AMCREW",
            "tableColumnName": "STATUS"
        },
        {
            "attributeName": "TYPE",
            "required": false,
            "persistent": true,
            "title": "Type",
            "remarks": "Identifies the type of resource that is required. Options include craft, tool, or crew.",
            "sameAsAttribute": "TYPE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "TYPE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "TYPE"
        },
        {
            "attributeName": "STARTDATE1",
            "required": false,
            "persistent": true,
            "title": "Start Date",
            "remarks": "Identifies the start date and time when this additional resource is required.",
            "sameAsAttribute": "STARTDATE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "STARTDATE1",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "STARTDATE"
        },
        {
            "attributeName": "WORKLOCATION",
            "required": false,
            "persistent": true,
            "title": "Work Location",
            "remarks": "The location where this labor code works. The work location maybe used to select a labor code for work order assignments. This location's internal labor account is used to set the GL Control Account on all crafts for this labor that are not associated with a vendor. The GL Control Account, in turn, is used as the credit GL account for the labor transaction.",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS",
            "viewColumnName": "WORKLOCATION",
            "tableName": "AMCREW",
            "tableColumnName": "WORKLOCATION"
        },
        {
            "attributeName": "WORKSITE",
            "required": false,
            "persistent": true,
            "title": "Work Site",
            "remarks": "The site where this labor code works.",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "WORKSITE",
            "tableName": "AMCREW",
            "tableColumnName": "WORKSITE"
        },
        {
            "attributeName": "DISPLAYTO",
            "required": false,
            "persistent": false,
            "title": "Display To",
            "remarks": "Displays the current date plus seven days date. Available Work Hours table window displays the seven days of the week. You can modify this date to select a new ending date.",
            "sameAsAttribute": "DISPLAYTO",
            "sameAsObject": "AMCREW"
        }
    ],
    "viewinfo": {
        "autosect": true,
        "viewwhere": "skdworkplanextcap.resourcename= amcrew.amcrew and skdworkplanextcap.orgid=amcrew.orgid "
    },
    "outgoingRelationships": [],
    "incomingRelationships": [
        {
            "name": "SKDEXTRACAPCREWVIEW",
            "source": "SKDPROJECT",
            "remarks": "Relationship to the SKDExtraCapCrewView table, used to find the extra capacity for the schedule.",
            "whereClause": "skdprojectid=:skdprojectid",
            "cardinality": null
        }
    ]
}