mos = {
    "objectName": "DMCOLLECTIONEXPORT",
    "className": "psdi.dm.collection.DMCollectionExportSet",
    "description": "Collection Export File List",
    "longDescription": null,
    "isView": false,
    "isInternal": true,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": "DMCOLLECTIONEXPORTID",
    "primaryKeyColumns": [
        "DMCOLLECTIONOBJECTID",
        "FILENAME"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "DMCOLLECTIONOBJECT",
            "targetObject": "DMCOLLECTIONEXPORT",
            "parentKeys": "DMCOLLECTIONOBJECTID",
            "targetKeys": "DMCOLLECTIONOBJECTID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Migration Collection Object",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "DMCOLLECTIONOBJECTID",
            "required": true,
            "persistent": true,
            "title": "Configuration Owner",
            "remarks": "Unique ID of the Configuration that generate the export file.",
            "sameAsAttribute": "DMCOLLECTIONOBJECTID",
            "sameAsObject": "DMCOLLECTIONOBJECT"
        },
        {
            "attributeName": "FILENAME",
            "required": true,
            "persistent": true,
            "title": "Filename",
            "remarks": "The name of the exported file.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "DOWNLOADED",
            "required": true,
            "persistent": false,
            "title": "Downloaded",
            "remarks": "Was this export file downloaded.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "EXPORTDATE",
            "required": true,
            "persistent": true,
            "title": "Export Date",
            "remarks": "Date when the file was exported.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "DMCOLLECTIONEXPORTID",
            "required": true,
            "persistent": true,
            "title": "Unique Id",
            "remarks": "Unique Id",
            "sameAsAttribute": null,
            "sameAsObject": null
        }
    ],
    "outgoingRelationships": [],
    "incomingRelationships": [
        {
            "name": "DMCOLLECTIONEXPORT",
            "source": "DMCOLLECTIONOBJECT",
            "remarks": "List of files generated by the configuration.",
            "whereClause": "dmcollectionobjectid = :dmcollectionobjectid",
            "cardinality": null
        }
    ]
}