mos = {
    "objectName": "TOOLINV",
    "className": "psdi.app.inventory.ToolInvSet",
    "description": "Tool Inventory View of Inventory",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": true,
    "uniqueId": null,
    "primaryKeyColumns": [
        "ITEMNUM",
        "LOCATION",
        "SITEID",
        "ITEMSETID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "CLASSSTRUCTURE",
            "targetObject": "TOOLINV",
            "parentKeys": "CLASSSTRUCTUREID",
            "targetKeys": "CLASSSTRUCTUREID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Class Structure",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "TOOLINV",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITY, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Commodity",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "TOOLINV",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITYGROUP, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Commodity Group",
            "longDescription": null
        },
        {
            "objectName": "COMPANIES",
            "targetObject": "TOOLINV",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID, CONSVENDOR",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Consignment Vendor on Tool Inventory",
            "longDescription": null
        },
        {
            "objectName": "COMPANIES",
            "targetObject": "TOOLINV",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID, MANUFACTURER",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Manufacturer on Tool Inventory",
            "longDescription": null
        },
        {
            "objectName": "COMPANIES",
            "targetObject": "TOOLINV",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID, VENDOR",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Primary Vendor on Tool Inventory",
            "longDescription": null
        },
        {
            "objectName": "INVENTORY",
            "targetObject": "TOOLINV",
            "parentKeys": "INVENTORYID",
            "targetKeys": "INVENTORYID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Tool Inventory",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "TOOLINV",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "ITEMNUM, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Item",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "TOOLINV",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "ITEMNUM3, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Item",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "TOOLINV",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Language for the record",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "TOOLINV",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "SITEID, LOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Tool Location",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "TOOLINV",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "SITEID, STORELOC",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 200",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "TOOLINV",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "STORELOCSITEID, LOCATION",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 201",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "TOOLINV",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "STORELOCSITEID, STORELOC",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Tool Storeroom Location",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ISSUEUNIT, SITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 234",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ISSUEUNIT, STORELOCSITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 235",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ISSUEUNIT3, SITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 236",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ISSUEUNIT3, STORELOCSITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 237",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ORDERUNIT, SITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 238",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ORDERUNIT, STORELOCSITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 239",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ORDERUNIT3, SITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 240",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID, SITEID, ORGID",
            "targetKeys": "ORDERUNIT3, STORELOCSITEID, ORGID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 241",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID",
            "targetKeys": "ISSUEUNIT",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Issue Measure Unit",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID",
            "targetKeys": "ISSUEUNIT3",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Measure Unit",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID",
            "targetKeys": "ORDERUNIT",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Order Measure Unit",
            "longDescription": null
        },
        {
            "objectName": "MEASUREUNIT",
            "targetObject": "TOOLINV",
            "parentKeys": "MEASUREUNITID",
            "targetKeys": "ORDERUNIT3",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Measure Unit",
            "longDescription": null
        },
        {
            "objectName": "METER",
            "targetObject": "TOOLINV",
            "parentKeys": "METERNAME",
            "targetKeys": "METERNAME",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Meter",
            "longDescription": null
        },
        {
            "objectName": "METERGROUP",
            "targetObject": "TOOLINV",
            "parentKeys": "GROUPNAME",
            "targetKeys": "GROUPNAME",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Meter Group",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "TOOLINV",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "SETS",
            "targetObject": "TOOLINV",
            "parentKeys": "SETID",
            "targetKeys": "ITEMSETID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 63",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "TOOLINV",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "TOOLINV",
            "parentKeys": "SITEID",
            "targetKeys": "STORELOCSITEID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 277",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "ITEMSETID",
            "required": true,
            "persistent": true,
            "title": "Item Set",
            "remarks": "Identifies the item set, or group of items, to which this tool belongs.",
            "sameAsAttribute": "SETID",
            "sameAsObject": "SETS",
            "viewColumnName": "ITEMSETID",
            "tableName": "INVENTORY",
            "tableColumnName": "ITEMSETID"
        },
        {
            "attributeName": "ITEMSETID1",
            "required": true,
            "persistent": true,
            "title": "Item Set",
            "remarks": "Identifies the item set, or group of items, to which this item belongs. An organization is assigned to only one item set, but multiple organizations can use the same item set. Click the Select Value button to choose an item set.",
            "sameAsAttribute": "SETID",
            "sameAsObject": "SETS",
            "viewColumnName": "ITEMSETID1",
            "tableName": "ITEM",
            "tableColumnName": "ITEMSETID"
        },
        {
            "attributeName": "MANUFACTURER",
            "required": false,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Identifies the manufacturer of the tool for a particular vendor. Click the Detail Menu button to view a list of companies or go to the Companies applications.",
            "sameAsAttribute": "COMPANY",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "MANUFACTURER",
            "tableName": "INVENTORY",
            "tableColumnName": "MANUFACTURER"
        },
        {
            "attributeName": "MODELNUM",
            "required": false,
            "persistent": true,
            "title": "Model",
            "remarks": "Model number for the item from the primary vendor.",
            "sameAsAttribute": "MODELNUM",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "MODELNUM",
            "tableName": "INVENTORY",
            "tableColumnName": "MODELNUM"
        },
        {
            "attributeName": "ORDERUNIT",
            "required": false,
            "persistent": true,
            "title": "Order Unit",
            "remarks": "Unit Of Order",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ORDERUNIT",
            "tableName": "ITEM",
            "tableColumnName": "ORDERUNIT"
        },
        {
            "attributeName": "SHRINKAGEACC",
            "required": false,
            "persistent": true,
            "title": "Shrinkage GL Account",
            "remarks": "Shrinkage Account.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "SHRINKAGEACC",
            "tableName": "INVENTORY",
            "tableColumnName": "SHRINKAGEACC"
        },
        {
            "attributeName": "SSTOCK",
            "required": false,
            "persistent": true,
            "title": "Safety Stock",
            "remarks": "Safety Stock",
            "sameAsAttribute": "SSTOCK",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "SSTOCK",
            "tableName": "INVENTORY",
            "tableColumnName": "SSTOCK"
        },
        {
            "attributeName": "VENDOR",
            "required": false,
            "persistent": true,
            "title": "Primary Vendor",
            "remarks": "Code from the Companies application for the primary vendor that supplies this tool. Click the Detail Menu button to view a list of companies or go to the Companies application.",
            "sameAsAttribute": "COMPANY",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "VENDOR",
            "tableName": "INVENTORY",
            "tableColumnName": "VENDOR"
        },
        {
            "attributeName": "ABCTYPE",
            "required": false,
            "persistent": true,
            "title": "ABC Type",
            "remarks": "Identifies the type of inventory, telling you which inventory items represent your company's greatest investment in terms of monetary value and turnover rate. MAXIMO sets the type to A, B, or C based on a percentage that the system administrator sets in MultiSite. You can set the ABC type to N, for no category, to exclude this item from the ABC analysis. Click the Select Value button to view the list of types.",
            "sameAsAttribute": "ABCTYPE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ABCTYPE",
            "tableName": "INVENTORY",
            "tableColumnName": "ABCTYPE"
        },
        {
            "attributeName": "BINNUM",
            "required": false,
            "persistent": true,
            "title": "Default Bin",
            "remarks": "Identifies the primary bin or storage location for the selected tool within a storeroom.",
            "sameAsAttribute": "BINNUM",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "BINNUM",
            "tableName": "INVENTORY",
            "tableColumnName": "BINNUM"
        },
        {
            "attributeName": "CATALOGCODE",
            "required": false,
            "persistent": true,
            "title": "Catalog #",
            "remarks": "Primary vendor catalog number or product list number for the tool.",
            "sameAsAttribute": "CATALOGCODE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "CATALOGCODE",
            "tableName": "INVENTORY",
            "tableColumnName": "CATALOGCODE"
        },
        {
            "attributeName": "CONTROLACC",
            "required": false,
            "persistent": true,
            "title": "GL Control Account",
            "remarks": "Control Account.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CONTROLACC",
            "tableName": "INVENTORY",
            "tableColumnName": "CONTROLACC"
        },
        {
            "attributeName": "GLACCOUNT",
            "required": false,
            "persistent": true,
            "title": "GL Account",
            "remarks": "GL Account code.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "GLACCOUNT",
            "tableName": "INVENTORY",
            "tableColumnName": "GLACCOUNT"
        },
        {
            "attributeName": "INVCOSTADJACC",
            "required": false,
            "persistent": true,
            "title": "Cost Adjustment GL Account",
            "remarks": "Cost Adjustment Account.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "INVCOSTADJACC",
            "tableName": "INVENTORY",
            "tableColumnName": "INVCOSTADJACC"
        },
        {
            "attributeName": "ISSUEUNIT",
            "required": false,
            "persistent": true,
            "title": "Issue Unit",
            "remarks": "Standard quantity by which the tool is issued from the storeroom, such as each or roll. Click the Select Value button to view a list of valid issue units.",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ISSUEUNIT",
            "tableName": "INVENTORY",
            "tableColumnName": "ISSUEUNIT"
        },
        {
            "attributeName": "LASTISSUEDATE",
            "required": false,
            "persistent": true,
            "title": "Last Issue Date",
            "remarks": "Calendar date the tool was last issued from the storeroom.",
            "sameAsAttribute": "LASTISSUEDATE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "LASTISSUEDATE",
            "tableName": "INVENTORY",
            "tableColumnName": "LASTISSUEDATE"
        },
        {
            "attributeName": "ORGID",
            "required": true,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "INVENTORY",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "SITEID",
            "required": true,
            "persistent": true,
            "title": "Site",
            "remarks": "Identifies the site of the storeroom where the tool is stocked. Click the Select Value button to view a list of valid sites.",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "SITEID",
            "tableName": "INVENTORY",
            "tableColumnName": "SITEID"
        },
        {
            "attributeName": "SOURCESYSID",
            "required": false,
            "persistent": true,
            "title": "Source System ID",
            "remarks": "Source System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "SOURCESYSID",
            "tableName": "INVENTORY",
            "tableColumnName": "SOURCESYSID"
        },
        {
            "attributeName": "OWNERSYSID",
            "required": false,
            "persistent": true,
            "title": "Owner System ID",
            "remarks": "Owner System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "OWNERSYSID",
            "tableName": "INVENTORY",
            "tableColumnName": "OWNERSYSID"
        },
        {
            "attributeName": "OWNERSYSID1",
            "required": false,
            "persistent": true,
            "title": "Owner System ID",
            "remarks": "Owner System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "OWNERSYSID1",
            "tableName": "ITEM",
            "tableColumnName": "OWNERSYSID"
        },
        {
            "attributeName": "EXTERNALREFID",
            "required": false,
            "persistent": true,
            "title": "External Reference ID",
            "remarks": "External Reference ID",
            "sameAsAttribute": "EXTERNALREFID",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "EXTERNALREFID",
            "tableName": "INVENTORY",
            "tableColumnName": "EXTERNALREFID"
        },
        {
            "attributeName": "EXTERNALREFID1",
            "required": false,
            "persistent": true,
            "title": "External Reference ID",
            "remarks": "External Reference ID",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "EXTERNALREFID1",
            "tableName": "ITEM",
            "tableColumnName": "EXTERNALREFID"
        },
        {
            "attributeName": "CATEGORY",
            "required": true,
            "persistent": true,
            "title": "Stock Category",
            "remarks": "Indicates type of stock for the item: stocked (STK), non-stocked (NS), or special order (SP). Click the Select Value button to view the list of stock categories.",
            "sameAsAttribute": "CATEGORY",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "CATEGORY",
            "tableName": "INVENTORY",
            "tableColumnName": "CATEGORY"
        },
        {
            "attributeName": "CCF",
            "required": true,
            "persistent": true,
            "title": "Cycle Count Frequency",
            "remarks": "Cycle Count Frequency",
            "sameAsAttribute": "CCF",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "CCF",
            "tableName": "INVENTORY",
            "tableColumnName": "CCF"
        },
        {
            "attributeName": "DELIVERYTIME",
            "required": true,
            "persistent": true,
            "title": "Delivery Time",
            "remarks": "Delivery Time",
            "sameAsAttribute": "DELIVERYTIME",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "DELIVERYTIME",
            "tableName": "INVENTORY",
            "tableColumnName": "DELIVERYTIME"
        },
        {
            "attributeName": "ISSUE1YRAGO",
            "required": true,
            "persistent": true,
            "title": "Last Year",
            "remarks": "Quantity of this tool that was issued last year, over the calendar year.",
            "sameAsAttribute": "ISSUE1YRAGO",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ISSUE1YRAGO",
            "tableName": "INVENTORY",
            "tableColumnName": "ISSUE1YRAGO"
        },
        {
            "attributeName": "ISSUE2YRAGO",
            "required": true,
            "persistent": true,
            "title": "2 Years Ago",
            "remarks": "Quantity of this tool that was issued two years ago, over a calendar year.",
            "sameAsAttribute": "ISSUE2YRAGO",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ISSUE2YRAGO",
            "tableName": "INVENTORY",
            "tableColumnName": "ISSUE2YRAGO"
        },
        {
            "attributeName": "ISSUE3YRAGO",
            "required": true,
            "persistent": true,
            "title": "Issued 3 Years Ago",
            "remarks": "Number Of Items Issued 3 Years Ago",
            "sameAsAttribute": "ISSUE3YRAGO",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ISSUE3YRAGO",
            "tableName": "INVENTORY",
            "tableColumnName": "ISSUE3YRAGO"
        },
        {
            "attributeName": "ISSUEYTD",
            "required": true,
            "persistent": true,
            "title": "Year to Date",
            "remarks": "Quantity of the tool that has been issued so far this year.",
            "sameAsAttribute": "ISSUEYTD",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ISSUEYTD",
            "tableName": "INVENTORY",
            "tableColumnName": "ISSUEYTD"
        },
        {
            "attributeName": "ITEMNUM",
            "required": true,
            "persistent": true,
            "title": "Tool",
            "remarks": "Indentifies the inventory number for this tool. Click the Detail Menu button to view a list of valid tools, search for a tool by classification, or view a tool's availability.",
            "sameAsAttribute": "ITEMNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMNUM",
            "tableName": "INVENTORY",
            "tableColumnName": "ITEMNUM"
        },
        {
            "attributeName": "LOCATION",
            "required": true,
            "persistent": true,
            "title": "Storeroom",
            "remarks": "Location where the tool is stored. Click the Detail Menu button to view a list of valid storerooms, go to the Storerooms application, or view the Illustrated Parts Catalog.",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS",
            "viewColumnName": "LOCATION",
            "tableName": "INVENTORY",
            "tableColumnName": "LOCATION"
        },
        {
            "attributeName": "MAXLEVEL",
            "required": true,
            "persistent": true,
            "title": "Reorder Point",
            "remarks": "Maximum Level - Reorder Point",
            "sameAsAttribute": "MAXLEVEL",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "MAXLEVEL",
            "tableName": "INVENTORY",
            "tableColumnName": "MAXLEVEL"
        },
        {
            "attributeName": "MINLEVEL",
            "required": true,
            "persistent": true,
            "title": "Minimum Level",
            "remarks": "Minimum Level - Reorder Point",
            "sameAsAttribute": "MINLEVEL",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "MINLEVEL",
            "tableName": "INVENTORY",
            "tableColumnName": "MINLEVEL"
        },
        {
            "attributeName": "ORDERQTY",
            "required": true,
            "persistent": true,
            "title": "Economic Order Quantity",
            "remarks": "Reorder Quantity",
            "sameAsAttribute": "ORDERQTY",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ORDERQTY",
            "tableName": "INVENTORY",
            "tableColumnName": "ORDERQTY"
        },
        {
            "attributeName": "SENDERSYSID",
            "required": false,
            "persistent": true,
            "title": "Sender System ID",
            "remarks": "Column used by ERP-Integration (APIs)",
            "sameAsAttribute": "SENDERSYSID",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "SENDERSYSID",
            "tableName": "INVENTORY",
            "tableColumnName": "SENDERSYSID"
        },
        {
            "attributeName": "ADDTOSTORELOC",
            "required": false,
            "persistent": false,
            "title": "Location",
            "remarks": "ADDTOSTORELOC",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "RESERVEDQTY",
            "required": false,
            "persistent": false,
            "title": "Quantity Currently Reserved",
            "remarks": "Qauntity of the tool that is currently being reserved for use on work plans or jobs.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "EXPIREDQTY",
            "required": false,
            "persistent": false,
            "title": "Expired Quantity in Stock",
            "remarks": "Quantity of the tool that is expired in the storeroom.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "AVBLBALANCE",
            "required": false,
            "persistent": false,
            "title": "Quantity Available",
            "remarks": "Quantity of the tool available to issue. Available balance is the Current Balance minus any reserved or expired tools.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "LOTNUM",
            "required": false,
            "persistent": false,
            "title": "Lot",
            "remarks": "Lot number of the item if the item is lotted.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CURBAL",
            "required": false,
            "persistent": false,
            "title": "Current Balance",
            "remarks": "Current Balance",
            "sameAsAttribute": "CURBAL",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "CURBALTOTAL",
            "required": false,
            "persistent": false,
            "title": "Current Balance",
            "remarks": "Quantity of the tool that currently exists in storeroom.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CONDITIONCODE",
            "required": false,
            "persistent": false,
            "title": "Condition Code",
            "remarks": "Item condition code",
            "sameAsAttribute": "CONDITIONCODE",
            "sameAsObject": "ITEMCONDITION"
        },
        {
            "attributeName": "CONDRATE",
            "required": false,
            "persistent": false,
            "title": "Condition Rate Percentage",
            "remarks": "Item condition rate percentage",
            "sameAsAttribute": "CONDRATE",
            "sameAsObject": "ITEMCONDITION"
        },
        {
            "attributeName": "STDCOST",
            "required": false,
            "persistent": false,
            "title": "Standard Cost",
            "remarks": "Standard Item Cost",
            "sameAsAttribute": "STDCOST",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "AVGCOST",
            "required": false,
            "persistent": false,
            "title": "Average Cost",
            "remarks": "Average Item Cost",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "LASTCOST",
            "required": false,
            "persistent": false,
            "title": "Last Cost",
            "remarks": "Last Item Cost",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "PHYSCNTDATE",
            "required": false,
            "persistent": false,
            "title": "Physical Count Date",
            "remarks": "A nonpersistent column to PopulateCount Date field .",
            "sameAsAttribute": "PHYSCNTDATE",
            "sameAsObject": "INVBALANCES"
        },
        {
            "attributeName": "INVENTORYID",
            "required": true,
            "persistent": true,
            "title": "INVENTORYID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "INVENTORYID",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "INVENTORYID",
            "tableName": "INVENTORY",
            "tableColumnName": "INVENTORYID"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Item Description",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "ITEM",
            "viewColumnName": "DESCRIPTION",
            "tableName": "ITEM",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "ROTATING",
            "required": true,
            "persistent": true,
            "title": "Rotating",
            "remarks": "Is Item A Rotating Asset?",
            "sameAsAttribute": "ROTATING",
            "sameAsObject": "ITEM",
            "viewColumnName": "ROTATING",
            "tableName": "ITEM",
            "tableColumnName": "ROTATING"
        },
        {
            "attributeName": "LOTTYPE",
            "required": true,
            "persistent": true,
            "title": "Lot Type",
            "remarks": "Lot type (LOT or NOLOT)",
            "sameAsAttribute": "LOTTYPE",
            "sameAsObject": "ITEM",
            "viewColumnName": "LOTTYPE",
            "tableName": "ITEM",
            "tableColumnName": "LOTTYPE"
        },
        {
            "attributeName": "CAPITALIZED",
            "required": true,
            "persistent": true,
            "title": "Capitalized",
            "remarks": "Is Item Capitalized? (Y or N)",
            "sameAsAttribute": "CAPITALIZED",
            "sameAsObject": "ITEM",
            "viewColumnName": "CAPITALIZED",
            "tableName": "ITEM",
            "tableColumnName": "CAPITALIZED"
        },
        {
            "attributeName": "MSDSNUM",
            "required": false,
            "persistent": true,
            "title": "MSDS",
            "remarks": "MSDS # - For OSHA Requirements",
            "sameAsAttribute": "MSDSNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "MSDSNUM",
            "tableName": "ITEM",
            "tableColumnName": "MSDSNUM"
        },
        {
            "attributeName": "OUTSIDE",
            "required": true,
            "persistent": true,
            "title": "Outside",
            "remarks": "Is Item an Outside Item?",
            "sameAsAttribute": "OUTSIDE",
            "sameAsObject": "ITEM",
            "viewColumnName": "OUTSIDE",
            "tableName": "ITEM",
            "tableColumnName": "OUTSIDE"
        },
        {
            "attributeName": "IN19",
            "required": false,
            "persistent": true,
            "title": "Extra Field 19",
            "remarks": "Extra Field 19",
            "sameAsAttribute": "IN19",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN19",
            "tableName": "ITEM",
            "tableColumnName": "IN19"
        },
        {
            "attributeName": "IN20",
            "required": false,
            "persistent": true,
            "title": "Extra Field 20",
            "remarks": "Extra Field 20",
            "sameAsAttribute": "IN20",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN20",
            "tableName": "ITEM",
            "tableColumnName": "IN20"
        },
        {
            "attributeName": "IN21",
            "required": false,
            "persistent": true,
            "title": "Extra Field 21",
            "remarks": "Extra Field 21",
            "sameAsAttribute": "IN21",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN21",
            "tableName": "ITEM",
            "tableColumnName": "IN21"
        },
        {
            "attributeName": "IN22",
            "required": false,
            "persistent": true,
            "title": "Extra Field 22",
            "remarks": "Extra Field 22",
            "sameAsAttribute": "IN22",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN22",
            "tableName": "ITEM",
            "tableColumnName": "IN22"
        },
        {
            "attributeName": "IN23",
            "required": false,
            "persistent": true,
            "title": "Extra Field 23",
            "remarks": "Extra Field 23",
            "sameAsAttribute": "IN23",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN23",
            "tableName": "ITEM",
            "tableColumnName": "IN23"
        },
        {
            "attributeName": "SPAREPARTAUTOADD",
            "required": true,
            "persistent": true,
            "title": "Automatically Add as Spare",
            "remarks": "Indicates that the item is eligible to be added automatically as a spare part.",
            "sameAsAttribute": "SPAREPARTAUTOADD",
            "sameAsObject": "ITEM",
            "viewColumnName": "SPAREPARTAUTOADD",
            "tableName": "ITEM",
            "tableColumnName": "SPAREPARTAUTOADD"
        },
        {
            "attributeName": "CLASSSTRUCTUREID",
            "required": false,
            "persistent": true,
            "title": "Class Structure",
            "remarks": "Class Structure identifier",
            "sameAsAttribute": "CLASSSTRUCTUREID",
            "sameAsObject": "CLASSSTRUCTURE",
            "viewColumnName": "CLASSSTRUCTUREID",
            "tableName": "ITEM",
            "tableColumnName": "CLASSSTRUCTUREID"
        },
        {
            "attributeName": "INSPECTIONREQUIRED",
            "required": true,
            "persistent": true,
            "title": "Inspection Required",
            "remarks": "Indicates whether inspection of item is required upon receipt.",
            "sameAsAttribute": "INSPECTIONREQUIRED",
            "sameAsObject": "ITEM",
            "viewColumnName": "INSPECTIONREQUIRED",
            "tableName": "ITEM",
            "tableColumnName": "INSPECTIONREQUIRED"
        },
        {
            "attributeName": "IN24",
            "required": false,
            "persistent": true,
            "title": "IN24",
            "remarks": "Extra Field 24",
            "sameAsAttribute": "IN24",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN24",
            "tableName": "ITEM",
            "tableColumnName": "IN24"
        },
        {
            "attributeName": "IN25",
            "required": false,
            "persistent": true,
            "title": "IN25",
            "remarks": "Extra Field 25",
            "sameAsAttribute": "IN25",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN25",
            "tableName": "ITEM",
            "tableColumnName": "IN25"
        },
        {
            "attributeName": "IN26",
            "required": false,
            "persistent": true,
            "title": "IN26",
            "remarks": "Extra Field 26",
            "sameAsAttribute": "IN26",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN26",
            "tableName": "ITEM",
            "tableColumnName": "IN26"
        },
        {
            "attributeName": "IN27",
            "required": false,
            "persistent": true,
            "title": "IN27",
            "remarks": "Extra Field 27",
            "sameAsAttribute": "IN27",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN27",
            "tableName": "ITEM",
            "tableColumnName": "IN27"
        },
        {
            "attributeName": "DESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Details",
            "remarks": "Long Description for Item Description",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "ITEM_DESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description",
            "remarks": "Description of this item.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "ITEM_ID",
            "required": false,
            "persistent": false,
            "title": "Item",
            "remarks": "Inventory item number.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HASIAS",
            "required": true,
            "persistent": false,
            "title": "Rotating",
            "remarks": "HASIAS",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "INSTANCE",
            "required": false,
            "persistent": false,
            "title": "Instance",
            "remarks": "INSTANCE",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CONDITIONENABLED",
            "required": true,
            "persistent": true,
            "title": "Condition Enabled",
            "remarks": "Is this item condition enabled?",
            "sameAsAttribute": "CONDITIONENABLED",
            "sameAsObject": "ITEM",
            "viewColumnName": "CONDITIONENABLED",
            "tableName": "ITEM",
            "tableColumnName": "CONDITIONENABLED"
        },
        {
            "attributeName": "GROUPNAME",
            "required": false,
            "persistent": true,
            "title": "Group",
            "remarks": "Meter group for the item.  This attribute pertains to rotating items only, and is used to set the GroupName attribute of the new asset created from this item during the application of an item assembly structure.",
            "sameAsAttribute": "GROUPNAME",
            "sameAsObject": "METERGROUP",
            "viewColumnName": "GROUPNAME",
            "tableName": "ITEM",
            "tableColumnName": "GROUPNAME"
        },
        {
            "attributeName": "METERNAME",
            "required": false,
            "persistent": true,
            "title": "Meter",
            "remarks": "Meter associated with the item.  This is the meter for which a reading is to be recorded when this item is issued to an asset.  Only non-rotating items can be associated with a meter.",
            "sameAsAttribute": "METERNAME",
            "sameAsObject": "METER",
            "viewColumnName": "METERNAME",
            "tableName": "ITEM",
            "tableColumnName": "METERNAME"
        },
        {
            "attributeName": "COMMODITYGROUP",
            "required": false,
            "persistent": true,
            "title": "Commodity Group",
            "remarks": "Commodity Group",
            "sameAsAttribute": "COMMODITY",
            "sameAsObject": "COMMODITIES",
            "viewColumnName": "COMMODITYGROUP",
            "tableName": "ITEM",
            "tableColumnName": "COMMODITYGROUP"
        },
        {
            "attributeName": "COMMODITY",
            "required": false,
            "persistent": true,
            "title": "Commodity Code",
            "remarks": "Commodity",
            "sameAsAttribute": "COMMODITY",
            "sameAsObject": "COMMODITIES",
            "viewColumnName": "COMMODITY",
            "tableName": "ITEM",
            "tableColumnName": "COMMODITY"
        },
        {
            "attributeName": "ITEMTYPE",
            "required": true,
            "persistent": true,
            "title": "Type",
            "remarks": "Item Type",
            "sameAsAttribute": "ITEMTYPE",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMTYPE",
            "tableName": "ITEM",
            "tableColumnName": "ITEMTYPE"
        },
        {
            "attributeName": "PRORATE",
            "required": true,
            "persistent": true,
            "title": "Prorate Service",
            "remarks": "Prorate Service?",
            "sameAsAttribute": "PRORATE",
            "sameAsObject": "ITEM",
            "viewColumnName": "PRORATE",
            "tableName": "ITEM",
            "tableColumnName": "PRORATE"
        },
        {
            "attributeName": "ITEMID",
            "required": true,
            "persistent": true,
            "title": "ITEMID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "ITEMID",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMID",
            "tableName": "ITEM",
            "tableColumnName": "ITEMID"
        },
        {
            "attributeName": "ISKIT",
            "required": true,
            "persistent": true,
            "title": "Kit",
            "remarks": "is this item a kit, or collection of items defined in the ItemStruct table",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "ISKIT",
            "tableName": "ITEM",
            "tableColumnName": "ISKIT"
        },
        {
            "attributeName": "KITCOMPONENTTOADDTOSTORE",
            "required": true,
            "persistent": false,
            "title": "Is Kit Component to Be Added to Store",
            "remarks": "non-persistent attribute used when adding the kit to which this item belongs to a storeroom.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "LANGCODE",
            "required": true,
            "persistent": true,
            "title": "Language Code",
            "remarks": "Language Column",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGCODE",
            "tableName": "ITEM",
            "tableColumnName": "LANGCODE"
        },
        {
            "attributeName": "HOLDINGBAL",
            "required": false,
            "persistent": false,
            "title": "Holding Balance",
            "remarks": "Balance located in the holding location",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "ATTACHONISSUE",
            "required": true,
            "persistent": true,
            "title": "Attach to Parent Equipment on Issue",
            "remarks": "Attach to parent equipment on issue",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "ATTACHONISSUE",
            "tableName": "ITEM",
            "tableColumnName": "ATTACHONISSUE"
        },
        {
            "attributeName": "HASLD",
            "required": true,
            "persistent": true,
            "title": "Has Long Description",
            "remarks": "Boolean flag to indicate if there is any long description for this record",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "HASLD",
            "tableName": "ITEM",
            "tableColumnName": "HASLD"
        },
        {
            "attributeName": "STORELOC",
            "required": false,
            "persistent": true,
            "title": "Storeroom",
            "remarks": "Storeroom Location",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS",
            "viewColumnName": "STORELOC",
            "tableName": "INVENTORY",
            "tableColumnName": "STORELOC"
        },
        {
            "attributeName": "STORELOCSITEID",
            "required": false,
            "persistent": true,
            "title": "Storeroom Site",
            "remarks": "Identifies the site where the storeroom is located.",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "STORELOCSITEID",
            "tableName": "INVENTORY",
            "tableColumnName": "STORELOCSITEID"
        },
        {
            "attributeName": "INTERNAL",
            "required": true,
            "persistent": true,
            "title": "Internal",
            "remarks": "Internal Flag used for Reorder",
            "sameAsAttribute": "INTERNAL",
            "sameAsObject": "PO",
            "viewColumnName": "INTERNAL",
            "tableName": "INVENTORY",
            "tableColumnName": "INTERNAL"
        },
        {
            "attributeName": "MAXISSUE",
            "required": false,
            "persistent": true,
            "title": "Maximum Quantity Issued",
            "remarks": "Total maximum quantity that can be issued to an asset.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "MAXISSUE",
            "tableName": "ITEM",
            "tableColumnName": "MAXISSUE"
        },
        {
            "attributeName": "ITEMSTATUS",
            "required": false,
            "persistent": true,
            "title": "Status",
            "remarks": "The current status of the item such as ACTIVE, PENDING, PLANNING, PENDOBS and OBSELETE.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "ITEMSTATUS",
            "tableName": "ITEM",
            "tableColumnName": "STATUS"
        },
        {
            "attributeName": "ITEMSTATUSDATE",
            "required": false,
            "persistent": true,
            "title": "Status Date",
            "remarks": "Date the work order status was last changed.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "ITEMSTATUSDATE",
            "tableName": "ITEM",
            "tableColumnName": "STATUSDATE"
        },
        {
            "attributeName": "HIERARCHYPATH",
            "required": false,
            "persistent": false,
            "title": "Hierarchy Path",
            "remarks": "Sets value to HIERARCHYPATH, if the item has an associated CLASSSTRUCTURE record",
            "sameAsAttribute": "HIERARCHYPATH",
            "sameAsObject": "CLASSSTRUCTURE"
        },
        {
            "attributeName": "STATUSIFACE",
            "required": true,
            "persistent": false,
            "title": "Has Status Changed",
            "remarks": "Non persistent boolean field to indicate whether the status has been changed after the stateful object is fetched from the database.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "NP_STATUSMEMO",
            "required": false,
            "persistent": false,
            "title": "Change Status Memo",
            "remarks": "Status change memo, temporary non-persistent field used by MEA",
            "sameAsAttribute": "MEMO",
            "sameAsObject": "WFTRANSACTION"
        },
        {
            "attributeName": "NP_STATUSROLLDOWN",
            "required": true,
            "persistent": false,
            "title": "Roll New Status to Organizations and Inventory",
            "remarks": "Roll New Status to Organizations and Inventory, temporary non-persistent field used by MEA",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "STATUS",
            "required": true,
            "persistent": true,
            "title": "Status",
            "remarks": "The current status of the item such as ACTIVE, PENDING, PLANNING, PENDOBS and OBSELETE.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "ITEM",
            "viewColumnName": "STATUS",
            "tableName": "INVENTORY",
            "tableColumnName": "STATUS"
        },
        {
            "attributeName": "STATUSDATE",
            "required": true,
            "persistent": true,
            "title": "Status Date",
            "remarks": "Date the work order status was last changed.",
            "sameAsAttribute": "STATUSDATE",
            "sameAsObject": "ITEM",
            "viewColumnName": "STATUSDATE",
            "tableName": "INVENTORY",
            "tableColumnName": "STATUSDATE"
        },
        {
            "attributeName": "ORDERUNIT3",
            "required": false,
            "persistent": true,
            "title": "Order Unit",
            "remarks": "Unit Of Order. A unit can be each, box, roll, linear feet, cubic feet, square feet etc. For example, 1 box is 1 unit, but the box may be a part of a larger inventory issue element, perhaps a case or crate.",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ORDERUNIT3",
            "tableName": "INVENTORY",
            "tableColumnName": "ORDERUNIT"
        },
        {
            "attributeName": "ISSUEUNIT3",
            "required": false,
            "persistent": true,
            "title": "Issue Unit",
            "remarks": "Unit of measure used to issue the item from the storeroom, such as EACH or ROLL. Click the Select Value button to choose an issue unit.",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ISSUEUNIT3",
            "tableName": "ITEM",
            "tableColumnName": "ISSUEUNIT"
        },
        {
            "attributeName": "ITEMNUM3",
            "required": true,
            "persistent": true,
            "title": "Item",
            "remarks": "Identifies the item record. This value must be unique for all item records. Click the Detail Menu button to view items by classification or availability.",
            "sameAsAttribute": "ITEMNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMNUM3",
            "tableName": "ITEM",
            "tableColumnName": "ITEMNUM"
        },
        {
            "attributeName": "SENDERSYSID3",
            "required": false,
            "persistent": true,
            "title": "Sender System ID",
            "remarks": "Column used by ERP-Integration (APIs)",
            "sameAsAttribute": "SENDERSYSID",
            "sameAsObject": "ITEM",
            "viewColumnName": "SENDERSYSID3",
            "tableName": "ITEM",
            "tableColumnName": "SENDERSYSID"
        },
        {
            "attributeName": "SOURCESYSID3",
            "required": false,
            "persistent": true,
            "title": "Source System ID",
            "remarks": "Source System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "SOURCESYSID3",
            "tableName": "ITEM",
            "tableColumnName": "SOURCESYSID"
        },
        {
            "attributeName": "PHYSCNTTOTAL",
            "required": false,
            "persistent": false,
            "title": "Physical Count",
            "remarks": "Quantity of the tool that currently exists in storeroom.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "HARDRESISSUE",
            "required": true,
            "persistent": true,
            "title": "Requires hard reservation on use",
            "remarks": "Indicates whether a hard reservation must be referenced when the item is issued from a storeroom.",
            "sameAsAttribute": "HARDRESISSUE",
            "sameAsObject": "ITEM",
            "viewColumnName": "HARDRESISSUE",
            "tableName": "ITEM",
            "tableColumnName": "HARDRESISSUE"
        },
        {
            "attributeName": "HARDRESISSUE1",
            "required": false,
            "persistent": true,
            "title": "Requires hard reservation on use",
            "remarks": "Specifies when creating a reservation if the reservation can be only a hard reservation.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "HARDRESISSUE1",
            "tableName": "INVENTORY",
            "tableColumnName": "HARDRESISSUE"
        },
        {
            "attributeName": "DFLTSTAGEBIN",
            "required": false,
            "persistent": true,
            "title": "Default Stage Bin",
            "remarks": "The Default Staging bin for this inventory item.",
            "sameAsAttribute": "DFLTSTAGEBIN",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "DFLTSTAGEBIN",
            "tableName": "INVENTORY",
            "tableColumnName": "DFLTSTAGEBIN"
        },
        {
            "attributeName": "RQTYNOTSTAGED",
            "required": false,
            "persistent": false,
            "title": "Hard Reserved Quantity Not Staged",
            "remarks": "The quantity of hard reserved items that are not staged for transfer.",
            "sameAsAttribute": "RQTYNOTSTAGED",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "STAGEDQTY",
            "required": false,
            "persistent": false,
            "title": "Quantity Staged",
            "remarks": "Quantity Staged.",
            "sameAsAttribute": "STAGEDQTY",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "RECEIPTTOLERANCE",
            "required": false,
            "persistent": true,
            "title": "Receipt Tolerance %",
            "remarks": "The percentage value of items that can be received over the amount set in the initial agreement.",
            "sameAsAttribute": "RECEIPTTOLERANCE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "RECEIPTTOLERANCE",
            "tableName": "INVENTORY",
            "tableColumnName": "RECEIPTTOLERANCE"
        },
        {
            "attributeName": "RECEIPTTOLERANCE1",
            "required": false,
            "persistent": true,
            "title": "Receipt Tolerance %",
            "remarks": "The percentage value of items that can be received over the amount set in the initial agreement.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "RECEIPTTOLERANCE1",
            "tableName": "ITEM",
            "tableColumnName": "RECEIPTTOLERANCE"
        },
        {
            "attributeName": "SHIPPEDQTY",
            "required": false,
            "persistent": false,
            "title": "Quantity Shipped",
            "remarks": "The quantity of items that were shipped, including all reservation types.",
            "sameAsAttribute": "SHIPPEDQTY",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "REORDER",
            "required": false,
            "persistent": true,
            "title": "Reorder",
            "remarks": "Specify whether to include the item in the inventory reorder process.",
            "sameAsAttribute": "REORDER",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "REORDER",
            "tableName": "INVENTORY",
            "tableColumnName": "REORDER"
        },
        {
            "attributeName": "COSTTYPE",
            "required": true,
            "persistent": true,
            "title": "Issue Cost Type",
            "remarks": "The issue cost type of an inventory item can be Average, Standard or Asset. You use the Asset cost type for rotating items only.",
            "sameAsAttribute": "COSTTYPE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "COSTTYPE",
            "tableName": "INVENTORY",
            "tableColumnName": "COSTTYPE"
        },
        {
            "attributeName": "UNITCOST",
            "required": false,
            "persistent": false,
            "title": "Unit Cost",
            "remarks": "Identifies the unit cost for the current item.",
            "sameAsAttribute": "STDCOST",
            "sameAsObject": "INVCOST"
        },
        {
            "attributeName": "NEWCOSTTYPE",
            "required": false,
            "persistent": false,
            "title": "New Issue Cost Type",
            "remarks": "The issue cost type of an inventory item can be Average, Standard or Asset. You use the Asset cost type for rotating items only.",
            "sameAsAttribute": "NEWCOSTTYPE",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "DEFCOSTTYPE",
            "required": false,
            "persistent": false,
            "title": "Issue Cost Type",
            "remarks": "The issue cost type of an inventory item can be Average, Standard or Asset. You use the Asset cost type for rotating items only.",
            "sameAsAttribute": "DEFCOSTTYPE",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "REFOBJECT",
            "required": false,
            "persistent": false,
            "title": "Referring Object",
            "remarks": "The object that created the lifo/fifo cost record:  RECEIPT, TRANSFER, RETURN, ADJUSTMENT",
            "sameAsAttribute": "OBJECTNAME",
            "sameAsObject": "MAXOBJECT"
        },
        {
            "attributeName": "REFOBJECTID",
            "required": false,
            "persistent": false,
            "title": "Referring Object ID",
            "remarks": "ID for the related object transaction that created the lifo/fifo cost record",
            "sameAsAttribute": "MAXOBJECTID",
            "sameAsObject": "MAXOBJECT"
        },
        {
            "attributeName": "HARDRESERVEDQTY",
            "required": false,
            "persistent": false,
            "title": "Hard Reserved Quantity",
            "remarks": "The total quantity of items that are currently reserved as HARD or APHARD.",
            "sameAsAttribute": "HARDRESERVEDQTY",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "SOFTRESERVEDQTY",
            "required": false,
            "persistent": false,
            "title": "Soft Reserved Quantity",
            "remarks": "The total quantity of items that are currently reserved as SOFT or APSOFT.",
            "sameAsAttribute": "SOFTRESERVEDQTY",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "COSTDATE",
            "required": false,
            "persistent": false,
            "title": "Cost Date",
            "remarks": "You can specify the receipt date for all cost records in the list.",
            "sameAsAttribute": "COSTDATE",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "LIFOFIFOCOST",
            "required": false,
            "persistent": false,
            "title": "Unit Cost",
            "remarks": "Unit Cost for this item.",
            "sameAsAttribute": "UNITCOST",
            "sameAsObject": "INVLIFOFIFOCOST"
        },
        {
            "attributeName": "CONSIGNMENT",
            "required": true,
            "persistent": true,
            "title": "Consignment",
            "remarks": "Select this check box to identify the item as a consignment type of item.",
            "sameAsAttribute": "CONSIGNMENT",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "CONSIGNMENT",
            "tableName": "INVENTORY",
            "tableColumnName": "CONSIGNMENT"
        },
        {
            "attributeName": "INVGENTYPE",
            "required": false,
            "persistent": true,
            "title": "Invoice Generation Type",
            "remarks": "You can specify how the invoice is generated for the current item. You can specify that invoices are generated based on consumption or on frequency or that they are generated manually.",
            "sameAsAttribute": "INVGENTYPE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "INVGENTYPE",
            "tableName": "INVENTORY",
            "tableColumnName": "INVGENTYPE"
        },
        {
            "attributeName": "FREQUENCY",
            "required": false,
            "persistent": true,
            "title": "Frequency",
            "remarks": "The numeric frequency value of the period to create invoices for the consumption of consignment items.",
            "sameAsAttribute": "FREQUENCY",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "FREQUENCY",
            "tableName": "INVENTORY",
            "tableColumnName": "FREQUENCY"
        },
        {
            "attributeName": "FREQUNIT",
            "required": false,
            "persistent": true,
            "title": "Frequency Units",
            "remarks": "The unit of measure for the frequency value.",
            "sameAsAttribute": "FREQUNIT",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "FREQUNIT",
            "tableName": "INVENTORY",
            "tableColumnName": "FREQUNIT"
        },
        {
            "attributeName": "NEXTINVOICEDATE",
            "required": false,
            "persistent": true,
            "title": "Next Invoice Date",
            "remarks": "The next date that an invoice will be generated if one is needed. When the Frequency and Frequency Units fields are specified, the Next Invoice Date will default based on the current date/time plus the frequency.",
            "sameAsAttribute": "NEXTINVOICEDATE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "NEXTINVOICEDATE",
            "tableName": "INVENTORY",
            "tableColumnName": "NEXTINVOICEDATE"
        },
        {
            "attributeName": "CONSVENDOR",
            "required": false,
            "persistent": true,
            "title": "Consignment Vendor",
            "remarks": "The vendor that is responsible for replenishing the consignment items. Purchase orders and invoices are generated for the vendor that is specified in this field.",
            "sameAsAttribute": "COMPANY",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "CONSVENDOR",
            "tableName": "INVENTORY",
            "tableColumnName": "CONSVENDOR"
        },
        {
            "attributeName": "HARDQTYSHIPPED",
            "required": false,
            "persistent": false,
            "title": "Hard Quantity Shipped",
            "remarks": "The quantity of hard reserved items that were shipped.",
            "sameAsAttribute": "HARDQTYSHIPPED",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "TAXEXEMPT",
            "required": true,
            "persistent": true,
            "title": "Tax Exempt",
            "remarks": "Select this check box if the item, the tool, or the service is not taxable. The buyer for your organization determines the tax-exempt status of items, of tools, and of services.",
            "sameAsAttribute": "TAXEXEMPT",
            "sameAsObject": "ITEM",
            "viewColumnName": "TAXEXEMPT",
            "tableName": "ITEM",
            "tableColumnName": "TAXEXEMPT"
        },
        {
            "attributeName": "PLUSCISINHOUSECAL",
            "required": true,
            "persistent": true,
            "title": "Internal Calibration",
            "remarks": "When selected, indicates that this tool is calibrated in house. This field can be used to sort tools that are calibrated internally or externally.",
            "sameAsAttribute": "PLUSCISINHOUSECAL",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCISINHOUSECAL",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCISINHOUSECAL"
        },
        {
            "attributeName": "PLUSCISMTE",
            "required": true,
            "persistent": true,
            "title": "Is M&TE",
            "remarks": "Defines whether a Tool is a standard used for measuring and testing equipment.",
            "sameAsAttribute": "PLUSCISMTE",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCISMTE",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCISMTE"
        },
        {
            "attributeName": "PLUSCISMTECLASS",
            "required": false,
            "persistent": true,
            "title": "M&TE Classification",
            "remarks": "When the Is M&TE? field is checked then you have the option to choose a classification for M&TE.",
            "sameAsAttribute": "PLUSCISMTECLASS",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCISMTECLASS",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCISMTECLASS"
        },
        {
            "attributeName": "PLUSCSOLUTION",
            "required": true,
            "persistent": true,
            "title": "Buffer Solution",
            "remarks": "Buffer Solution Flag",
            "sameAsAttribute": "PLUSCSOLUTION",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCSOLUTION",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCSOLUTION"
        },
        {
            "attributeName": "SITEID3",
            "required": false,
            "persistent": false,
            "title": "Site",
            "remarks": "SITEID",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE"
        },
        {
            "attributeName": "ITEMTYPE3",
            "required": false,
            "persistent": false,
            "title": "Item Type",
            "remarks": "Item Type",
            "sameAsAttribute": "ITEMTYPE",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "ISCREW",
            "required": true,
            "persistent": true,
            "title": "Crew",
            "remarks": "Specifies whether the tool can be used in Crew applications and Work Order Tracking applications. If the check box is selected, the tool can be used. If the check box is cleared, the tool cannot be used.",
            "sameAsAttribute": "ISCREW",
            "sameAsObject": "ITEM",
            "viewColumnName": "ISCREW",
            "tableName": "ITEM",
            "tableColumnName": "ISCREW"
        },
        {
            "attributeName": "ITEMQTY",
            "required": false,
            "persistent": false,
            "title": "Quantity Requested",
            "remarks": "Number of items you need for the task. If you modify this field, Maximo recalculates the Line Cost field on the Materials subtab, and the Current Estimate Material Cost on the View Costs dialog box. You can edit this field if the work order's status allows work plan material edits. Work order editing rules are set up in the Organizations application.",
            "sameAsAttribute": "ITEMQTY",
            "sameAsObject": "JOBITEM"
        }
    ],
    "viewinfo": {
        "autosect": true,
        "viewwhere": "item.itemsetid=inventory.itemsetid and  inventory.itemnum=item.itemnum and item.itemtype  in (select value from synonymdomain where domainid = 'ITEMTYPE'  and maxvalue = 'TOOL')"
    },
    "outgoingRelationships": [
        {
            "name": "DOCLINKS",
            "target": "DOCLINKS",
            "remarks": null,
            "whereClause": "(ownertable ='TOOLINV' and ownerid = :inventoryid) or (ownertable ='TOOLITEM' and ownerid = (select itemid from toolitem where itemnum=:itemnum and itemsetid=:itemsetid))",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "INVBALANCES",
            "target": "INVBALANCES",
            "remarks": "Stocked Tools Report Object Structure",
            "whereClause": "itemnum=:itemnum and location=:location and siteid=:siteid and itemsetid=:itemsetid",
            "cardinality": "MULTIPLE"
        },
        {
            "name": "TOOLITEM",
            "target": "TOOLITEM",
            "remarks": "Relationship to TOOLITEM",
            "whereClause": "itemnum=:itemnum and itemsetid=:itemsetid",
            "cardinality": null
        }
    ],
    "incomingRelationships": []
}