mos = {
    "objectName": "NETDEVICE",
    "className": "psdi.app.ndasset.NetDeviceSet",
    "description": "Deployed Assets Network Devices",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": true,
    "uniqueId": null,
    "primaryKeyColumns": [
        "NODEID",
        "NODENAME"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "DEPLOYEDASSET",
            "targetObject": "NETDEVICE",
            "parentKeys": "NODEID",
            "targetKeys": "NODEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Deployed Network Device",
            "longDescription": null
        },
        {
            "objectName": "DPAMMANUVARIANT",
            "targetObject": "NETDEVICE",
            "parentKeys": "DPAMMANUVARIANTID",
            "targetKeys": "DPAMMANUVARIANTID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Variant",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "NETDEVICE",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "NETDEVICE",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "NODEID",
            "required": true,
            "persistent": true,
            "title": "Node Id",
            "remarks": "Node Id",
            "sameAsAttribute": "NODEID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "NODEID",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "NODEID"
        },
        {
            "attributeName": "NODEID1",
            "required": true,
            "persistent": true,
            "title": "Node Id",
            "remarks": "Node Id",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "NODEID1",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "NODEID"
        },
        {
            "attributeName": "NETWORKADDRESS",
            "required": false,
            "persistent": true,
            "title": "Network Address",
            "remarks": "Device's network address. This is usually the TCPIP address.",
            "sameAsAttribute": "NETWORKADDRESS",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "NETWORKADDRESS",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "NETWORKADDRESS"
        },
        {
            "attributeName": "NETMACADDR",
            "required": false,
            "persistent": true,
            "title": "MAC Address",
            "remarks": "Primary MAC address for the device. The MAC (Media Access Control) address uniquely identifies each node of a network.",
            "sameAsAttribute": "NETMACADDR",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "NETMACADDR",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "NETMACADDR"
        },
        {
            "attributeName": "FIRMWAREVERSION",
            "required": false,
            "persistent": true,
            "title": "Firmware Version",
            "remarks": "Firmware or BIOS version of the network device. Firmware is software (data or program instructions) stored on integrated circuits in read only memory (ROM).",
            "sameAsAttribute": "FIRMWAREVERSION",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "FIRMWAREVERSION",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "FIRMWAREVERSION"
        },
        {
            "attributeName": "OSVERSION",
            "required": false,
            "persistent": true,
            "title": "Operating System Version",
            "remarks": "Operating system of the network device.",
            "sameAsAttribute": "OSVERSION",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "OSVERSION",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "OSVERSION"
        },
        {
            "attributeName": "RAMSIZE",
            "required": false,
            "persistent": true,
            "title": "RAM Size",
            "remarks": "RAM Size",
            "sameAsAttribute": "RAMSIZE",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "RAMSIZE",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "RAMSIZE"
        },
        {
            "attributeName": "RAMUNIT",
            "required": false,
            "persistent": true,
            "title": "RAM Unit",
            "remarks": "RAM Unit",
            "sameAsAttribute": "RAMUNIT",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "RAMUNIT",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "RAMUNIT"
        },
        {
            "attributeName": "NODENAME",
            "required": true,
            "persistent": true,
            "title": "Device",
            "remarks": "Node Name",
            "sameAsAttribute": "NODENAME",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "NODENAME",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "NODENAME"
        },
        {
            "attributeName": "DOMAINNAME",
            "required": true,
            "persistent": true,
            "title": "Domain",
            "remarks": "Network domain name.",
            "sameAsAttribute": "DOMAINNAME",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "DOMAINNAME",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "DOMAINNAME"
        },
        {
            "attributeName": "SERIALNUMBER",
            "required": false,
            "persistent": true,
            "title": "Serial Number",
            "remarks": "Serial number of the network device.",
            "sameAsAttribute": "SERIALNUMBER",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "SERIALNUMBER",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "SERIALNUMBER"
        },
        {
            "attributeName": "ASSETTAG",
            "required": false,
            "persistent": true,
            "title": "Asset Tag",
            "remarks": "Asset tag of the network device.",
            "sameAsAttribute": "ASSETTAG",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "ASSETTAG",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "ASSETTAG"
        },
        {
            "attributeName": "MAKEMODEL",
            "required": false,
            "persistent": true,
            "title": "Make/Model",
            "remarks": "Make or model (product name) of the network device. Sometimes the make or model field contains the name of the manufacturer of the device.",
            "sameAsAttribute": "MAKEMODEL",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "MAKEMODEL",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "MAKEMODEL"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Describes the network device. This description contains relevant data that is not provided in other fields or that identifies the device in more detail. The data in this field is dependent on the discovery tool used to collect the device information; the field may be empty or may consist of several concatenated pieces of information.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "DEPLOYEDASSET"
        },
        {
            "attributeName": "HWLASTSCANDATE",
            "required": false,
            "persistent": true,
            "title": "Hardware Last Scan Date",
            "remarks": "Last date that the device was scanned for its hardware configuration.",
            "sameAsAttribute": "HWLASTSCANDATE",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "HWLASTSCANDATE",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "HWLASTSCANDATE"
        },
        {
            "attributeName": "HWDETECTIONTOOL",
            "required": false,
            "persistent": true,
            "title": "Hardware Detection Tool",
            "remarks": "Name and version of the software tool used to scan the device for hardware information.",
            "sameAsAttribute": "HWDETECTIONTOOL",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "HWDETECTIONTOOL",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "HWDETECTIONTOOL"
        },
        {
            "attributeName": "SUPPORTSSNMP",
            "required": true,
            "persistent": true,
            "title": "Supports SNMP",
            "remarks": "Specifies whether the SNMP (Simple Network Management Protocol) is enabled on the device. If the check box is selected, the device has SNMP enabled; if the check box is empty, the device does not support SNMP or does not have it enabled. If the information is unknown, the default value is used, and the box is cleared.",
            "sameAsAttribute": "SUPPORTSSNMP",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "SUPPORTSSNMP",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "SUPPORTSSNMP"
        },
        {
            "attributeName": "SOURCEID",
            "required": false,
            "persistent": true,
            "title": "Source",
            "remarks": "Source Id",
            "sameAsAttribute": "SOURCEID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "SOURCEID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "SOURCEID"
        },
        {
            "attributeName": "SYSTEMROLE",
            "required": false,
            "persistent": true,
            "title": "Role",
            "remarks": "Role of the network device. The field usually displays one of the following values: router, switch, or hub.",
            "sameAsAttribute": "SYSTEMROLE",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "SYSTEMROLE",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "SYSTEMROLE"
        },
        {
            "attributeName": "ASSETCLASS",
            "required": true,
            "persistent": true,
            "title": "Asset Class",
            "remarks": "Asset Class",
            "sameAsAttribute": "ASSETCLASS",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "ASSETCLASS",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "ASSETCLASS"
        },
        {
            "attributeName": "SITEID",
            "required": false,
            "persistent": true,
            "title": "Site",
            "remarks": "Site for the network device. An administrator must specify the value for this field when he creates a IBM Tivoli Integration Composer mapping; IBM Tivoli Integration Composer assigns the value to each computer when it executes the mapping.",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE",
            "viewColumnName": "SITEID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "SITEID"
        },
        {
            "attributeName": "ORGID",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Id",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "CREATEDATE",
            "required": true,
            "persistent": true,
            "title": "Created Date",
            "remarks": "Create Date",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CREATEDATE",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "CREATEDATE"
        },
        {
            "attributeName": "CHANGEDATE",
            "required": true,
            "persistent": true,
            "title": "Changed Date",
            "remarks": "Change Date",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CHANGEDATE",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "CHANGEDATE"
        },
        {
            "attributeName": "VRAMSIZE",
            "required": false,
            "persistent": false,
            "title": "RAM Size",
            "remarks": "Size of the RAM (random access memory) on the network device and unit of measurement, either kilobytes (KB), megabytes (MB), or gigabytes (GB).",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CREATEDATE1",
            "required": true,
            "persistent": true,
            "title": "Created Date",
            "remarks": "Create Date",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CREATEDATE1",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "CREATEDATE"
        },
        {
            "attributeName": "CHANGEDATE1",
            "required": true,
            "persistent": true,
            "title": "Changed Date",
            "remarks": "Change Date",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CHANGEDATE1",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "CHANGEDATE"
        },
        {
            "attributeName": "CMANUFACTURER",
            "required": true,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Name of manufacturer of the network device.",
            "sameAsAttribute": "MANUFACTURERNAME",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "CMANUFACTURER",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "MANUFACTURERNAME"
        },
        {
            "attributeName": "MANUFACTURER",
            "required": true,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Manufacturer",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "MANUFACTURER",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "MANUFACTURER"
        },
        {
            "attributeName": "MANUFACTURERVAR",
            "required": true,
            "persistent": true,
            "title": "Manufacturer Variant",
            "remarks": "Manufacturer Var",
            "sameAsAttribute": "MANUFACTURERVAR",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "MANUFACTURERVAR",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "MANUFACTURERVAR"
        },
        {
            "attributeName": "DPAMMANUVARIANTID",
            "required": true,
            "persistent": true,
            "title": "Manufacturer Variant Id",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "DPAMMANUVARIANTID",
            "sameAsObject": "DPAMMANUVARIANT",
            "viewColumnName": "DPAMMANUVARIANTID",
            "tableName": "DPAMMANUVARIANT",
            "tableColumnName": "DPAMMANUVARIANTID"
        },
        {
            "attributeName": "GUID",
            "required": false,
            "persistent": true,
            "title": "GUID",
            "remarks": "Actual CI's GUID",
            "sameAsAttribute": "GUID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "GUID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "GUID"
        },
        {
            "attributeName": "NETSOURCEID1",
            "required": false,
            "persistent": true,
            "title": "Network Source ID",
            "remarks": "Network Source ID",
            "sameAsAttribute": "NETSOURCEID1",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "NETSOURCEID1",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "NETSOURCEID1"
        },
        {
            "attributeName": "DESCRIPTION1",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Description",
            "sameAsAttribute": "DESCRIPTION1",
            "sameAsObject": "DPANETDEVICE",
            "viewColumnName": "DESCRIPTION1",
            "tableName": "DPANETDEVICE",
            "tableColumnName": "DESCRIPTION1"
        },
        {
            "attributeName": "TLOAMISPROMOTED",
            "required": false,
            "persistent": true,
            "title": "Promoted?",
            "remarks": "Indicates whether the Network Device was previously promoted using the promotion process.",
            "sameAsAttribute": "TLOAMISPROMOTED",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMISPROMOTED",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMISPROMOTED"
        },
        {
            "attributeName": "TLOAMNRSGUID",
            "required": false,
            "persistent": true,
            "title": "NRS GUID",
            "remarks": "Naming and Reconciliation Service (NRS) GUID",
            "sameAsAttribute": "TLOAMNRSGUID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSGUID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSGUID"
        },
        {
            "attributeName": "TLOAMNRSSIGNATURE",
            "required": false,
            "persistent": true,
            "title": "NRS Signature",
            "remarks": "The primary IP address, or if there is no IP stack then SNA_HOST",
            "sameAsAttribute": "TLOAMNRSSIGNATURE",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSSIGNATURE",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSSIGNATURE"
        },
        {
            "attributeName": "TLOAMNRSVMID",
            "required": false,
            "persistent": true,
            "title": "NRS VMID",
            "remarks": "The VMID is a unique identifier for the virtual machine",
            "sameAsAttribute": "TLOAMNRSVMID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSVMID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSVMID"
        },
        {
            "attributeName": "TLOAMNRSMANUFACTURER",
            "required": false,
            "persistent": true,
            "title": "NRS Manufacturer",
            "remarks": "Manufacturer",
            "sameAsAttribute": "TLOAMNRSMANUFACTURER",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSMANUFACTURER",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSMANUFACTURER"
        },
        {
            "attributeName": "TLOAMNRSMODEL",
            "required": false,
            "persistent": true,
            "title": "NRS Make/Model",
            "remarks": "Make/Model",
            "sameAsAttribute": "TLOAMNRSMODEL",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSMODEL",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSMODEL"
        },
        {
            "attributeName": "TLOAMNRSSERIALNUMBER",
            "required": false,
            "persistent": true,
            "title": "NRS Serial Number",
            "remarks": "Serial Number",
            "sameAsAttribute": "TLOAMNRSSERIALNUMBER",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSSERIALNUMBER",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSSERIALNUMBER"
        },
        {
            "attributeName": "TLOAMNRSSYSTEMBOARDUUID",
            "required": false,
            "persistent": true,
            "title": "NRS System Board UUID",
            "remarks": "System Board UUID",
            "sameAsAttribute": "TLOAMNRSSYSTEMBOARDUUID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSSYSTEMBOARDUUID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSSYSTEMBOARDUUID"
        },
        {
            "attributeName": "TLOAMNRSPRIMARYMACADDRESS",
            "required": false,
            "persistent": true,
            "title": "NRS MAC Address",
            "remarks": "Primary MAC address",
            "sameAsAttribute": "TLOAMNRSPRIMARYMACADDRESS",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSPRIMARYMACADDRESS",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSPRIMARYMACADDRESS"
        },
        {
            "attributeName": "TLOAMNRSHOSTSYSTEM",
            "required": false,
            "persistent": true,
            "title": "NRS Host System",
            "remarks": "Host System",
            "sameAsAttribute": "TLOAMNRSHOSTSYSTEM",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSHOSTSYSTEM",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSHOSTSYSTEM"
        },
        {
            "attributeName": "TLOAMNRSNAME",
            "required": false,
            "persistent": true,
            "title": "NRS Name",
            "remarks": "Name",
            "sameAsAttribute": "TLOAMNRSNAME",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSNAME",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSNAME"
        },
        {
            "attributeName": "TLOAMNRSMANAGEDSYSTEMNAME",
            "required": false,
            "persistent": true,
            "title": "NRS Managed System Name",
            "remarks": "The name used by the OMEGAMON and IBM Tivoli Monitoring (ITM) products to uniquely identify the agent that manages a specific resource. This agent simultaneously serves as a surrogate for the specific resource under management.",
            "sameAsAttribute": "TLOAMNRSMANAGEDSYSTEMNAME",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSMANAGEDSYSTEMNAME",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSMANAGEDSYSTEMNAME"
        },
        {
            "attributeName": "TLOAMNRSUUID",
            "required": false,
            "persistent": true,
            "title": "NRS Virtual Machine UUID",
            "remarks": "UUID of a virtual machine",
            "sameAsAttribute": "TLOAMNRSUUID",
            "sameAsObject": "DEPLOYEDASSET",
            "viewColumnName": "TLOAMNRSUUID",
            "tableName": "DEPLOYEDASSET",
            "tableColumnName": "TLOAMNRSUUID"
        }
    ],
    "viewinfo": {
        "autosect": false,
        "viewwhere": "dpanetdevice.nodeid=deployedasset.nodeid and deployedasset.manufacturer=dpammanuvariant.manufacturervar",
        "viewselect": "select deployedasset.assetclass, deployedasset.assettag, dpanetdevice.description1 as description1, dpanetdevice.changedate, deployedasset.changedate as changedate1, dpanetdevice.createdate, deployedasset.createdate as createdate1,deployedasset.description, deployedasset.domainname, dpanetdevice.firmwareversion, deployedasset.guid, deployedasset.hwdetectiontool, deployedasset.hwlastscandate,deployedasset.makemodel, deployedasset.manufacturer, dpanetdevice.netmacaddr, dpanetdevice.networkaddress, dpanetdevice.nodeid, deployedasset.nodeid as nodeid1, deployedasset.nodename, deployedasset.orgid, dpanetdevice.osversion, dpanetdevice.ramsize,dpanetdevice.ramunit, dpanetdevice.netsourceid1, dpanetdevice.rowstamp, deployedasset.rowstamp as rowstamp1, deployedasset.serialnumber, deployedasset.siteid,deployedasset.sourceid, deployedasset.supportssnmp, deployedasset.systemrole,dpammanuvariant.manufacturername as cmanufacturer,dpammanuvariant.manufacturervar, dpammanuvariant.dpammanuvariantid,dpammanuvariant.rowstamp as rowstamp2,deployedasset.tloamnrsguid, deployedasset.tloamnrssignature, deployedasset.tloamnrsvmid, deployedasset.tloamnrsmanufacturer, deployedasset.tloamnrsmodel, deployedasset.tloamnrsserialnumber, deployedasset.tloamnrssystemboarduuid, deployedasset.tloamnrsprimarymacaddress, deployedasset.tloamnrshostsystem, deployedasset.tloamnrsname, deployedasset.tloamispromoted, deployedasset.tloamnrsmanagedsystemname,deployedasset.tloamnrsuuid",
        "viewfrom": "from deployedasset, dpanetdevice, dpammanuvariant"
    },
    "outgoingRelationships": [
        {
            "name": "NDASSET_ACTCI",
            "target": "ACTCI",
            "remarks": "Relationship to the ACTCI object, used to find the ACTCI record for the ndasset based on the guid.",
            "whereClause": "guid=:guid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "DDPANETDEVCARD",
            "target": "DPANETDEVCARD",
            "remarks": "delete children",
            "whereClause": "nodeid=:nodeid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "TLOAMRECONRESULT",
            "target": "RECONASSETRESULT",
            "remarks": "Link between NETDEVICE and RECONRESULT",
            "whereClause": "nodeid=:nodeid and code not in ('C3', 'C4','C1','C2') and recontype in (select maxvalue from synonymdomain where domainid = 'RECONTYPE' and maxvalue = 'ASSET') and compset in (select maxvalue from synonymdomain where domainid = 'RECONTYPE' and maxvalue = 'DEPLOYED ASSET')",
            "cardinality": null
        },
        {
            "name": "RECONLINK",
            "target": "RECONLINK",
            "remarks": "delete rerefenced reconciliation link results",
            "whereClause": "nodeid=:nodeid and recontype in (select value from synonymdomain where domainid = 'RECONTYPE' and maxvalue = 'ASSET') and compset in (select value from synonymdomain where domainid = 'RECONTYPE' and maxvalue = 'DEPLOYED ASSET')",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "TLOAMRECONLINK",
            "target": "RECONLINK",
            "remarks": "Link between NETDEVICE and RECONLINK",
            "whereClause": "nodeid=:nodeid and recontype in (select value from synonymdomain where domainid = 'RECONTYPE' and maxvalue = 'ASSET') and compset in (select value from synonymdomain where domainid = 'RECONTYPE' and maxvalue = 'DEPLOYED ASSET')",
            "cardinality": null
        },
        {
            "name": "TLOAMPRMDFLT",
            "target": "TLOAMPRMDFLT",
            "remarks": "network device default",
            "whereClause": "defaultname='DO_NOT_CHANGE_THIS_NDASSET'",
            "cardinality": null
        },
        {
            "name": "TLOAMPRMVALUE",
            "target": "TLOAMPRMVALUE",
            "remarks": "non-persistent relationship",
            "whereClause": "1=1",
            "cardinality": null
        }
    ],
    "incomingRelationships": [
        {
            "name": "NETDEVICE",
            "source": "TLOAMPROMOTE",
            "remarks": "Relationship from Deployed Asset Promotion Records to Network Devices. Returns one and only one record.",
            "whereClause": "nodeid = :nodeid",
            "cardinality": null
        }
    ]
}