mos = {
    "objectName": "SPWORKASSET",
    "className": "psdi.app.safety.SPWorkAssetSet",
    "description": "A work asset which may require the Safety Plan",
    "longDescription": null,
    "isView": false,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": "SPWORKASSETID",
    "primaryKeyColumns": [
        "SITEID",
        "SPWORKASSETID"
    ],
    "logicalRelationships": [
        {
            "objectName": "SPWORKASSET",
            "targetObject": "SPLEXICONLINK",
            "parentKeys": "SITEID, SPWORKASSETID",
            "targetKeys": "SITEID, SPWORKASSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Safety Plan Work Asset",
            "longDescription": null
        }
    ],
    "targetLogicalRelationships": [
        {
            "objectName": "ASSET",
            "targetObject": "SPWORKASSET",
            "parentKeys": "SITEID, ASSETNUM",
            "targetKeys": "SITEID, WORKASSET",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 146",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SPWORKASSET",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "SITEID, WORKLOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Work Location",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SPWORKASSET",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "SAFETYPLAN",
            "targetObject": "SPWORKASSET",
            "parentKeys": "SITEID, SAFETYPLANID",
            "targetKeys": "SITEID, SAFETYPLANID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Safety Plan",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "SPWORKASSET",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "SPWORKASSETID",
            "required": true,
            "persistent": true,
            "title": "SP Work Asset",
            "remarks": "Identifies the Safety Plan's Work Asset. Unique Key Field. Autogenerated",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "SAFETYPLANID",
            "required": true,
            "persistent": true,
            "title": "Safety Plan",
            "remarks": "Identifies the Safety Plan",
            "sameAsAttribute": "SAFETYPLANID",
            "sameAsObject": "SAFETYPLAN"
        },
        {
            "attributeName": "WORKASSET",
            "required": false,
            "persistent": true,
            "title": "Asset",
            "remarks": "Identifies the work asset",
            "sameAsAttribute": "ASSETNUM",
            "sameAsObject": "ASSET"
        },
        {
            "attributeName": "WORKLOCATION",
            "required": false,
            "persistent": true,
            "title": "Location",
            "remarks": "Identifies the work asset as a location",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS"
        },
        {
            "attributeName": "ORGID",
            "required": true,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION"
        },
        {
            "attributeName": "SITEID",
            "required": true,
            "persistent": true,
            "title": "Site",
            "remarks": "Site Identifier",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE"
        },
        {
            "attributeName": "ASSETDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Asset/Location Description",
            "remarks": "ASSETDESCRIPTION",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "ASSETDESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Asset long description",
            "remarks": "The long description of asset",
            "sameAsAttribute": null,
            "sameAsObject": null
        }
    ],
    "outgoingRelationships": [
        {
            "name": "DRILLDOWN",
            "target": "DRILLDOWN",
            "remarks": "Relationship from the SPWORKASSET to the non-persistent DrillDown table. (No where clause). The resulting set will contain zero objects. This relationship is used when the DrillDown page is launched from a location or asset field.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SELECTHAZARD",
            "target": "SAFETYLEXICON",
            "remarks": null,
            "whereClause": "tagoutid is null and siteid =:siteid and  (  (assetnum in (   select relatedasset from sprelatedasset  where (assetnum=:workasset or assetnum is null) and (location=:worklocation or location is null) and siteid=:siteid) ) or (location in ( select relatedlocation from sprelatedasset where (assetnum=:workasset or assetnum is null) and (location=:worklocation or location is null) and siteid=:siteid ) ) or ( ( (assetnum=:workasset )  or   ( location= :worklocation   ) )  and  exists  (select varvalue from maxvars where varname='SHOWWORKASSETHAZ' and varvalue='1' and siteid =:siteid) ) )",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SAFETYPLAN",
            "target": "SAFETYPLAN",
            "remarks": "Relationship to SafetyPlan table. (safetyplan.safetyplanid = spworkasset.safetyplanid). The result set will contain one object.",
            "whereClause": "safetyplanid = :safetyplanid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPLEXICONLINK",
            "target": "SPLEXICONLINK",
            "remarks": "Relationship to SPLexiconLink table. (splexiconlink.spworkassetid = spworkasset.spworkassetid). The result set will contain zero or more objects.",
            "whereClause": "spworkassetid = :spworkassetid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSET",
            "target": "SPRELATEDASSET",
            "remarks": "Relationship to  SPRelatedAsset table. (sprelatedasset.assetnum = spworkasset.workasset or sprelatedasset.location = spworkasset.worklocation). The result set will contain zero or one object.",
            "whereClause": "assetnum = :workasset or location = :worklocation and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWCONTINPUT",
            "target": "VIEWCONTINPUT",
            "remarks": "Relationship to the non-persistent ViewContInput",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWWOPMS",
            "target": "VIEWWOPMS",
            "remarks": "Relationship from the SPWORKASSET to the non-persistent VIEWWOPMS table. (No where clause.) The resulting set will contain zero objects. This relationship is used when the View WO and PM dialog is launched from a location or asset field.  ",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        }
    ],
    "incomingRelationships": [
        {
            "name": "SPWORKASSET",
            "source": "ASSET",
            "remarks": "Relationship to the SPWorkAsset table, used to find all safety plan's work assets for a given asset. (spworkasset.workasset = asset.assetnum). This resulting set will contain zero or more objects.",
            "whereClause": "workasset = :assetnum and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPWORKASSET",
            "source": "LOCATIONS",
            "remarks": "Relationship to the SPWorkAsset table, used to find the safety plan work assets which contain the operating location specified as a work asset. (locations.location =spworkasset.worklocation). The resulting set will contain zero or more objects.",
            "whereClause": "worklocation = :location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPWORKASSET",
            "source": "SAFETYLEXICON",
            "remarks": "Relationship to psdi.app.safety.SPWorkAsset (spworkasset.spworkassetid in (select splexiconlink.spworkassetid from splexiconlink where splexiconlink.safetylexiconid = safetylexicon.safetylexiconid)). This is the middle link in a chain of cross-reference tables leading back to the Safety Plan. The result set will contain zero or more objects.",
            "whereClause": "spworkassetid in (select spworkassetid from splexiconlink where safetylexiconid = :safetylexiconid and siteid=:siteid) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CHILDSPWORKASSET",
            "source": "SAFETYPLAN",
            "remarks": "Relationship to SPWorkAsset. (spworkasset.safetyplanid = safetyplan.safetyplanid and (spworkasset.workasset is not null or spworkasset.worklocation is not null)). Finds the child SPWorkAssets for this SafetyPlan. The result set will contain zero or more objects.",
            "whereClause": "safetyplanid = :safetyplanid and (workasset is not null or worklocation is not null) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "MAINSPWORKASSET",
            "source": "SAFETYPLAN",
            "remarks": "Relationship to SPWorkAsset table. (spworkasset.safetyplanid = safetyplan.safetyplanid and spworkasset.workasset is null and spworkasset.worklocation is null).\tFinds the \"main\" SPWorkAsset record for this SafetyPlan (the record that does not specify an asset or location). The result set will contain one object.",
            "whereClause": "safetyplanid = :safetyplanid and workasset is null and worklocation is null and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPWORKASSET",
            "source": "SAFETYPLAN",
            "remarks": "Relationship to SPWorkAsset table. (spworkasset.safetyplanid = safetyplan.safetyplanid). Finds all SPWorkAsset records for this SafetyPlan. The result set will contain one or more objects.",
            "whereClause": "safetyplanid = :safetyplanid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPWORKASSET",
            "source": "SPLEXICONLINK",
            "remarks": "Relationship to SPWorkAsset table. (spworkasset.spworkassetid = splexiconlink.spworkassetid). The result set will contain one object.",
            "whereClause": "spworkassetid = :spworkassetid and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPWORKASSET",
            "source": "SPRELATEDASSET",
            "remarks": "Relationship to SPWorkAsset table. (spworkasset.workasset = sprelatedasset.assetnum or spworkasset.worklocation = sprelatedasset.location). Finds any SPWorkAsset for the parent asset. The result set will contain zero or more objects.",
            "whereClause": "workasset = :assetnum or worklocation = :location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        }
    ]
}