mos = {
    "objectName": "SPRELATEDASSET",
    "className": "psdi.app.safety.SPRelatedAssetSet",
    "description": "A safety related asset",
    "longDescription": null,
    "isView": false,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": "SPRELATEDASSETID",
    "primaryKeyColumns": [
        "SITEID",
        "SPRELATEDASSETID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "ASSET",
            "targetObject": "SPRELATEDASSET",
            "parentKeys": "SITEID, ASSETNUM",
            "targetKeys": "SITEID, ASSETNUM",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 144",
            "longDescription": null
        },
        {
            "objectName": "ASSET",
            "targetObject": "SPRELATEDASSET",
            "parentKeys": "SITEID, ASSETNUM",
            "targetKeys": "SITEID, RELATEDASSET",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 145",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SPRELATEDASSET",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "SITEID, LOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Location",
            "longDescription": null
        },
        {
            "objectName": "LOCATIONS",
            "targetObject": "SPRELATEDASSET",
            "parentKeys": "SITEID, LOCATION",
            "targetKeys": "SITEID, RELATEDLOCATION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Related Location",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SPRELATEDASSET",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "SITE",
            "targetObject": "SPRELATEDASSET",
            "parentKeys": "SITEID",
            "targetKeys": "SITEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Site for the record",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "SPRELATEDASSETID",
            "required": true,
            "persistent": true,
            "title": "SP Related Asset",
            "remarks": "Identifies the safety related asset of a work asset. Unique Key Field. Autogenerated",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "LOCATION",
            "required": false,
            "persistent": true,
            "title": "Location",
            "remarks": "Identifies the Work Location",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS"
        },
        {
            "attributeName": "ASSETNUM",
            "required": false,
            "persistent": true,
            "title": "Asset",
            "remarks": "Identifies the Work Asset",
            "sameAsAttribute": "ASSETNUM",
            "sameAsObject": "ASSET"
        },
        {
            "attributeName": "RELATEDLOCATION",
            "required": false,
            "persistent": true,
            "title": "Location",
            "remarks": "Identifies the safety related asset Location",
            "sameAsAttribute": "LOCATION",
            "sameAsObject": "LOCATIONS"
        },
        {
            "attributeName": "RELATEDASSET",
            "required": false,
            "persistent": true,
            "title": "Asset",
            "remarks": "Identifies the safety related asset",
            "sameAsAttribute": "ASSETNUM",
            "sameAsObject": "ASSET"
        },
        {
            "attributeName": "ORGID",
            "required": true,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION"
        },
        {
            "attributeName": "SITEID",
            "required": true,
            "persistent": true,
            "title": "Site",
            "remarks": "Site Identifier",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE"
        },
        {
            "attributeName": "WONUM",
            "required": false,
            "persistent": false,
            "title": "Work Order",
            "remarks": "WONUM",
            "sameAsAttribute": "WONUM",
            "sameAsObject": "WORKORDER"
        },
        {
            "attributeName": "RELASSETDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description",
            "remarks": "RELASSETDESCRIPTION",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "RELATEDASSETLOC",
            "required": false,
            "persistent": false,
            "title": "Related asset or Location",
            "remarks": "Related asset or Location",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "RELASSETDESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Details",
            "remarks": "Long description",
            "sameAsAttribute": null,
            "sameAsObject": null
        }
    ],
    "outgoingRelationships": [
        {
            "name": "ASSETCHILD",
            "target": "ASSET",
            "remarks": "Relationship to Asset table. (asset.assetnum = sprelatedasset.relatedasset). Finds the related asset. The result set will contain one object.",
            "whereClause": "assetnum = :relatedasset and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "ASSETPARENT",
            "target": "ASSET",
            "remarks": "Relationship to Asset table. (asset.assetnum = sprelatedasset.assetnum). Finds the parent asset. The result set will contain one object.",
            "whereClause": "assetnum = :assetnum and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "DRILLDOWN",
            "target": "DRILLDOWN",
            "remarks": "Relationship from the SPRELATEDASSET to the non-persistent DrillDown table. (No where clause). The resulting set will contain zero objects. This relationship is used when the DrillDown page is launched from a location or asset field.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SELECTHAZARD",
            "target": "HAZARD",
            "remarks": "Relationship to Hazard table. The Sql is ( hazard.hazardid in (select safetylexicon.hazardid from safetylexicon where safetylexicon.tagoutid is null and  (safetylexicon.assetnum = sprelatedasset.relatedasset or safetylexicon.assetnum is null) and (safetylexicon.location = sprelatedasset.relatedlocation or safetylexicon.location is null) and (not (safetylexicon.assetnum is null and safetylexicon.location is null))) and hazard.hazardid not in (select wohazard.hazardid from wohazard where wohazard.wonum = sprelatedasset.wonum and wohazard.wosafetydatasource = WoSafetyLinkSet.SOURCE_WORKORDER )). Used to find hazards that can be applied to a given work order and related asset. The result set will contain zero or more objects. This relationship makes use of the non-persistent attribute wonum.",
            "whereClause": "hazardid in (select hazardid from safetylexicon where tagoutid is null and (assetnum = :relatedasset or assetnum is null) and    (location = :relatedlocation or location is null) and (not (assetnum is null and location is null)) and siteid=:siteid) and hazardid not in (select hazardid from wohazard where wonum = :wonum and wosafetydatasource = 'WO' and siteid=:siteid) and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "LOCCHILD",
            "target": "LOCATIONS",
            "remarks": "Relationship to Location table. (locations.location = sprelatedasset.relatedlocation). Finds the related location. The result set will contain one object.",
            "whereClause": "location = :relatedlocation and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "LOCPARENT",
            "target": "LOCATIONS",
            "remarks": "Relationship to Location table. (locations.location = sprelatedasset.location). Finds the parent location. The result set will contain one object.",
            "whereClause": "location = :location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SAFETYLEXICON",
            "target": "SAFETYLEXICON",
            "remarks": "Relationship to SafetyLexicon table. (safetylexicon.assetnum = sprelatedasset.relatedasset or safetylexicon.location = sprelatedasset.relatedlocation). Finds any SafetyLexicon for the related asset. The result set will contain zero or more objects.",
            "whereClause": "assetnum = :relatedasset or location = :relatedlocation and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPWORKASSET",
            "target": "SPWORKASSET",
            "remarks": "Relationship to SPWorkAsset table. (spworkasset.workasset = sprelatedasset.assetnum or spworkasset.worklocation = sprelatedasset.location). Finds any SPWorkAsset for the parent asset. The result set will contain zero or more objects.",
            "whereClause": "workasset = :assetnum or worklocation = :location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWCONTINPUT",
            "target": "VIEWCONTINPUT",
            "remarks": "Relationship to the non-persistent ViewContInput",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWWOPMS",
            "target": "VIEWWOPMS",
            "remarks": "Relationship from the SPRELATEDASSET to the non-persistent VIEWWOPMS table. (No where clause.) The resulting set will contain zero objects. This relationship is used when the View Work Details dialog is launched from a location or asset field",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        }
    ],
    "incomingRelationships": [
        {
            "name": "SPRELATEDASSET",
            "source": "ASSET",
            "remarks": "Relationship to the SPRelatedAsset table, used to find all safety related assets of a work asset for a given asset. (sprelatedasset.assetnum = asset.assetnum). This resulting set will contain zero or more objects.",
            "whereClause": "assetnum = :assetnum and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSETRELASSET",
            "source": "ASSET",
            "remarks": "Relationship to the SPRelatedAssetRelAsset table, used to find all safety related assets of a work asset for a related asset. (sprelatedasset.relatedasset = asset.assetnum). This resulting set will contain zero or more objects.",
            "whereClause": "relatedasset = :assetnum and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSETLOC",
            "source": "LOCATIONS",
            "remarks": "Relationship to the SPRelatedAsset table, used to find the work order related assets for a given operating location. (locations.location=sprelatedasset.location). The resulting set will contain zero or more objects.",
            "whereClause": "location=:location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSETRELLOC",
            "source": "LOCATIONS",
            "remarks": "Relationship to the SPRelatedAsset table, used to find the safety related assets for a given operating location. (locations.location=sprelatedasset.relatedlocation).  The resulting set will contain zero or more objects.",
            "whereClause": "relatedlocation=:location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSET",
            "source": "SAFETYLEXICON",
            "remarks": "Relationship to psdi.app.safety.SPRelatedAsset (sprelatedasset.relatedasset = safetylexicon.assetnum or sprelatedasset.relatedlocation = safetylexicon.location). Used to find the asset or location that owns this safetylexicon. The result set will contain zero or more objects.",
            "whereClause": "relatedasset = :assetnum or relatedlocation = :location and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSET",
            "source": "SPWORKASSET",
            "remarks": "Relationship to  SPRelatedAsset table. (sprelatedasset.assetnum = spworkasset.workasset or sprelatedasset.location = spworkasset.worklocation). The result set will contain zero or one object.",
            "whereClause": "assetnum = :workasset or location = :worklocation and siteid=:siteid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SPRELATEDASSET",
            "source": "WORKORDER",
            "remarks": "Relationship to the psdi.app.safety.SPRelatedAsset SPRelatedAsset table, used to get assets that are related to the work order's asset or location.  The identifier of the related asset is relatedasset or relatedlocation. (assetnum = workorder.assetnum or assetnum is null) and (location = workorder.location or location is null). This result set will contain zero or more objects. This is used for the top table window in the Select Hazards dialog.",
            "whereClause": "(assetnum = :assetnum or assetnum is null) and (location = :location or location is null) and siteid=:siteid",
            "cardinality": "UNDEFINED"
        }
    ]
}