mos = {
    "objectName": "SFWVIEW",
    "className": "psdi.app.contract.software.SFWViewSet",
    "description": "Software View",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": true,
    "uniqueId": null,
    "primaryKeyColumns": [
        "CONTRACTNUM",
        "REVISIONNUM",
        "ORGID"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "COMPANIES",
            "targetObject": "SFWVIEW",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID, VENDOR",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Company on Software Contract",
            "longDescription": null
        },
        {
            "objectName": "CONTRACT",
            "targetObject": "SFWVIEW",
            "parentKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "targetKeys": "CONTRACTNUM, MASTERREVNUM, ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Master Contract",
            "longDescription": null
        },
        {
            "objectName": "CONTRACT",
            "targetObject": "SFWVIEW",
            "parentKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "targetKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Contract",
            "longDescription": null
        },
        {
            "objectName": "CONTRACTSFW",
            "targetObject": "SFWVIEW",
            "parentKeys": "CONTRACTSFWID",
            "targetKeys": "CONTRACTSFWID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Software Contracts",
            "longDescription": null
        },
        {
            "objectName": "CURRENCY",
            "targetObject": "SFWVIEW",
            "parentKeys": "CURRENCYCODE",
            "targetKeys": "CURRENCYCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Record Currency",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "SFWVIEW",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Language for the record",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SFWVIEW",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "SFWVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "CHANGEBY",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Person who last changed the record.",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "SFWVIEW",
            "parentKeys": "PERSONID",
            "targetKeys": "PURCHASEAGENT",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Purchase Agent",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "CONTRACTNUM",
            "required": true,
            "persistent": true,
            "title": "Contract",
            "remarks": "The unique identification number of an associated contract on a Master Contract.",
            "sameAsAttribute": "CONTRACTNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTNUM",
            "tableName": "CONTRACT",
            "tableColumnName": "CONTRACTNUM"
        },
        {
            "attributeName": "CONTRACTNUM1",
            "required": true,
            "persistent": true,
            "title": "ContractNum",
            "remarks": "Contractnum field from CONTRACT table",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CONTRACTNUM1",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CONTRACTNUM"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Description of the current contract.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "PR",
            "viewColumnName": "DESCRIPTION",
            "tableName": "CONTRACT",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "MASTERNUM",
            "required": false,
            "persistent": true,
            "title": "Master Contract",
            "remarks": "Master Contract Number.",
            "sameAsAttribute": "MASTERNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "MASTERNUM",
            "tableName": "CONTRACT",
            "tableColumnName": "MASTERNUM"
        },
        {
            "attributeName": "VENDORREFNUM",
            "required": false,
            "persistent": true,
            "title": "Vendor Reference",
            "remarks": "Vendor reference number.",
            "sameAsAttribute": "VENDORREFNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "VENDORREFNUM",
            "tableName": "CONTRACT",
            "tableColumnName": "VENDORREFNUM"
        },
        {
            "attributeName": "CONTRACTTYPE",
            "required": true,
            "persistent": true,
            "title": "Contract Type",
            "remarks": "Indicator of the current contract type.",
            "sameAsAttribute": "CONTRACTTYPE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTTYPE",
            "tableName": "CONTRACT",
            "tableColumnName": "CONTRACTTYPE"
        },
        {
            "attributeName": "REVISIONNUM",
            "required": true,
            "persistent": true,
            "title": "Revision",
            "remarks": "Revision number of the associated contract. This number indicates the number of times the associated contract has been revised. An associated contract that has been created and not revised will show a number of 0.",
            "sameAsAttribute": "REVISIONNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "REVISIONNUM",
            "tableName": "CONTRACT",
            "tableColumnName": "REVISIONNUM"
        },
        {
            "attributeName": "REVISIONNUM1",
            "required": true,
            "persistent": true,
            "title": "Revision",
            "remarks": "Revision number of the contract. This number indicates the number of times a contract has been revised. A contract that has been created and not revised will show a number of 0.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "REVISIONNUM1",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "REVISIONNUM"
        },
        {
            "attributeName": "PURCHASEAGENT",
            "required": false,
            "persistent": true,
            "title": "Buyer",
            "remarks": "Buyer",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "PURCHASEAGENT",
            "tableName": "CONTRACT",
            "tableColumnName": "PURCHASEAGENT"
        },
        {
            "attributeName": "STATUS",
            "required": true,
            "persistent": true,
            "title": "Status",
            "remarks": "Current status of this contract.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "STATUS",
            "tableName": "CONTRACT",
            "tableColumnName": "STATUS"
        },
        {
            "attributeName": "STATUSDATE",
            "required": false,
            "persistent": true,
            "title": "Status Date",
            "remarks": "Status date.",
            "sameAsAttribute": "STATUSDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "STATUSDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "STATUSDATE"
        },
        {
            "attributeName": "STARTDATE",
            "required": false,
            "persistent": true,
            "title": "Start Date",
            "remarks": "Date when a PO becomes an active contract.",
            "sameAsAttribute": "STARTDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "STARTDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "STARTDATE"
        },
        {
            "attributeName": "ENDDATE",
            "required": false,
            "persistent": true,
            "title": "End Date",
            "remarks": "Date after which the contract is no longer valid.",
            "sameAsAttribute": "ENDDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "ENDDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "ENDDATE"
        },
        {
            "attributeName": "ENDDATE1",
            "required": false,
            "persistent": true,
            "title": "End Date",
            "remarks": "End Date",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "ENDDATE1",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ENDDATE"
        },
        {
            "attributeName": "RENEWALDATE",
            "required": false,
            "persistent": true,
            "title": "Renewal Date",
            "remarks": "Date that the contract can be renewed.",
            "sameAsAttribute": "RENEWALDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "RENEWALDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "RENEWALDATE"
        },
        {
            "attributeName": "EXTENDABLE",
            "required": true,
            "persistent": true,
            "title": "Extendable",
            "remarks": "Is the contract extendable.",
            "sameAsAttribute": "EXTENDABLE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "EXTENDABLE",
            "tableName": "CONTRACT",
            "tableColumnName": "EXTENDABLE"
        },
        {
            "attributeName": "AUTOEXTENDPERIOD",
            "required": false,
            "persistent": true,
            "title": "Automatically Extend Period",
            "remarks": "Auto extend period in days.",
            "sameAsAttribute": "AUTOEXTENDPERIOD",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "AUTOEXTENDPERIOD",
            "tableName": "CONTRACT",
            "tableColumnName": "AUTOEXTENDPERIOD"
        },
        {
            "attributeName": "CONDFOREXT",
            "required": false,
            "persistent": true,
            "title": "Condition for Extension",
            "remarks": "Condition for extension.",
            "sameAsAttribute": "CONDFOREXT",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONDFOREXT",
            "tableName": "CONTRACT",
            "tableColumnName": "CONDFOREXT"
        },
        {
            "attributeName": "CUSTTERMALLOWED",
            "required": true,
            "persistent": true,
            "title": "Customer Termination Allowed",
            "remarks": "Checking this box indicates that early termination by the customer is allowed.",
            "sameAsAttribute": "CUSTTERMALLOWED",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CUSTTERMALLOWED",
            "tableName": "CONTRACT",
            "tableColumnName": "CUSTTERMALLOWED"
        },
        {
            "attributeName": "CUSTNOTIFYPERIOD",
            "required": false,
            "persistent": true,
            "title": "Customer Notify Period",
            "remarks": "Customer notification period in days.",
            "sameAsAttribute": "CUSTNOTIFYPERIOD",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CUSTNOTIFYPERIOD",
            "tableName": "CONTRACT",
            "tableColumnName": "CUSTNOTIFYPERIOD"
        },
        {
            "attributeName": "VENDTERMALLOWED",
            "required": true,
            "persistent": true,
            "title": "Vendor Term Allowed",
            "remarks": "Early termination allowed by vendor.",
            "sameAsAttribute": "VENDTERMALLOWED",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "VENDTERMALLOWED",
            "tableName": "CONTRACT",
            "tableColumnName": "VENDTERMALLOWED"
        },
        {
            "attributeName": "VENDNOTIFYPERIOD",
            "required": false,
            "persistent": true,
            "title": "Vendor Notify Period",
            "remarks": "If early termination is allowed by vendor, this indicates the notice of termination in days.",
            "sameAsAttribute": "VENDNOTIFYPERIOD",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "VENDNOTIFYPERIOD",
            "tableName": "CONTRACT",
            "tableColumnName": "VENDNOTIFYPERIOD"
        },
        {
            "attributeName": "VENDOR",
            "required": false,
            "persistent": true,
            "title": "Vendor",
            "remarks": "Vendor code",
            "sameAsAttribute": "COMPANY",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "VENDOR",
            "tableName": "CONTRACT",
            "tableColumnName": "VENDOR"
        },
        {
            "attributeName": "CONTACT",
            "required": false,
            "persistent": true,
            "title": "Contact",
            "remarks": "Vendor contact name.",
            "sameAsAttribute": "CONTACT",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "CONTACT",
            "tableName": "CONTRACT",
            "tableColumnName": "CONTACT"
        },
        {
            "attributeName": "FREIGHTTERMS",
            "required": false,
            "persistent": true,
            "title": "Freight Terms",
            "remarks": "Freight Terms.",
            "sameAsAttribute": "FREIGHTTERMS",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "FREIGHTTERMS",
            "tableName": "CONTRACT",
            "tableColumnName": "FREIGHTTERMS"
        },
        {
            "attributeName": "PAYMENTTERMS",
            "required": false,
            "persistent": true,
            "title": "Payment Terms",
            "remarks": "Payment terms.",
            "sameAsAttribute": "PAYMENTTERMS",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "PAYMENTTERMS",
            "tableName": "CONTRACT",
            "tableColumnName": "PAYMENTTERMS"
        },
        {
            "attributeName": "SHIPVIA",
            "required": false,
            "persistent": true,
            "title": "Ship Via",
            "remarks": "Ship via.",
            "sameAsAttribute": "SHIPVIA",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "SHIPVIA",
            "tableName": "CONTRACT",
            "tableColumnName": "SHIPVIA"
        },
        {
            "attributeName": "CUSTOMERNUM",
            "required": false,
            "persistent": true,
            "title": "Customer #",
            "remarks": "Vendors Number Identifying Our Company.",
            "sameAsAttribute": "CUSTOMERNUM",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "CUSTOMERNUM",
            "tableName": "CONTRACT",
            "tableColumnName": "CUSTOMERNUM"
        },
        {
            "attributeName": "FOB",
            "required": false,
            "persistent": true,
            "title": "Freight on Board",
            "remarks": "Freight on board.",
            "sameAsAttribute": "FOB",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "FOB",
            "tableName": "CONTRACT",
            "tableColumnName": "FOB"
        },
        {
            "attributeName": "TOTALCOST",
            "required": false,
            "persistent": true,
            "title": "Total Cost",
            "remarks": "The sum of all the costs on the contract lines added together of the current associated contract.",
            "sameAsAttribute": "TOTALCOST",
            "sameAsObject": "PO",
            "viewColumnName": "TOTALCOST",
            "tableName": "CONTRACT",
            "tableColumnName": "TOTALCOST"
        },
        {
            "attributeName": "CHANGEBY",
            "required": false,
            "persistent": true,
            "title": "Changed By",
            "remarks": "Last Modified By.",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "CHANGEBY",
            "tableName": "CONTRACT",
            "tableColumnName": "CHANGEBY"
        },
        {
            "attributeName": "CHANGEDATE",
            "required": true,
            "persistent": true,
            "title": "Changed Date",
            "remarks": "Last modified date.",
            "sameAsAttribute": "CHANGEDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CHANGEDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "CHANGEDATE"
        },
        {
            "attributeName": "HISTORYFLAG",
            "required": true,
            "persistent": true,
            "title": "History",
            "remarks": "History flag.",
            "sameAsAttribute": "HISTORYFLAG",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "HISTORYFLAG",
            "tableName": "CONTRACT",
            "tableColumnName": "HISTORYFLAG"
        },
        {
            "attributeName": "CURRENCYCODE",
            "required": true,
            "persistent": true,
            "title": "Currency",
            "remarks": "Currency code the Contract is in.",
            "sameAsAttribute": "CURRENCYCODE",
            "sameAsObject": "CURRENCY",
            "viewColumnName": "CURRENCYCODE",
            "tableName": "CONTRACT",
            "tableColumnName": "CURRENCYCODE"
        },
        {
            "attributeName": "EXCHANGERATE",
            "required": false,
            "persistent": true,
            "title": "Exchange Rate",
            "remarks": "Exchange rate the time of contract approval.",
            "sameAsAttribute": "EXCHANGERATE",
            "sameAsObject": "EXCHANGE",
            "viewColumnName": "EXCHANGERATE",
            "tableName": "CONTRACT",
            "tableColumnName": "EXCHANGERATE"
        },
        {
            "attributeName": "EXCHANGERATE2",
            "required": false,
            "persistent": true,
            "title": "Exchange Rate2",
            "remarks": "Exchange rate2 at the time of contract approval.",
            "sameAsAttribute": "EXCHANGERATE",
            "sameAsObject": "EXCHANGE",
            "viewColumnName": "EXCHANGERATE2",
            "tableName": "CONTRACT",
            "tableColumnName": "EXCHANGERATE2"
        },
        {
            "attributeName": "EXCHANGEDATE",
            "required": false,
            "persistent": true,
            "title": "ExDate Changed",
            "remarks": "Date of the exchange rate.",
            "sameAsAttribute": "EXCHANGEDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "EXCHANGEDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "EXCHANGEDATE"
        },
        {
            "attributeName": "BUYAHEAD",
            "required": true,
            "persistent": true,
            "title": "Buy Ahead",
            "remarks": "Is this a buy ahead rate, ie entered directly by the user and not calculated from the list of active exchange rate.",
            "sameAsAttribute": "BUYAHEAD",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "BUYAHEAD",
            "tableName": "CONTRACT",
            "tableColumnName": "BUYAHEAD"
        },
        {
            "attributeName": "INCLUSIVE1",
            "required": true,
            "persistent": true,
            "title": "Include Tax 1",
            "remarks": "Is the PO total inclusive of Tax 1",
            "sameAsAttribute": "INCLUSIVE1",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "INCLUSIVE1",
            "tableName": "CONTRACT",
            "tableColumnName": "INCLUSIVE1"
        },
        {
            "attributeName": "INCLUSIVE2",
            "required": true,
            "persistent": true,
            "title": "Include Tax 2",
            "remarks": "Is the PO total inclusive of Tax 2.",
            "sameAsAttribute": "INCLUSIVE2",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "INCLUSIVE2",
            "tableName": "CONTRACT",
            "tableColumnName": "INCLUSIVE2"
        },
        {
            "attributeName": "INCLUSIVE3",
            "required": true,
            "persistent": true,
            "title": "Include Tax 3",
            "remarks": "Is the PO total inclusive of Tax 3.",
            "sameAsAttribute": "INCLUSIVE3",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "INCLUSIVE3",
            "tableName": "CONTRACT",
            "tableColumnName": "INCLUSIVE3"
        },
        {
            "attributeName": "INCLUSIVE4",
            "required": true,
            "persistent": true,
            "title": "Include Tax 4",
            "remarks": "Is the PO total inclusive of Tax 4.",
            "sameAsAttribute": "INCLUSIVE4",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "INCLUSIVE4",
            "tableName": "CONTRACT",
            "tableColumnName": "INCLUSIVE4"
        },
        {
            "attributeName": "INCLUSIVE5",
            "required": true,
            "persistent": true,
            "title": "Include Tax 5",
            "remarks": "Is the PO total inclusive of Tax 5.",
            "sameAsAttribute": "INCLUSIVE5",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "INCLUSIVE5",
            "tableName": "CONTRACT",
            "tableColumnName": "INCLUSIVE5"
        },
        {
            "attributeName": "EXTERNALREFID",
            "required": false,
            "persistent": true,
            "title": "External Reference ID",
            "remarks": "External Reference ID.",
            "sameAsAttribute": "EXTERNALREFID",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "EXTERNALREFID",
            "tableName": "CONTRACT",
            "tableColumnName": "EXTERNALREFID"
        },
        {
            "attributeName": "OWNERSYSID",
            "required": false,
            "persistent": true,
            "title": "Owner System ID",
            "remarks": "Owner system ID.",
            "sameAsAttribute": "OWNERSYSID",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "OWNERSYSID",
            "tableName": "CONTRACT",
            "tableColumnName": "OWNERSYSID"
        },
        {
            "attributeName": "SENDERSYSID",
            "required": false,
            "persistent": true,
            "title": "Sender System ID",
            "remarks": "Column used by ERP-Integration (MEA).",
            "sameAsAttribute": "SENDERSYSID",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "SENDERSYSID",
            "tableName": "CONTRACT",
            "tableColumnName": "SENDERSYSID"
        },
        {
            "attributeName": "ORGID",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization identifier.",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "CONTRACT",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "ORGID1",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID1",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "TOTALBASECOST",
            "required": true,
            "persistent": true,
            "title": "Total Base Cost",
            "remarks": "Cost of the entire contract in base currency 1.",
            "sameAsAttribute": "TOTALBASECOST",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "TOTALBASECOST",
            "tableName": "CONTRACT",
            "tableColumnName": "TOTALBASECOST"
        },
        {
            "attributeName": "POREQUIRED",
            "required": true,
            "persistent": true,
            "title": "PO Required",
            "remarks": "Will a PO be required for this contract?",
            "sameAsAttribute": "POREQUIRED",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "POREQUIRED",
            "tableName": "CONTRACT",
            "tableColumnName": "POREQUIRED"
        },
        {
            "attributeName": "PAYMENTSCHED",
            "required": true,
            "persistent": true,
            "title": "Payment Schedule",
            "remarks": "Is there a payment schedule for this contract?",
            "sameAsAttribute": "PAYMENTSCHED",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "PAYMENTSCHED",
            "tableName": "CONTRACT",
            "tableColumnName": "PAYMENTSCHED"
        },
        {
            "attributeName": "HASINSURANCE",
            "required": true,
            "persistent": true,
            "title": "Has Insurance",
            "remarks": "Does this vendor have a current insurance policy ?",
            "sameAsAttribute": "HASINSURANCE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "HASINSURANCE",
            "tableName": "CONTRACT",
            "tableColumnName": "HASINSURANCE"
        },
        {
            "attributeName": "INSURANCEEXPDATE",
            "required": false,
            "persistent": true,
            "title": "Insurance Expiration Date",
            "remarks": "Expiration date of the vendors insurance policy.",
            "sameAsAttribute": "INSURANCEEXPDATE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "INSURANCEEXPDATE",
            "tableName": "CONTRACT",
            "tableColumnName": "INSURANCEEXPDATE"
        },
        {
            "attributeName": "CONTRACTID",
            "required": true,
            "persistent": true,
            "title": "CONTRACTID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "CONTRACTID",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTID",
            "tableName": "CONTRACT",
            "tableColumnName": "CONTRACTID"
        },
        {
            "attributeName": "REVCOMMENTS",
            "required": false,
            "persistent": true,
            "title": "Revision Comments",
            "remarks": "Revision Comments.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "PR",
            "viewColumnName": "REVCOMMENTS",
            "tableName": "CONTRACT",
            "tableColumnName": "REVCOMMENTS"
        },
        {
            "attributeName": "LANGCODE",
            "required": true,
            "persistent": true,
            "title": "Language Code",
            "remarks": "Language Column",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGCODE",
            "tableName": "CONTRACT",
            "tableColumnName": "LANGCODE"
        },
        {
            "attributeName": "MASTERREVNUM",
            "required": false,
            "persistent": true,
            "title": "Master Revision",
            "remarks": "Master Contract Revision Number",
            "sameAsAttribute": "REVISIONNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "MASTERREVNUM",
            "tableName": "CONTRACT",
            "tableColumnName": "MASTERREVNUM"
        },
        {
            "attributeName": "PROCESSCLAIM",
            "required": true,
            "persistent": true,
            "title": "PROCESS CLAIM",
            "remarks": "Can a claim be processed against this contract",
            "sameAsAttribute": "PROCESSCLAIM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "PROCESSCLAIM",
            "tableName": "CONTRACT",
            "tableColumnName": "PROCESSCLAIM"
        },
        {
            "attributeName": "INSPECTIONREQUIRED",
            "required": true,
            "persistent": true,
            "title": "Inspection Required",
            "remarks": "Whether items ordered from this company need to be inspected on receipt.",
            "sameAsAttribute": "INSPECTIONREQUIRED",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "INSPECTIONREQUIRED",
            "tableName": "CONTRACT",
            "tableColumnName": "INSPECTIONREQUIRED"
        },
        {
            "attributeName": "HASLD",
            "required": true,
            "persistent": true,
            "title": "Has Long Description",
            "remarks": "Boolean flag to indicate if there is any long description for this record",
            "sameAsAttribute": "HASLD",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "HASLD",
            "tableName": "CONTRACT",
            "tableColumnName": "HASLD"
        },
        {
            "attributeName": "STATUSIFACE",
            "required": true,
            "persistent": false,
            "title": "Has Status Changed",
            "remarks": "Non persistent boolean field to indicate whether the status has been changed after the stateful object is fetched from the database.",
            "sameAsAttribute": "STATUSIFACE",
            "sameAsObject": "CONTRACT"
        },
        {
            "attributeName": "CONTRACTSFWID",
            "required": true,
            "persistent": true,
            "title": "Unique Id",
            "remarks": "Unique Id",
            "sameAsAttribute": "CONTRACTSFWID",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CONTRACTSFWID",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CONTRACTSFWID"
        },
        {
            "attributeName": "ADDLINESONUSE",
            "required": true,
            "persistent": true,
            "title": "Adds Lines On Use",
            "remarks": "Can additional lines be added to software document with contract reference",
            "sameAsAttribute": "ADDLINESONUSE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ADDLINESONUSE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ADDLINESONUSE"
        },
        {
            "attributeName": "CHGPRICEONUSE",
            "required": true,
            "persistent": true,
            "title": "Change Price On Use",
            "remarks": "Can price be changed on the line with contract reference",
            "sameAsAttribute": "CHGPRICEONUSE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CHGPRICEONUSE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CHGPRICEONUSE"
        },
        {
            "attributeName": "CHGQTYONUSE",
            "required": true,
            "persistent": true,
            "title": "Change Quantity On Use",
            "remarks": "Can quantity be changed on line with contract reference",
            "sameAsAttribute": "CHGQTYONUSE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CHGQTYONUSE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CHGQTYONUSE"
        },
        {
            "attributeName": "MAXVOL",
            "required": false,
            "persistent": true,
            "title": "Maximium Amount",
            "remarks": "Maximum Amount",
            "sameAsAttribute": "MAXVOL",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "MAXVOL",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "MAXVOL"
        },
        {
            "attributeName": "MAXRELVOL",
            "required": false,
            "persistent": true,
            "title": "Maximum Release Amount",
            "remarks": "Maximum Release Amount",
            "sameAsAttribute": "MAXRELVOL",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "MAXRELVOL",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "MAXRELVOL"
        },
        {
            "attributeName": "SHIPPINGLOSS",
            "required": true,
            "persistent": true,
            "title": "Shipping Loss",
            "remarks": "Liable for shipping loss?",
            "sameAsAttribute": "SHIPPINGLOSS",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SHIPPINGLOSS",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SHIPPINGLOSS"
        },
        {
            "attributeName": "DELIVERYLOSS",
            "required": true,
            "persistent": true,
            "title": "Delivery Loss",
            "remarks": "Liable for delivery loss?",
            "sameAsAttribute": "DELIVERYLOSS",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "DELIVERYLOSS",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "DELIVERYLOSS"
        },
        {
            "attributeName": "ACCEPTANCELOSS",
            "required": true,
            "persistent": true,
            "title": "Acceptance Loss",
            "remarks": "Liable for acceptance loss?",
            "sameAsAttribute": "ACCEPTANCELOSS",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ACCEPTANCELOSS",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ACCEPTANCELOSS"
        },
        {
            "attributeName": "SFWLICTYPE",
            "required": false,
            "persistent": true,
            "title": "License Type",
            "remarks": "Software License Type",
            "sameAsAttribute": "SFWLICTYPE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SFWLICTYPE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SFWLICTYPE"
        },
        {
            "attributeName": "FULLYLIC",
            "required": true,
            "persistent": true,
            "title": "License Status",
            "remarks": "Current license status of this contract.",
            "sameAsAttribute": "FULLYLIC",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "FULLYLIC",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "FULLYLIC"
        },
        {
            "attributeName": "WEBSUPPORT",
            "required": true,
            "persistent": true,
            "title": "Web Support",
            "remarks": "Web Support",
            "sameAsAttribute": "WEBSUPPORT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "WEBSUPPORT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "WEBSUPPORT"
        },
        {
            "attributeName": "GENCOVERAGE",
            "required": false,
            "persistent": true,
            "title": "General Coverage",
            "remarks": "General Coverage",
            "sameAsAttribute": "GENCOVERAGE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "GENCOVERAGE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "GENCOVERAGE"
        },
        {
            "attributeName": "PRODCOVERAGE",
            "required": false,
            "persistent": true,
            "title": "Production Coverage",
            "remarks": "Production Coverage",
            "sameAsAttribute": "PRODCOVERAGE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "PRODCOVERAGE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "PRODCOVERAGE"
        },
        {
            "attributeName": "VERSUPPORT",
            "required": false,
            "persistent": true,
            "title": "Version Support",
            "remarks": "Version Support",
            "sameAsAttribute": "VERSUPPORT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "VERSUPPORT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "VERSUPPORT"
        },
        {
            "attributeName": "SUPPTEAM",
            "required": false,
            "persistent": true,
            "title": "Support Team",
            "remarks": "Support Team",
            "sameAsAttribute": "SUPPTEAM",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SUPPTEAM",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SUPPTEAM"
        },
        {
            "attributeName": "DEDICSUPPTEAM",
            "required": true,
            "persistent": true,
            "title": "Dedicated Support Team",
            "remarks": "Dedicated Support Team",
            "sameAsAttribute": "DEDICSUPPTEAM",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "DEDICSUPPTEAM",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "DEDICSUPPTEAM"
        },
        {
            "attributeName": "SERVCOVERAGE",
            "required": false,
            "persistent": true,
            "title": "Service Coverage",
            "remarks": "Service Coverage",
            "sameAsAttribute": "SERVCOVERAGE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SERVCOVERAGE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SERVCOVERAGE"
        },
        {
            "attributeName": "SUPPLEVELS",
            "required": false,
            "persistent": true,
            "title": "Support Levels",
            "remarks": "Support Levels",
            "sameAsAttribute": "SUPPLEVELS",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SUPPLEVELS",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SUPPLEVELS"
        },
        {
            "attributeName": "SUPPSITES",
            "required": false,
            "persistent": true,
            "title": "Support Sites",
            "remarks": "Support Sites",
            "sameAsAttribute": "SUPPSITES",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SUPPSITES",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SUPPSITES"
        },
        {
            "attributeName": "SUPPSERVERS",
            "required": false,
            "persistent": true,
            "title": "Support Servers",
            "remarks": "Support Servers",
            "sameAsAttribute": "SUPPSERVERS",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "SUPPSERVERS",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "SUPPSERVERS"
        },
        {
            "attributeName": "REINSTATDATE",
            "required": false,
            "persistent": true,
            "title": "Reinstatement Date",
            "remarks": "Reinstatement Date",
            "sameAsAttribute": "REINSTATDATE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "REINSTATDATE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "REINSTATDATE"
        },
        {
            "attributeName": "CANCELNOTICE",
            "required": false,
            "persistent": true,
            "title": "Cancellation Notice",
            "remarks": "Cancellation Notice",
            "sameAsAttribute": "CANCELNOTICE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CANCELNOTICE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CANCELNOTICE"
        },
        {
            "attributeName": "CAPRATIO",
            "required": false,
            "persistent": true,
            "title": "Cap (%)",
            "remarks": "Cap (%)",
            "sameAsAttribute": "CAPRATIO",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CAPRATIO",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CAPRATIO"
        },
        {
            "attributeName": "ADDSERVCOST",
            "required": false,
            "persistent": true,
            "title": "Additional Server Cost",
            "remarks": "Additional Server Cost",
            "sameAsAttribute": "ADDSERVCOST",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ADDSERVCOST",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ADDSERVCOST"
        },
        {
            "attributeName": "ADDSITECOST",
            "required": false,
            "persistent": true,
            "title": "Additional Site Cost",
            "remarks": "Additional Site Cost",
            "sameAsAttribute": "ADDSITECOST",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ADDSITECOST",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ADDSITECOST"
        },
        {
            "attributeName": "UPDATES",
            "required": true,
            "persistent": true,
            "title": "Updates",
            "remarks": "Updates",
            "sameAsAttribute": "UPDATES",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "UPDATES",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "UPDATES"
        },
        {
            "attributeName": "NEWVERSION",
            "required": true,
            "persistent": true,
            "title": "New Versions",
            "remarks": "New Versions",
            "sameAsAttribute": "NEWVERSION",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "NEWVERSION",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "NEWVERSION"
        },
        {
            "attributeName": "NEWRELEASE",
            "required": true,
            "persistent": true,
            "title": "New Release",
            "remarks": "New release",
            "sameAsAttribute": "NEWRELEASE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "NEWRELEASE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "NEWRELEASE"
        },
        {
            "attributeName": "FIXES",
            "required": true,
            "persistent": true,
            "title": "Fixes",
            "remarks": "Fixes",
            "sameAsAttribute": "FIXES",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "FIXES",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "FIXES"
        },
        {
            "attributeName": "ENHANCEMENT",
            "required": true,
            "persistent": true,
            "title": "Enhancements",
            "remarks": "Enhancements",
            "sameAsAttribute": "ENHANCEMENT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ENHANCEMENT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ENHANCEMENT"
        },
        {
            "attributeName": "MAINTFEE",
            "required": false,
            "persistent": true,
            "title": "Maintenance Fee",
            "remarks": "Maintenance Fee",
            "sameAsAttribute": "MAINTFEE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "MAINTFEE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "MAINTFEE"
        },
        {
            "attributeName": "MAINT",
            "required": true,
            "persistent": true,
            "title": "Maintenance",
            "remarks": "Includes maintenance?",
            "sameAsAttribute": "MAINT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "MAINT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "MAINT"
        },
        {
            "attributeName": "PORTABILITY",
            "required": true,
            "persistent": true,
            "title": "Portability",
            "remarks": "Portability",
            "sameAsAttribute": "PORTABILITY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "PORTABILITY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "PORTABILITY"
        },
        {
            "attributeName": "LATEPMTPENALTY",
            "required": false,
            "persistent": true,
            "title": "Late Payment Penalty",
            "remarks": "Late payment penalty",
            "sameAsAttribute": "LATEPMTPENALTY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "LATEPMTPENALTY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "LATEPMTPENALTY"
        },
        {
            "attributeName": "DISASTERRECOV",
            "required": true,
            "persistent": true,
            "title": "Disaster Recovery",
            "remarks": "Disaster Recovery",
            "sameAsAttribute": "DISASTERRECOV",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "DISASTERRECOV",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "DISASTERRECOV"
        },
        {
            "attributeName": "DIVESTRIGHT",
            "required": true,
            "persistent": true,
            "title": "Divestiture Rights",
            "remarks": "Divestiture Rights",
            "sameAsAttribute": "DIVESTRIGHT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "DIVESTRIGHT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "DIVESTRIGHT"
        },
        {
            "attributeName": "DIVPERIOD",
            "required": false,
            "persistent": true,
            "title": "Divestiture Period",
            "remarks": "Divestiture Period",
            "sameAsAttribute": "DIVPERIOD",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "DIVPERIOD",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "DIVPERIOD"
        },
        {
            "attributeName": "ADDPRODDISCOUNT",
            "required": false,
            "persistent": true,
            "title": "Additional Product Discounts (%)",
            "remarks": "Additional product discounts (%)",
            "sameAsAttribute": "ADDPRODDISCOUNT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ADDPRODDISCOUNT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ADDPRODDISCOUNT"
        },
        {
            "attributeName": "ADDTRAINDISCOUNT",
            "required": false,
            "persistent": true,
            "title": "Additional Training Discount (%)",
            "remarks": "Additional Training Discount (%)",
            "sameAsAttribute": "ADDTRAINDISCOUNT",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ADDTRAINDISCOUNT",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ADDTRAINDISCOUNT"
        },
        {
            "attributeName": "GLOBAL",
            "required": true,
            "persistent": true,
            "title": "Global Usage",
            "remarks": "Global Usage ?",
            "sameAsAttribute": "GLOBAL",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "GLOBAL",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "GLOBAL"
        },
        {
            "attributeName": "LICKEY",
            "required": true,
            "persistent": true,
            "title": "License Key",
            "remarks": "License Key Used ?",
            "sameAsAttribute": "LICKEY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "LICKEY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "LICKEY"
        },
        {
            "attributeName": "TRANSFER",
            "required": true,
            "persistent": true,
            "title": "Transferable",
            "remarks": "Transferable?",
            "sameAsAttribute": "TRANSFER",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "TRANSFER",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "TRANSFER"
        },
        {
            "attributeName": "ASSIGNABILITY",
            "required": true,
            "persistent": true,
            "title": "Assignability",
            "remarks": "Assignability",
            "sameAsAttribute": "ASSIGNABILITY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ASSIGNABILITY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ASSIGNABILITY"
        },
        {
            "attributeName": "MAINTHIERARCHY",
            "required": true,
            "persistent": true,
            "title": "Maintain hierarchy",
            "remarks": "Maintain hierarchy",
            "sameAsAttribute": "MAINTHIERARCHY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "MAINTHIERARCHY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "MAINTHIERARCHY"
        },
        {
            "attributeName": "CANEXCEEDVOLUME",
            "required": true,
            "persistent": true,
            "title": "Can exceed amount",
            "remarks": "Can the specified maximum amount be exceeded?",
            "sameAsAttribute": "CANEXCEEDVOLUME",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CANEXCEEDVOLUME",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CANEXCEEDVOLUME"
        },
        {
            "attributeName": "CREATEREL",
            "required": true,
            "persistent": true,
            "title": "Create Release",
            "remarks": "Create release from the software contracts?",
            "sameAsAttribute": "CREATEREL",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CREATEREL",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CREATEREL"
        },
        {
            "attributeName": "AMTREMAINING",
            "required": false,
            "persistent": true,
            "title": "Amount Remaining",
            "remarks": "Difference between the maximum volume and the commited cost for a volume specified contract",
            "sameAsAttribute": "AMTREMAINING",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "AMTREMAINING",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "AMTREMAINING"
        },
        {
            "attributeName": "ACCEPTPERIOD",
            "required": false,
            "persistent": true,
            "title": "Acceptance Period (Days)",
            "remarks": "Acceptance period in days",
            "sameAsAttribute": "ACCEPTPERIOD",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ACCEPTPERIOD",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ACCEPTPERIOD"
        },
        {
            "attributeName": "ENFORCEBUNDLE",
            "required": true,
            "persistent": true,
            "title": "Enforce Bundle",
            "remarks": "Bundle enforced?",
            "sameAsAttribute": "ENFORCEBUNDLE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ENFORCEBUNDLE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ENFORCEBUNDLE"
        },
        {
            "attributeName": "ACCEPTANCE",
            "required": true,
            "persistent": true,
            "title": "Acceptance",
            "remarks": "Is there an acceptance period?",
            "sameAsAttribute": "ACCEPTANCE",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "ACCEPTANCE",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "ACCEPTANCE"
        },
        {
            "attributeName": "PERPETUITY",
            "required": true,
            "persistent": true,
            "title": "Perpetuity",
            "remarks": "Does the contract extend indefinitely?",
            "sameAsAttribute": "PERPETUITY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "PERPETUITY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "PERPETUITY"
        },
        {
            "attributeName": "AUTORENEWAL",
            "required": true,
            "persistent": true,
            "title": "Automatic Renewal",
            "remarks": "Does this contract automatically renew?",
            "sameAsAttribute": "AUTORENEWAL",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "AUTORENEWAL",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "AUTORENEWAL"
        },
        {
            "attributeName": "CONFIDENTIALITY",
            "required": true,
            "persistent": true,
            "title": "Confidentiality",
            "remarks": "Confidentiality",
            "sameAsAttribute": "CONFIDENTIALITY",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "CONFIDENTIALITY",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "CONFIDENTIALITY"
        },
        {
            "attributeName": "WARRANTYPERIOD",
            "required": false,
            "persistent": true,
            "title": "Warranty Period",
            "remarks": "Warranty period",
            "sameAsAttribute": "WARRANTYPERIOD",
            "sameAsObject": "CONTRACTSFW",
            "viewColumnName": "WARRANTYPERIOD",
            "tableName": "CONTRACTSFW",
            "tableColumnName": "WARRANTYPERIOD"
        },
        {
            "attributeName": "ADJUSTPERCENT",
            "required": false,
            "persistent": false,
            "title": "Adjustment %",
            "remarks": "Use this field to specify the increase or decrease percentage in price for this contract.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "LINESTATUS",
            "required": false,
            "persistent": false,
            "title": "Line Status",
            "remarks": "Use this field to indicate the status you want for the checked lines below.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "CONTRACT"
        },
        {
            "attributeName": "DESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Details",
            "remarks": "A detailed description of the current purchase contract.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "FREIGHTTERMS_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Freight Terms Long Description",
            "remarks": "A detailed description of the freight terms associated with this contract.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "REVCOMMENTS_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "REVCOMMENTS Long Description",
            "remarks": "Long description or detailed comments associated with the current revision of this contract.",
            "sameAsAttribute": null,
            "sameAsObject": null
        }
    ],
    "viewinfo": {
        "autosect": true,
        "viewwhere": "contract.contractnum=contractsfw.contractnum and contract.revisionnum=contractsfw.revisionnum and contract.orgid=contractsfw.orgid"
    },
    "outgoingRelationships": [
        {
            "name": "VENDOR",
            "target": "COMPANIES",
            "remarks": "Relationship to the Companies table, used to find all company records for a given contract. (sfwview.vendor=companies.company and sfwview.orgid=companies.orgid)",
            "whereClause": "company=:vendor and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "COMM_CONTGRP",
            "target": "CONTCOMMODITY",
            "remarks": "Relationship to the contcommodity table. (contcommodity.contractnum = sfwview.contractnum and contcommodity.revisionnum=sfwview.revisionnum and contcommodity.orgid = sfwview.orgid and contcommodity.commodity in (select commodity from contcommodity where parent is null)",
            "whereClause": "contractnum = :contractnum and revisionnum=:revisionnum and orgid = :orgid and commodity in (select commodity from contcommodity where parent is null)",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTCOMMODITY",
            "target": "CONTCOMMODITY",
            "remarks": "Relationship to the ContCommodity table, used to find all commodities for a given contract. (contcommodity.contractnum = sfwview.contractnum and contcommodity.revisionnum=sfwview.revisionnum). The resulting set will contain zero or more objects.",
            "whereClause": "contractnum=:contractnum and revisionnum=:revisionnum and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTASSET",
            "target": "CONTRACTASSET",
            "remarks": "Relationship to the contractasset table, used to find all contract assets for a given contract. (sfwview.contractnum=contractasset.contractnum)",
            "whereClause": "contractnum=:contractnum and revisionnum=:revisionnum and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTAUTH",
            "target": "CONTRACTAUTH",
            "remarks": "Relationship to the ContractAuth table, used to find all ContractAuth records for a given software contract. (contractauth.contractnum=sfwview.contractnum). The resulting set will contain one or more records.",
            "whereClause": "contractnum = :contractnum and revisionnum = :revisionnum and orgid = :orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTLINE",
            "target": "CONTRACTLINE",
            "remarks": "Relationship to the ContractLine table, used to find all contract lines for a given contract. (sfwview.contractnum=contractline.contractnum and sfwview.revisionnum=contractline.revisionnum and sfwview.orgid=contractline.orgid)",
            "whereClause": "contractnum = :contractnum and revisionnum =:revisionnum and orgid =:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTSTATUS",
            "target": "CONTRACTSTATUS",
            "remarks": "Relationship to the ContractStatus table, used to find all contract statuses for a given contract. (sfwview.contractnum=contractstatus.contractnum and sfwview.orgid=contractstatus.orgid)",
            "whereClause": "contractnum = :contractnum and revisionnum = :revisionnum and orgid = :orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTTERM",
            "target": "CONTRACTTERM",
            "remarks": "Relationship to the ContractTerm table, used to find all contract terms for a given software contract. (sfwview.contractnum=contractterm.contractnum and sfwview.revisionnum=contractterm.revisionnum and sfwview.orgid=contractterm.orgid)",
            "whereClause": "contractnum = :contractnum and revisionnum =:revisionnum and orgid =:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTTYPETERM",
            "target": "CONTRACTTYPETERM",
            "remarks": "Relationship to the ContractTypeTerm table used to find all ContractTerms for a given Contract Type (contracttypeterm.contracttypeid=sfwview.contracttype and contracttypeterm.orgid=sfwview.orgid)",
            "whereClause": "contracttypeid=:contracttype and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTSFWLIC",
            "target": "CONTSFWLIC",
            "remarks": "Relationship to the contsfwlic table. (contsfwlic.contractid=sfwview.contractid)",
            "whereClause": "contractid = :contractid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "COSTINPUT",
            "target": "COSTINPUT",
            "remarks": "Relationship to the non-persistent CostInput object. (No where clause). The resulting set will contain zero objects.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CREATERELINPUT",
            "target": "CREATERELINPUT",
            "remarks": "Relationship to the non-persistent CreateRelInput object. (No where clause). The resulting set will contain zero objects. Note: This relationship is used only for the create release action page to create a release from a given software contract.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "DOCLINKS",
            "target": "DOCLINKS",
            "remarks": "Relationship to the DocLinks table, used to find all document records for a given master contract. (doclinks.keytable = SFWVIEW and doclinks.keycolumn = CONTRACTNUM and doclinks.keyvalue = masterview.contractnum$DOCLINKS.KEYVALUE). The resulting set will contain zero or more objects. Note: The SFWVIEW.CONTRACTNUM field value will be formatted to match the DocLinks.KeyValue data type.",
            "whereClause": "(ownertable='SFWVIEW' and ownerid=:contractid) or (ownertable='RFQLINE' and ownerid in (select rfqlineid from rfqline where contractnum=:contractnum and orgid=:orgid)) or (ownertable='PRLINE' and ownerid in (select prlineid from prline where contractnum=:contractnum and orgid=:orgid)) or (ownertable='COMPANIES' and ownerid = (select companiesid from companies where company=:vendor and orgid=:orgid))",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "DRILLDOWN",
            "target": "DRILLDOWN",
            "remarks": "Relationship from the SFWVIEW to the non-persistent DrillDown table. (No where clause). The resulting set will contain zero objects. This relationship is used when the DrillDown page is launched from a location or asset field.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "INVOICELINEFORCONTRACT",
            "target": "INVOICELINE",
            "remarks": "Relationship to the InvoiceLine table, used to find all invoiceline for a given contract. (invoiceline.contractrefnum = sfwview.contractnum). The resulting set will contain one or more objects.",
            "whereClause": "contractrefnum = :contractnum",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "INVVENDOR",
            "target": "INVVENDOR",
            "remarks": "Relationship to the InvVendor table, used to find the invvendor records for a given vendor. (invvendor.vendor = sfwview.vendor and invvendor.orgid=sfwview.orgid). The resulting set will contain zero or more objects.",
            "whereClause": "vendor=:vendor and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "NAMEDUSERS",
            "target": "NAMEDUSERS",
            "remarks": "Relationship to the NamedUsers table, used to find all named users records for a given software contract. (sfwview.contractnum=namedusers.contractnum and sfwview.revisionnum=namedusers.revisionnum and sfwview.orgid=namedusers.orgid)",
            "whereClause": "contractnum = :contractnum and revisionnum =:revisionnum and orgid =:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "RELEASEPO",
            "target": "PO",
            "remarks": "Relationship to the PO table, used to find all release POs for a given contract. (contract.contractnum=po.contractrefnum and contract.orgid=po.orgid)",
            "whereClause": "contractrefnum=:contractnum and orgid=:orgid and status not in (select value from synonymdomain where domainid = 'POSTATUS' and maxvalue in ('REVISE', 'PNDREV'))",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "POLINES",
            "target": "POLINE",
            "remarks": "Relationship to the POLine table. Used to fetch all the POLines from the POLINE table",
            "whereClause": "1=1",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "PRLINE",
            "target": "PRLINE",
            "remarks": "Relationship to the PRLine table, used to find all purchase req line records for a given contract. (prline.contractnum = sfwview.contractnum). The resulting set will contain zero or more objects.",
            "whereClause": "contractnum=:contractnum and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "PROPERTYDEFAULT",
            "target": "PROPERTYDEFAULT",
            "remarks": "Relationship to the PropertyDefault table, used to find the PropertyDefault records whose propertyid match that of the SfwView. (propertydefault.contracttypeid=sfwview.contracttype). The resulting set will contain zero or more objects.",
            "whereClause": "contracttypeid = :contracttype and orgid = :orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWPROPERTYDEFAULT",
            "target": "PROPERTYDEFAULT",
            "remarks": "Relationship to the PropertyDefault table, used to find the PropertyDefault records whose propertyid match that of the SFWView. (propertydefault.contracttypeid=SFWCONTRACT,ENTERPRISE,OEM,RETAIL,SELECT,SUBSCRIPTION). The resulting set will contain zero or more objects.",
            "whereClause": "contracttypeid in ( select value from synonymdomain where domainid = 'CONTRACTTYPE' and maxvalue in('SFWCONTRACT','ENTERPRISE','OEM','RETAIL','SELECT','SUBSCRIPTION')) and propertyid in (select propertyid from propertydefault where contracttypeid in ( select value from synonymdomain where domainid = 'CONTRACTTYPE' and maxvalue in('SFWCONTRACT','ENTERPRISE','OEM','RETAIL','SELECT','SUBSCRIPTION')))",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "REVISIONINPUT",
            "target": "REVISIONINPUT",
            "remarks": "Relationship to the non-persistent RevisionInput object. (No where clause). The resulting set will contain zero objects.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "RFQLINE",
            "target": "RFQLINE",
            "remarks": "Relationship to the RFQLine table, used to find all rfq records for a given contract. (rfqline.contractnum = swview.contractnum). The resulting set will contain zero or more objects.",
            "whereClause": "contractnum=:contractnum and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWLICENSE",
            "target": "SFWLICENSE",
            "remarks": "Relationship to the sfwlicense table for sfwlicenseid associated with a contract.",
            "whereClause": "sfwlicenseid in (select sfwlicenseid from contsfwlic where contractid=:contractid)",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWREVHIST",
            "target": "SFWVIEW",
            "remarks": "Relationship to the sfwview table, used to find sfwview for a given software contract.",
            "whereClause": "contractnum=:contractnum and orgid=:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWVIEWCHGSTAT",
            "target": "SFWVIEWCHGSTAT",
            "remarks": "Relationship to the non-persistent SFWViewChangeStatus object. (No where clause). The resulting set will contain zero objects. Note: This relationship is used only for the Change Status action page to change the status of a given software contract.",
            "whereClause": null,
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWVIEWLINE",
            "target": "SFWVIEWLINE",
            "remarks": "Relationship to the SFWVIEWLINE table, used to find all contract lines for a given contract. (sfwview.contractnum=sfwviewline.contractnum and sfwview.revisionnum=sfwviewline.revisionnum and sfwview.orgid=sfwviewline.orgid)",
            "whereClause": "contractnum = :contractnum and revisionnum =:revisionnum and orgid =:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "REVISIONLINE",
            "target": "SFWVIEWLINE",
            "remarks": "Relationship to the SFWViewLine table used to find all SoftwareContractLines for a given Software Contract",
            "whereClause": "contractnum=:contractnum and revisionnum in (:revisionnum, (select max(revisionnum) from sfwviewline where contractnum=:contractnum and revisionnum < :revisionnum)) and contractlinenum in (select contractlinenum1 from sfwviewline where contractnum=:contractnum and revstatus in (select value from synonymdomain where maxvalue in ('ADDED','CHANGED'))  and revisionnum = :revisionnum)",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "NONCANCELEDCONRACTLINE",
            "target": "SFWVIEWLINE",
            "remarks": "Relationship to the SFWViewLine table, used to find all ContractLines that dont have a linestatus of cenceled. The resulting set might contain one or more objects.",
            "whereClause": "contractnum=:contractnum and revisionnum=:revisionnum and orgid=:orgid and linestatus not in (select value from synonymdomain where domainid ='CONTRACTSTATUS' and maxvalue='CAN')",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "APPRCONTRACTLINE",
            "target": "SFWVIEWLINE",
            "remarks": "Relationship to the SFWVIEWLINE table, used to find approved software contract line records for a given contract. (sfwviewline.contractnum = sfwview.contractnum and sfwviewline.revisionnum = sfwview.revisionnum and sfwviewline.orgid = sfwview.orgid). The resulting set will contain zero or more objects.",
            "whereClause": "contractnum=:contractnum and revisionnum = :revisionnum and orgid=:orgid and linestatus in (select value from synonymdomain where domainid='CONTRACTSTATUS' and maxvalue='APPR')",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTRACTSITE",
            "target": "SITE",
            "remarks": "Relationship to the Site table, used to find all sites that use the same itemset and companyset as the current contract site. The resulting set will contain zero or more objects.",
            "whereClause": "orgid in (select orgid from organization where itemsetid in (select itemsetid from organization where orgid=:orgid) and companysetid in (select companysetid from organization where orgid=:orgid))",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SLA",
            "target": "SLA",
            "remarks": "Relationship to the SLA table, used to find all slas in a status of active. (sla.status=ACTIVE). The resulting set will contain zero or more objects.",
            "whereClause": "orgid=:orgid and status in (select value from synonymdomain where domainid='SLASTATUS'and maxvalue ='ACTIVE')",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SLACONTRACT",
            "target": "SLACONTRACT",
            "remarks": "Relationship to the SLAContract table, used to find all slacontracts for a given software contract. (sfwview.contractid = slacontract.contractid). The resulting set will contain zero or more object.",
            "whereClause": "contractnum=:contractnum",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "STATUSDESC",
            "target": "SYNONYMDOMAIN",
            "remarks": "Relationship to synonymdomain table, used to find description for the status, it will contain one object.",
            "whereClause": "domainid='CONTRACTSTATUS' and value=:status and :&DOMAINFILTER&_STATUS",
            "cardinality": "UNDEFINED"
        }
    ],
    "incomingRelationships": [
        {
            "name": "SFWVIEW",
            "source": "CONTRACT",
            "remarks": "Relationship to the SFWView table, used to find SFWview records for a given contract. (sfwview.contractid = contract.contractid and sfwview.orgid = contract.orgid). The resulting set will contain zero or one object.",
            "whereClause": "contractid = :contractid and orgid = :orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWVIEW",
            "source": "CONTSFWLIC",
            "remarks": "Relationship to the sfwview table.(contswlic.contractlineid=sfwview.contractlineid)",
            "whereClause": "contractid = :contractid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWVIEW",
            "source": "PO",
            "remarks": "Relationship to the Software Contract, used to find all software contracts for a given relase po. (sfwview.contractid = po.contractrefid). The resulting set will contain zero or one object.",
            "whereClause": "contractid=:contractrefid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "VIEWREVHIST",
            "source": "SFWVIEW",
            "remarks": "Relationship to the sfwview table, used to find sfwview for a given software contract.",
            "whereClause": "contractnum=:contractnum and orgid=:orgid",
            "cardinality": "UNDEFINED"
        }
    ]
}