mos = {
    "objectName": "WFACTION",
    "className": "psdi.workflow.WFActionSet",
    "description": "Represent the arrows drawn between nodes",
    "longDescription": null,
    "isView": false,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": "WFACTIONID",
    "primaryKeyColumns": [
        "PROCESSNAME",
        "PROCESSREV",
        "ACTIONID"
    ],
    "logicalRelationships": [
        {
            "objectName": "WFACTION",
            "targetObject": "WFNOTIFICATION",
            "parentKeys": "PROCESSNAME, PROCESSREV, ACTIONID",
            "targetKeys": "PROCESSNAME, PROCESSREV, ACTIONID",
            "relNum": "1 to 1",
            "status": "VERIFIED",
            "description": "Designed Notification on Workflow Action",
            "longDescription": null
        },
        {
            "objectName": "WFACTION",
            "targetObject": "WFTRANSACTION",
            "parentKeys": "PROCESSNAME, PROCESSREV, ACTIONID",
            "targetKeys": "PROCESSNAME, PROCESSREV, ACTIONID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Executed Notification on Workflow Action",
            "longDescription": null
        }
    ],
    "targetLogicalRelationships": [
        {
            "objectName": "ACTION",
            "targetObject": "WFACTION",
            "parentKeys": "ACTION",
            "targetKeys": "ACTION",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Action performed when workflow reaches WFAction.",
            "longDescription": null
        },
        {
            "objectName": "WFNODE",
            "targetObject": "WFACTION",
            "parentKeys": "PROCESSNAME, PROCESSREV, NODEID",
            "targetKeys": "PROCESSNAME, PROCESSREV, MEMBERNODEID",
            "relNum": "0 to many",
            "status": "VERIFIED",
            "description": "Workflow actions extending from the node",
            "longDescription": null
        },
        {
            "objectName": "WFNODE",
            "targetObject": "WFACTION",
            "parentKeys": "PROCESSNAME, PROCESSREV, NODEID",
            "targetKeys": "PROCESSNAME, PROCESSREV, OWNERNODEID",
            "relNum": "0 to many",
            "status": "VERIFIED",
            "description": "Workflow actions pointing to the node",
            "longDescription": null
        },
        {
            "objectName": "WFPROCESS",
            "targetObject": "WFACTION",
            "parentKeys": "PROCESSNAME, PROCESSREV",
            "targetKeys": "PROCESSNAME, PROCESSREV",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Actions in the design of a workflow process.1",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "ACTIONID",
            "required": true,
            "persistent": true,
            "title": "Action",
            "remarks": "Uniquely identifies an action in a process. Autogenerated by the design tool for internal use.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "OWNERNODEID",
            "required": true,
            "persistent": true,
            "title": "From Node",
            "remarks": "The predecessor node.",
            "sameAsAttribute": "NODEID",
            "sameAsObject": "WFNODE"
        },
        {
            "attributeName": "MEMBERNODEID",
            "required": true,
            "persistent": true,
            "title": "To Node",
            "remarks": "The successor node.",
            "sameAsAttribute": "NODEID",
            "sameAsObject": "WFNODE"
        },
        {
            "attributeName": "ACTION",
            "required": false,
            "persistent": true,
            "title": "Action",
            "remarks": "The action to be performed (if any) as part of the processing of this arrow.",
            "sameAsAttribute": "ACTION",
            "sameAsObject": "ACTION"
        },
        {
            "attributeName": "INSTRUCTION",
            "required": false,
            "persistent": true,
            "title": "Instruction",
            "remarks": "Text to further clarify what specific action will take place for routing and manual inputs.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "PROCESSREV",
            "required": true,
            "persistent": true,
            "title": "Process Revision",
            "remarks": "Process Revision",
            "sameAsAttribute": "PROCESSREV",
            "sameAsObject": "WFPROCESS"
        },
        {
            "attributeName": "ISPOSITIVE",
            "required": true,
            "persistent": true,
            "title": "Positive",
            "remarks": "Is this a positive action",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "PROCESSNAME",
            "required": true,
            "persistent": true,
            "title": "Process",
            "remarks": "Name of the owning process.",
            "sameAsAttribute": "PROCESSNAME",
            "sameAsObject": "WFPROCESS"
        },
        {
            "attributeName": "WFACTIONID",
            "required": true,
            "persistent": true,
            "title": "WFACTIONID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "OBJECTNAME",
            "required": false,
            "persistent": false,
            "title": "Object",
            "remarks": "Type of object the owning process supports.",
            "sameAsAttribute": "OBJECTNAME",
            "sameAsObject": "MAXOBJECT"
        },
        {
            "attributeName": "SEQUENCE",
            "required": false,
            "persistent": true,
            "title": "Sequence",
            "remarks": "Ordering sequence for manual input actions",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CONDITION",
            "required": false,
            "persistent": true,
            "title": "Condition",
            "remarks": "Condition to check to enable this action",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "CONDITIONCLASS",
            "required": false,
            "persistent": true,
            "title": "Condition Class",
            "remarks": "Name of class to instanciate for custom conditional actions",
            "sameAsAttribute": "CLASSNAME",
            "sameAsObject": "MAXOBJECT"
        },
        {
            "attributeName": "AVAILABLE",
            "required": true,
            "persistent": false,
            "title": "Action Available",
            "remarks": "Is this workflow action available?",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "MEMBERNODETITLE",
            "required": false,
            "persistent": false,
            "title": "To Node",
            "remarks": "The title of the successor node.",
            "sameAsAttribute": "TITLE",
            "sameAsObject": "WFNODE"
        }
    ],
    "outgoingRelationships": [
        {
            "name": "ACTION",
            "target": "ACTION",
            "remarks": "Relationship to the Action table (action = :action).  Set will contain one or zero objects",
            "whereClause": "action = :action",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SHOWWFACTIONS",
            "target": "SHOWWFACTION",
            "remarks": "Relationship to the SHOWWFACTION table, used to edit workflow actions.",
            "whereClause": "1=2",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "MEMBERNODE",
            "target": "WFNODE",
            "remarks": "Relationship to the membernode of the wfaction.",
            "whereClause": "processname=:processname and processrev=:processrev and nodeid = :membernodeid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "NOTIFICATIONS",
            "target": "WFNOTIFICATION",
            "remarks": "Relationship to the WFNofitication table which holds the notifications for the action.  (processname=:processname and processrev=:processrev and nodeid = :ownernodeid and actionid = :actionid and actionid <> 0). This resulting set will contain zero to many objects.",
            "whereClause": "processname=:processname and processrev=:processrev and nodeid=:ownernodeid and actionid = :actionid and actionid <> 0",
            "cardinality": null
        }
    ],
    "incomingRelationships": [
        {
            "name": "ACTIONS",
            "source": "WFASSIGNMENT",
            "remarks": "Relationship used to find all actions extending from an assignment task node. (processname = :processname and processrev = :processrev and ownernodeid = :nodeid). This resulting set will contain one or two actions.",
            "whereClause": "processname = :processname and processrev = :processrev and ownernodeid = :nodeid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "ENTERINGACTIONS",
            "source": "WFNODE",
            "remarks": "The actions extending to this node. Set contains zero to many objects.",
            "whereClause": "processname=:processname and processrev=:processrev and membernodeid=:nodeid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "ACTIONS",
            "source": "WFNODE",
            "remarks": "Relationship to the WFAction table, used to find all actions extending from a node, of any node type. (wfnode.processid = wfaction.processid and wfnode.processrev = wfaction.processrev and wfnode.nodeid = wfaction.ownernodeid). This resulting set will contain zero or more objects.",
            "whereClause": "processname = :processname and processrev = :processrev and ownernodeid = :nodeid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "ACTION",
            "source": "WFTRANSACTION",
            "remarks": null,
            "whereClause": "processname=:processname and actionid=:actionid and processrev = :processrev",
            "cardinality": "UNDEFINED"
        }
    ]
}