mos = {
    "objectName": "SFWVIEWLINE",
    "className": "psdi.app.contract.software.SFWViewLineSet",
    "description": "View that combines CONTRACTLINE and SFWLINE",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": null,
    "primaryKeyColumns": [
        "CONTRACTNUM",
        "REVISIONNUM",
        "ORGID",
        "CONTRACTLINENUM"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "COMMODITIES",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITY, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Commodity",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITYGROUP, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Commodity Group",
            "longDescription": null
        },
        {
            "objectName": "COMPANIES",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "ORGID, COMPANY",
            "targetKeys": "ORGID, MANUFACTURER",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Manufacturer on Software Contract Line",
            "longDescription": null
        },
        {
            "objectName": "CONTRACT",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "targetKeys": "CONTRACTNUM, REVISIONNUM, ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Contract",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "ITEMNUM, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Item",
            "longDescription": null
        },
        {
            "objectName": "ITEMCONDITION",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "ITEMNUM, CONDITIONCODE, ITEMSETID",
            "targetKeys": "ITEMNUM, CONDITIONCODE, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Item Condition",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Language for the record",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization for the record",
            "longDescription": null
        },
        {
            "objectName": "PERSON",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "PERSONID",
            "targetKeys": "ENTERBY",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Person who entered the record.",
            "longDescription": null
        },
        {
            "objectName": "SETS",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "SETID",
            "targetKeys": "ITEMSETID",
            "relNum": null,
            "status": "INVALIDATED",
            "description": "Relationship 59",
            "longDescription": null
        },
        {
            "objectName": "SFWLINE",
            "targetObject": "SFWVIEWLINE",
            "parentKeys": "SFWLINEID",
            "targetKeys": "SFWLINEID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Software Line",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "ENTERDATE",
            "required": true,
            "persistent": true,
            "title": "Entered Date",
            "remarks": "The on which the line item was entered.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "ENTERDATE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ENTERDATE"
        },
        {
            "attributeName": "CATALOGCODE",
            "required": false,
            "persistent": true,
            "title": "Catalog #",
            "remarks": "A unique code for cataloging an item.",
            "sameAsAttribute": "CATALOGCODE",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "CATALOGCODE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CATALOGCODE"
        },
        {
            "attributeName": "CONVERSION",
            "required": false,
            "persistent": false,
            "title": "Conversion Factor",
            "remarks": "Conversion Factor",
            "sameAsAttribute": "CONVERSION",
            "sameAsObject": "CONVERSION"
        },
        {
            "attributeName": "INSPECTIONREQUIRED",
            "required": true,
            "persistent": true,
            "title": "Inspection Required",
            "remarks": "Indicates whether inspection of item is required upon receipt.",
            "sameAsAttribute": "INSPECTIONREQUIRED",
            "sameAsObject": "ITEM",
            "viewColumnName": "INSPECTIONREQUIRED",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "INSPECTIONREQUIRED"
        },
        {
            "attributeName": "ORGID",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization identifier.",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "ORGID1",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization identifier",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID1",
            "tableName": "SFWLINE",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "A written description of the entity on the contract line.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "ITEM",
            "viewColumnName": "DESCRIPTION",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "CHGQTYONUSE",
            "required": true,
            "persistent": true,
            "title": "Change Quantity on Use",
            "remarks": "Checking this box indicates you can change the quantity on the line with contract reference.",
            "sameAsAttribute": "CHGQTYONUSE",
            "sameAsObject": "CONTRACTPURCH",
            "viewColumnName": "CHGQTYONUSE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CHGQTYONUSE"
        },
        {
            "attributeName": "NEWUNITCOST",
            "required": false,
            "persistent": false,
            "title": "New Unit Cost",
            "remarks": "Non-persistent attribute used in the apply price adjustment action.",
            "sameAsAttribute": "UNITCOST",
            "sameAsObject": "CONTRACTLINE"
        },
        {
            "attributeName": "REMARK",
            "required": false,
            "persistent": true,
            "title": "Remarks",
            "remarks": "Comments about the individual line or line item.",
            "sameAsAttribute": "REMARK",
            "sameAsObject": "PRLINE",
            "viewColumnName": "REMARK",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "REMARK"
        },
        {
            "attributeName": "SFWLINEID",
            "required": true,
            "persistent": true,
            "title": "Unique Id",
            "remarks": "Unique Id",
            "sameAsAttribute": "SFWLINEID",
            "sameAsObject": "SFWLINE",
            "viewColumnName": "SFWLINEID",
            "tableName": "SFWLINE",
            "tableColumnName": "SFWLINEID"
        },
        {
            "attributeName": "COMMODITYGROUP",
            "required": false,
            "persistent": true,
            "title": "Commodity Group",
            "remarks": "The commodity group in which the line item is listed.",
            "sameAsAttribute": "COMMODITY",
            "sameAsObject": "COMMODITIES",
            "viewColumnName": "COMMODITYGROUP",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "COMMODITYGROUP"
        },
        {
            "attributeName": "ISSUEUNIT",
            "required": false,
            "persistent": false,
            "title": "Issue Unit",
            "remarks": "Issue Unit",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT"
        },
        {
            "attributeName": "LINESTATUS",
            "required": true,
            "persistent": true,
            "title": "Status",
            "remarks": "Indicates the status of the Contract Line. Could be one of Draft, Approved, Cancel and Waiting for Approval.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "LINESTATUS",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LINESTATUS"
        },
        {
            "attributeName": "REVSTATUS",
            "required": false,
            "persistent": true,
            "title": "Revision Status",
            "remarks": "Revision Status.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "REVSTATUS",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "REVSTATUS"
        },
        {
            "attributeName": "ORDERUNIT",
            "required": false,
            "persistent": true,
            "title": "Order Unit",
            "remarks": "Indicates the physical characteristics of a unit. A unit can be each, box, roll, linear feet, cubic feet, square feet etc.",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ORDERUNIT",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ORDERUNIT"
        },
        {
            "attributeName": "LEASEENDVALUE",
            "required": false,
            "persistent": true,
            "title": "Lease End Value",
            "remarks": "The monetary amount required to buy the asset at the end of the lease period.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "LEASEENDVALUE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LEASEENDVALUE"
        },
        {
            "attributeName": "PRLINENUM",
            "required": false,
            "persistent": false,
            "title": "PR Line",
            "remarks": "PR line number",
            "sameAsAttribute": "PRLINENUM",
            "sameAsObject": "PRLINE"
        },
        {
            "attributeName": "LANGCODE",
            "required": true,
            "persistent": true,
            "title": "Language Code",
            "remarks": "Language Column",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGCODE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LANGCODE"
        },
        {
            "attributeName": "REVISIONNUM",
            "required": true,
            "persistent": true,
            "title": "Revision",
            "remarks": "Revision number of the line. This number indicates the number of times the line has been revised. A line that has been created and not revised will show a number of 0.",
            "sameAsAttribute": "REVISIONNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "REVISIONNUM",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "REVISIONNUM"
        },
        {
            "attributeName": "REVISIONNUM1",
            "required": true,
            "persistent": true,
            "title": "Revision",
            "remarks": "Revision number of the line. This number indicates the number of times the line has been revised. A line that has been created and not revised will show a number of 0.",
            "sameAsAttribute": "REVISIONNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "REVISIONNUM1",
            "tableName": "SFWLINE",
            "tableColumnName": "REVISIONNUM"
        },
        {
            "attributeName": "ITEMSETID",
            "required": false,
            "persistent": true,
            "title": "Item Set",
            "remarks": "Set identifier for the item.",
            "sameAsAttribute": "SETID",
            "sameAsObject": "SETS",
            "viewColumnName": "ITEMSETID",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ITEMSETID"
        },
        {
            "attributeName": "NEWORDERQTY",
            "required": false,
            "persistent": false,
            "title": "Quantity",
            "remarks": "Non-persistent field to hold the order quantity value",
            "sameAsAttribute": "ORDERQTY",
            "sameAsObject": "INVENTORY"
        },
        {
            "attributeName": "PRNUM",
            "required": false,
            "persistent": false,
            "title": "PR",
            "remarks": "PR number",
            "sameAsAttribute": "PRNUM",
            "sameAsObject": "PR"
        },
        {
            "attributeName": "CHGPRICEONUSE",
            "required": true,
            "persistent": true,
            "title": "Change Price on Use",
            "remarks": "Checking this box indicates you can change the price on the line with contract reference.",
            "sameAsAttribute": "CHGPRICEONUSE",
            "sameAsObject": "CONTRACTPURCH",
            "viewColumnName": "CHGPRICEONUSE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CHGPRICEONUSE"
        },
        {
            "attributeName": "MANUFACTURER",
            "required": false,
            "persistent": true,
            "title": "Manufacturer",
            "remarks": "Unique code indicating the manufacturer of the item listed on the contract line.",
            "sameAsAttribute": "COMPANY",
            "sameAsObject": "COMPANIES",
            "viewColumnName": "MANUFACTURER",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "MANUFACTURER"
        },
        {
            "attributeName": "UNITCOST",
            "required": false,
            "persistent": true,
            "title": "Unit Cost",
            "remarks": "The monetary value associated with an ordered unit.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "UNITCOST",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "UNITCOST"
        },
        {
            "attributeName": "CONTRACTLINENUM",
            "required": true,
            "persistent": true,
            "title": "Line",
            "remarks": "The number of associated with an individual contract line.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "CONTRACTLINENUM",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CONTRACTLINENUM"
        },
        {
            "attributeName": "CONTRACTLINENUM1",
            "required": true,
            "persistent": true,
            "title": "Line",
            "remarks": "Contract Line Number",
            "sameAsAttribute": "CONTRACTLINENUM",
            "sameAsObject": "CONTRACTLINE",
            "viewColumnName": "CONTRACTLINENUM1",
            "tableName": "SFWLINE",
            "tableColumnName": "CONTRACTLINENUM"
        },
        {
            "attributeName": "CONTRACTTYPE",
            "required": true,
            "persistent": true,
            "title": "Contract Type",
            "remarks": "Contract type for the current contract.",
            "sameAsAttribute": "CONTRACTTYPE",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTTYPE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CONTRACTTYPE"
        },
        {
            "attributeName": "CONTRACTNUM",
            "required": true,
            "persistent": true,
            "title": "Contract",
            "remarks": "Unique ID number for the current contract.",
            "sameAsAttribute": "CONTRACTNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTNUM",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CONTRACTNUM"
        },
        {
            "attributeName": "CONTRACTNUM1",
            "required": true,
            "persistent": true,
            "title": "Contract",
            "remarks": "Contract number",
            "sameAsAttribute": "CONTRACTNUM",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "CONTRACTNUM1",
            "tableName": "SFWLINE",
            "tableColumnName": "CONTRACTNUM"
        },
        {
            "attributeName": "LINECOST",
            "required": false,
            "persistent": true,
            "title": "Line Cost",
            "remarks": "The sum of the unit cost multiplied by the order quantity.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "LINECOST",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LINECOST"
        },
        {
            "attributeName": "LINECOST2",
            "required": false,
            "persistent": true,
            "title": "Line Cost 2",
            "remarks": "Line cost in base currency 2.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "LINECOST2",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LINECOST2"
        },
        {
            "attributeName": "ENTERBY",
            "required": true,
            "persistent": true,
            "title": "Entered By",
            "remarks": "The name of the logged in user who entered the line item.",
            "sameAsAttribute": "PERSONID",
            "sameAsObject": "PERSON",
            "viewColumnName": "ENTERBY",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ENTERBY"
        },
        {
            "attributeName": "COMMODITY",
            "required": false,
            "persistent": true,
            "title": "Commodity Code",
            "remarks": "A unique code indicating the type of commodity on the line.",
            "sameAsAttribute": "COMMODITY",
            "sameAsObject": "COMMODITIES",
            "viewColumnName": "COMMODITY",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "COMMODITY"
        },
        {
            "attributeName": "MODELNUM",
            "required": false,
            "persistent": true,
            "title": "Model",
            "remarks": "The vendor's unique identification number for an item.",
            "sameAsAttribute": "MODELNUM",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "MODELNUM",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "MODELNUM"
        },
        {
            "attributeName": "RFQLINENUM",
            "required": false,
            "persistent": false,
            "title": "RFQ Line",
            "remarks": "RFQ line number",
            "sameAsAttribute": "RFQLINENUM",
            "sameAsObject": "RFQLINE"
        },
        {
            "attributeName": "NEWORDERUNIT",
            "required": false,
            "persistent": false,
            "title": "Order Unit",
            "remarks": "Non-persistent field to hold the order unit value",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT"
        },
        {
            "attributeName": "LINETYPE",
            "required": true,
            "persistent": true,
            "title": "Line Type",
            "remarks": "A code that indicates the type of item listed on the line. The value of line type could be Item, Material, Service, Special Order or External Catalog Item.",
            "sameAsAttribute": "LINETYPE",
            "sameAsObject": "PRLINE",
            "viewColumnName": "LINETYPE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LINETYPE"
        },
        {
            "attributeName": "DESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Details",
            "remarks": "An attached file that allows for a longer, more in depth description of the item.",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "SFWLICENSED",
            "required": true,
            "persistent": true,
            "title": "Licensed",
            "remarks": "Licensed",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "SFWLICENSED",
            "tableName": "SFWLINE",
            "tableColumnName": "SFWLICENSED"
        },
        {
            "attributeName": "LEADTIME",
            "required": false,
            "persistent": true,
            "title": "Delivery Time",
            "remarks": "The number of days between the order date and the delivery date.",
            "sameAsAttribute": "DELIVERYTIME",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "LEADTIME",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "LEADTIME"
        },
        {
            "attributeName": "NEWPRICE",
            "required": false,
            "persistent": false,
            "title": "New Line Cost",
            "remarks": "Contains the new price after the price adjustment has been applied.",
            "sameAsAttribute": "LINECOST",
            "sameAsObject": "CONTRACTLINE"
        },
        {
            "attributeName": "RFQNUM",
            "required": false,
            "persistent": false,
            "title": "RFQ",
            "remarks": "RFQ number",
            "sameAsAttribute": "RFQNUM",
            "sameAsObject": "RFQ"
        },
        {
            "attributeName": "ORDERQTY",
            "required": false,
            "persistent": true,
            "title": "Quantity",
            "remarks": "The number of an item ordered on this line.",
            "sameAsAttribute": "ORDERQTY",
            "sameAsObject": "INVENTORY",
            "viewColumnName": "ORDERQTY",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ORDERQTY"
        },
        {
            "attributeName": "ITEMNUM",
            "required": false,
            "persistent": true,
            "title": "Item",
            "remarks": "A unique identifier for the item.",
            "sameAsAttribute": "ITEMNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMNUM",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "ITEMNUM"
        },
        {
            "attributeName": "HASLD",
            "required": true,
            "persistent": true,
            "title": "Has Long Description",
            "remarks": "Boolean flag to indicate if there is any long description for this record",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "HASLD",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "HASLD"
        },
        {
            "attributeName": "CONTRACTLINEID",
            "required": true,
            "persistent": true,
            "title": "ContractLine ID",
            "remarks": "Unique identifier of every Contract Line in  the database (internal identifier).",
            "sameAsAttribute": "CONTRACTLINEID",
            "sameAsObject": "CONTRACTLINE",
            "viewColumnName": "CONTRACTLINEID",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CONTRACTLINEID"
        },
        {
            "attributeName": "REMARK_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Remark Long Description",
            "remarks": "Long Description for the description of the remark",
            "sameAsAttribute": null,
            "sameAsObject": null
        },
        {
            "attributeName": "POREQUIRED",
            "required": true,
            "persistent": true,
            "title": "Requires PO",
            "remarks": "Will a PO be required for this contractline?",
            "sameAsAttribute": "POREQUIRED",
            "sameAsObject": "CONTRACT",
            "viewColumnName": "POREQUIRED",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "POREQUIRED"
        },
        {
            "attributeName": "HASPAYMENTSCHED",
            "required": true,
            "persistent": true,
            "title": "Payment Schedule",
            "remarks": "Checking this box indicates the line has a payment schedule associated with it.",
            "sameAsAttribute": null,
            "sameAsObject": null,
            "viewColumnName": "HASPAYMENTSCHED",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "HASPAYMENTSCHED"
        },
        {
            "attributeName": "CONDITIONCODE",
            "required": false,
            "persistent": true,
            "title": "Condition Code",
            "remarks": "A code indicating a condition for the item rotated out of service and into a storeroom.",
            "sameAsAttribute": "CONDITIONCODE",
            "sameAsObject": "ITEMCONDITION",
            "viewColumnName": "CONDITIONCODE",
            "tableName": "CONTRACTLINE",
            "tableColumnName": "CONDITIONCODE"
        },
        {
            "attributeName": "MAINT",
            "required": true,
            "persistent": true,
            "title": "Maintenance",
            "remarks": "Specifies whether or not the contract line item is for maintenance.",
            "sameAsAttribute": "MAINT",
            "sameAsObject": "SFWLINE",
            "viewColumnName": "MAINT",
            "tableName": "SFWLINE",
            "tableColumnName": "MAINT"
        },
        {
            "attributeName": "MAINTTERM",
            "required": false,
            "persistent": true,
            "title": "Maintenance Term",
            "remarks": "The number that specifies the duration of the maintenance contract line item. Use this number in combination with the value in the Term Unit field to determine the duration.",
            "sameAsAttribute": "MAINTTERM",
            "sameAsObject": "SFWLINE",
            "viewColumnName": "MAINTTERM",
            "tableName": "SFWLINE",
            "tableColumnName": "MAINTTERM"
        },
        {
            "attributeName": "TERMUNIT",
            "required": false,
            "persistent": true,
            "title": "Term Unit",
            "remarks": "Unit of measurement for the term of the maintenance contract line item.",
            "sameAsAttribute": "TERMUNIT",
            "sameAsObject": "SFWLINE",
            "viewColumnName": "TERMUNIT",
            "tableName": "SFWLINE",
            "tableColumnName": "TERMUNIT"
        },
        {
            "attributeName": "RENEWALDATE",
            "required": false,
            "persistent": true,
            "title": "Maintenance Renewal Date",
            "remarks": "Date that the contract line item can be or must be renewed.",
            "sameAsAttribute": "RENEWALDATE",
            "sameAsObject": "SFWLINE",
            "viewColumnName": "RENEWALDATE",
            "tableName": "SFWLINE",
            "tableColumnName": "RENEWALDATE"
        }
    ],
    "viewinfo": {
        "autosect": true,
        "viewwhere": "contractline.contractnum=sfwline.contractnum and contractline.revisionnum=sfwline.revisionnum and contractline.orgid=sfwline.orgid and contractline.contractlinenum=sfwline.contractlinenum and contractline.contracttype in (select value from synonymdomain where domainid ='CONTRACTTYPE' and maxvalue in ('SFWCONTRACT','ENTERPRISE','OEM','RETAIL','SELECT','SUBSCRIPTION'))"
    },
    "outgoingRelationships": [
        {
            "name": "ASSET",
            "target": "ASSET",
            "remarks": "Relationship to the contractline table.(cotractline.itemnum=asset.itemnum and cotractline.itemsetid=asset.itemsetid)",
            "whereClause": "itemnum = :itemnum and itemsetid = :itemsetid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "CONTSFWLIC",
            "target": "CONTSFWLIC",
            "remarks": "Relationship to the contsfwlic table (sfwviewline.contractlineid=contsfwlic.contractlineid)",
            "whereClause": "contractlineid=:contractlineid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWLICENSE",
            "target": "SFWLICENSE",
            "remarks": "Relationship to the sfwlicense table for sfwlicenseid associated with a software contract line.",
            "whereClause": "sfwlicenseid in (select sfwlicenseid from contsfwlic where contractlineid=:sfwviewlineid)",
            "cardinality": "UNDEFINED"
        }
    ],
    "incomingRelationships": [
        {
            "name": "CONTSFWLIC_CONTLINE",
            "source": "CONTSFWLIC",
            "remarks": "Relationship to the sfwviewline table. (contsfwlic.contractlineid=sfwviewline.contractlineid)",
            "whereClause": "contractlineid = :contractlineid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "SFWVIEWLINE",
            "source": "SFWVIEW",
            "remarks": "Relationship to the SFWVIEWLINE table, used to find all contract lines for a given contract. (sfwview.contractnum=sfwviewline.contractnum and sfwview.revisionnum=sfwviewline.revisionnum and sfwview.orgid=sfwviewline.orgid)",
            "whereClause": "contractnum = :contractnum and revisionnum =:revisionnum and orgid =:orgid",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "REVISIONLINE",
            "source": "SFWVIEW",
            "remarks": "Relationship to the SFWViewLine table used to find all SoftwareContractLines for a given Software Contract",
            "whereClause": "contractnum=:contractnum and revisionnum in (:revisionnum, (select max(revisionnum) from sfwviewline where contractnum=:contractnum and revisionnum < :revisionnum)) and contractlinenum in (select contractlinenum1 from sfwviewline where contractnum=:contractnum and revstatus in (select value from synonymdomain where maxvalue in ('ADDED','CHANGED'))  and revisionnum = :revisionnum)",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "NONCANCELEDCONRACTLINE",
            "source": "SFWVIEW",
            "remarks": "Relationship to the SFWViewLine table, used to find all ContractLines that dont have a linestatus of cenceled. The resulting set might contain one or more objects.",
            "whereClause": "contractnum=:contractnum and revisionnum=:revisionnum and orgid=:orgid and linestatus not in (select value from synonymdomain where domainid ='CONTRACTSTATUS' and maxvalue='CAN')",
            "cardinality": "UNDEFINED"
        },
        {
            "name": "APPRCONTRACTLINE",
            "source": "SFWVIEW",
            "remarks": "Relationship to the SFWVIEWLINE table, used to find approved software contract line records for a given contract. (sfwviewline.contractnum = sfwview.contractnum and sfwviewline.revisionnum = sfwview.revisionnum and sfwviewline.orgid = sfwview.orgid). The resulting set will contain zero or more objects.",
            "whereClause": "contractnum=:contractnum and revisionnum = :revisionnum and orgid=:orgid and linestatus in (select value from synonymdomain where domainid='CONTRACTSTATUS' and maxvalue='APPR')",
            "cardinality": "UNDEFINED"
        }
    ]
}