mos = {
    "objectName": "SKDEXTRACAPTOOLVIEW",
    "className": "com.ibm.tivoli.maximo.skd.app.SKDExtraCapToolViewSet",
    "description": "View that combines SKDWORKPLANEXTCAP and ITEM.",
    "longDescription": null,
    "isView": true,
    "isInternal": false,
    "isPersistent": true,
    "isMainObject": false,
    "uniqueId": null,
    "primaryKeyColumns": [
        "ITEMNUM",
        "ITEMSETID1"
    ],
    "logicalRelationships": [],
    "targetLogicalRelationships": [
        {
            "objectName": "CLASSSTRUCTURE",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "CLASSSTRUCTUREID",
            "targetKeys": "CLASSSTRUCTUREID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Tool Class Structure",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITY, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Tool Commodity",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITY, ITEMSETID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 47",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITYGROUP, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Tool Commodity Group",
            "longDescription": null
        },
        {
            "objectName": "COMMODITIES",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "COMMODITY, ITEMSETID",
            "targetKeys": "COMMODITYGROUP, ITEMSETID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 49",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "ITEMNUM, ITEMSETID",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 59",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "ITEMNUM, ITEMSETID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 60",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "RESOURCENAME, ITEMSETID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Tool",
            "longDescription": null
        },
        {
            "objectName": "ITEM",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "ITEMNUM, ITEMSETID",
            "targetKeys": "RESOURCENAME, ITEMSETID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Relationship 62",
            "longDescription": null
        },
        {
            "objectName": "LANGUAGE",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "MAXLANGCODE",
            "targetKeys": "LANGCODE",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Record Language",
            "longDescription": null
        },
        {
            "objectName": "METER",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "METERNAME",
            "targetKeys": "METERNAME",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Tool Meter",
            "longDescription": null
        },
        {
            "objectName": "METERGROUP",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "GROUPNAME",
            "targetKeys": "GROUPNAME",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Tool Group",
            "longDescription": null
        },
        {
            "objectName": "ORGANIZATION",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "ORGID",
            "targetKeys": "ORGID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Organization",
            "longDescription": null
        },
        {
            "objectName": "SETS",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "SETID",
            "targetKeys": "ITEMSETID",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Item Set",
            "longDescription": null
        },
        {
            "objectName": "SETS",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "SETID",
            "targetKeys": "ITEMSETID1",
            "relNum": "1 to many",
            "status": "INVALIDATED",
            "description": "Item Set",
            "longDescription": null
        },
        {
            "objectName": "SKDWORKPLANEXTCAP",
            "targetObject": "SKDEXTRACAPTOOLVIEW",
            "parentKeys": "SKDWORKPLANEXTCAPID",
            "targetKeys": "SKDWORKPLANEXTCAPID",
            "relNum": "1 to many",
            "status": "VERIFIED",
            "description": "Extra Capacity Work Plan Next",
            "longDescription": null
        }
    ],
    "columns": [
        {
            "attributeName": "SOURCESYSID",
            "required": false,
            "persistent": true,
            "title": "Source System ID",
            "remarks": "Source System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "SOURCESYSID",
            "tableName": "ITEM",
            "tableColumnName": "SOURCESYSID"
        },
        {
            "attributeName": "PLUSCISMTE",
            "required": true,
            "persistent": true,
            "title": "Is M&TE",
            "remarks": "Defines whether a Tool is a standard used for measuring and testing equipment.",
            "sameAsAttribute": "PLUSCISMTE",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCISMTE",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCISMTE"
        },
        {
            "attributeName": "RANK",
            "required": false,
            "persistent": true,
            "title": "Rank",
            "remarks": "The rank associated with the skill level of a particular craft. The rank is in ascending order, 1 being the lowest.",
            "sameAsAttribute": "RANK",
            "sameAsObject": "CRAFTSKILL",
            "viewColumnName": "RANK",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "RANK"
        },
        {
            "attributeName": "CAPITALIZED",
            "required": true,
            "persistent": true,
            "title": "Capitalized",
            "remarks": "Specifies whether the item is to be financially accounted for as a capitalized cost or a non-capitalized cost. If the check box is selected, the item is capitalized. If the check box is cleared (the default), the item is a non-capitalized cost. Tools are always accounted for as capitalized costs. You can only change the setting for this field by using the Change Capitalized Status action in Item Master. Capitalized items are always issued and returned at zero cost, regardless of the cost carried in inventory. Non-capitalized items are issued and returned at the standard, last, or average cost, as specified in Multisite.",
            "sameAsAttribute": "CAPITALIZED",
            "sameAsObject": "ITEM",
            "viewColumnName": "CAPITALIZED",
            "tableName": "ITEM",
            "tableColumnName": "CAPITALIZED"
        },
        {
            "attributeName": "SKILLNAME",
            "required": false,
            "persistent": true,
            "title": "Skill Name",
            "remarks": "Unique ID of the skill.",
            "sameAsAttribute": "SKILLNAME",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "SKILLNAME",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKILLNAME"
        },
        {
            "attributeName": "HASIAS",
            "required": true,
            "persistent": false,
            "title": "Rotating",
            "remarks": "HASIAS",
            "sameAsAttribute": "HASIAS",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "INSPECTIONREQUIRED",
            "required": true,
            "persistent": true,
            "title": "Inspect on Receipt",
            "remarks": "Specifies whether the item should be held out of inventory when being received, until the purchase order receipt has been approved. If the check box is selected, the item cannot be received until it has been inspected. If the check box is cleared (the default), the item can be received without an inspection.",
            "sameAsAttribute": "INSPECTIONREQUIRED",
            "sameAsObject": "ITEM",
            "viewColumnName": "INSPECTIONREQUIRED",
            "tableName": "ITEM",
            "tableColumnName": "INSPECTIONREQUIRED"
        },
        {
            "attributeName": "VALUE",
            "required": false,
            "persistent": true,
            "title": "Additional Capacity Required",
            "remarks": "The amount of extra resources that are required in order to complete the work during the specified time period.",
            "sameAsAttribute": "VALUE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "VALUE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "VALUE"
        },
        {
            "attributeName": "KITCOMPONENTTOADDTOSTORE",
            "required": true,
            "persistent": false,
            "title": "Is Kit Component to Be Added to Store",
            "remarks": "non-persistent attribute used when adding the kit to which this item belongs to a storeroom.",
            "sameAsAttribute": "KITCOMPONENTTOADDTOSTORE",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "ITEMID",
            "required": true,
            "persistent": true,
            "title": "ITEMID",
            "remarks": "Unique Identifier",
            "sameAsAttribute": "ITEMID",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMID",
            "tableName": "ITEM",
            "tableColumnName": "ITEMID"
        },
        {
            "attributeName": "STATUS",
            "required": true,
            "persistent": true,
            "title": "Status",
            "remarks": "The current status of the item such as ACTIVE, PENDING, PLANNING, PENDOBS and OBSELETE.",
            "sameAsAttribute": "STATUS",
            "sameAsObject": "ITEM",
            "viewColumnName": "STATUS",
            "tableName": "ITEM",
            "tableColumnName": "STATUS"
        },
        {
            "attributeName": "ENDDATE",
            "required": false,
            "persistent": true,
            "title": "End Date",
            "remarks": "Identifies the end date and time when this additional resource is required.",
            "sameAsAttribute": "ENDDATE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "ENDDATE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "ENDDATE"
        },
        {
            "attributeName": "PLUSCISMTECLASS",
            "required": false,
            "persistent": true,
            "title": "M&TE Classification",
            "remarks": "When the Is M&TE? field is checked then you have the option to choose a classification for M&TE.",
            "sameAsAttribute": "PLUSCISMTECLASS",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCISMTECLASS",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCISMTECLASS"
        },
        {
            "attributeName": "NP_STATUSMEMO",
            "required": false,
            "persistent": false,
            "title": "Change Status Memo",
            "remarks": "Status change memo, temporary non-persistent field used by MEA",
            "sameAsAttribute": "MEMO",
            "sameAsObject": "WFTRANSACTION"
        },
        {
            "attributeName": "STATUSDATE",
            "required": true,
            "persistent": true,
            "title": "Status Date",
            "remarks": "Date the work order status was last changed.",
            "sameAsAttribute": "STATUSDATE",
            "sameAsObject": "ITEM",
            "viewColumnName": "STATUSDATE",
            "tableName": "ITEM",
            "tableColumnName": "STATUSDATE"
        },
        {
            "attributeName": "ORGID",
            "required": false,
            "persistent": true,
            "title": "Organization",
            "remarks": "Organization Identifier.",
            "sameAsAttribute": "ORGID",
            "sameAsObject": "ORGANIZATION",
            "viewColumnName": "ORGID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "ORGID"
        },
        {
            "attributeName": "GROUPNAME",
            "required": false,
            "persistent": true,
            "title": "Meter Group",
            "remarks": "Identifies the meter group, or category of meters, to which the meter applied to this item belongs. Applies only to rotating items. Click the Select Value button to choose a meter group.",
            "sameAsAttribute": "GROUPNAME",
            "sameAsObject": "METERGROUP",
            "viewColumnName": "GROUPNAME",
            "tableName": "ITEM",
            "tableColumnName": "GROUPNAME"
        },
        {
            "attributeName": "ITEMNUM",
            "required": true,
            "persistent": true,
            "title": "Item",
            "remarks": "Identifies the item record. This value must be unique for all item records. Click the Detail Menu button to view items by classification or availability.",
            "sameAsAttribute": "ITEMNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMNUM",
            "tableName": "ITEM",
            "tableColumnName": "ITEMNUM"
        },
        {
            "attributeName": "DESCRIPTION",
            "required": false,
            "persistent": true,
            "title": "Description",
            "remarks": "Names or describes the inventory item. For additional information, click the Long Description button.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "ITEM",
            "viewColumnName": "DESCRIPTION",
            "tableName": "ITEM",
            "tableColumnName": "DESCRIPTION"
        },
        {
            "attributeName": "ISKIT",
            "required": true,
            "persistent": true,
            "title": "Kit",
            "remarks": "Specifies whether the item is a kit item that contains a collection of items that can be issued together as a single item. If the check box is selected, the item is a kit. If the check box is cleared (the default), the item is not a kit.",
            "sameAsAttribute": "ISKIT",
            "sameAsObject": "ITEM",
            "viewColumnName": "ISKIT",
            "tableName": "ITEM",
            "tableColumnName": "ISKIT"
        },
        {
            "attributeName": "LOTTYPE",
            "required": true,
            "persistent": true,
            "title": "Lot Type",
            "remarks": "Specifies whether the item is tracked by lot (LOT) or not (NOLOT). LOT is used for an item that is lotted, typically has an expiration date, and is able to be assigned lot numbers upon receipt. NOLOT means that the item does not need to be tracked by lots. Click the Select Value button to choose a lot type.",
            "sameAsAttribute": "LOTTYPE",
            "sameAsObject": "ITEM",
            "viewColumnName": "LOTTYPE",
            "tableName": "ITEM",
            "tableColumnName": "LOTTYPE"
        },
        {
            "attributeName": "ISCREW",
            "required": true,
            "persistent": true,
            "title": "Crew",
            "remarks": "Specifies whether the tool can be used in Crew applications and Work Order Tracking applications. If the check box is selected, the tool can be used. If the check box is cleared, the tool cannot be used.",
            "sameAsAttribute": "ISCREW",
            "sameAsObject": "ITEM",
            "viewColumnName": "ISCREW",
            "tableName": "ITEM",
            "tableColumnName": "ISCREW"
        },
        {
            "attributeName": "NP_STATUSROLLDOWN",
            "required": true,
            "persistent": false,
            "title": "Roll New Status to Organizations and Inventory",
            "remarks": "Roll New Status to Organizations and Inventory, temporary non-persistent field used by MEA",
            "sameAsAttribute": "NP_STATUSROLLDOWN",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "SPAREPARTAUTOADD",
            "required": true,
            "persistent": true,
            "title": "Add as Spare Part",
            "remarks": "Specifies whether the item will be added as a spare part for the asset when issued, if the item is not already a spare part. If the checkbox is selected, the item can be added as a spare part. If the check box is cleared (the default), the item is not used as a spare part.",
            "sameAsAttribute": "SPAREPARTAUTOADD",
            "sameAsObject": "ITEM",
            "viewColumnName": "SPAREPARTAUTOADD",
            "tableName": "ITEM",
            "tableColumnName": "SPAREPARTAUTOADD"
        },
        {
            "attributeName": "ITEMSETID",
            "required": false,
            "persistent": true,
            "title": "Item Set",
            "remarks": "Identifies the item set.",
            "sameAsAttribute": "SETID",
            "sameAsObject": "SETS",
            "viewColumnName": "ITEMSETID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "ITEMSETID"
        },
        {
            "attributeName": "MSDSNUM",
            "required": false,
            "persistent": true,
            "title": "MSDS",
            "remarks": "Material Safety Data Sheet number issued by the Occupational Safety and Health Association (OSHA). The Material Safety Data Sheet (MSDS), which describes product dangers, must be available to purchasers and users of commercial quantities of all hazardous materials.",
            "sameAsAttribute": "MSDSNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "MSDSNUM",
            "tableName": "ITEM",
            "tableColumnName": "MSDSNUM"
        },
        {
            "attributeName": "OWNERSYSID",
            "required": false,
            "persistent": true,
            "title": "Owner System ID",
            "remarks": "Owner System ID",
            "sameAsAttribute": "OWNER1SYSID",
            "sameAsObject": "MXCOLLAB",
            "viewColumnName": "OWNERSYSID",
            "tableName": "ITEM",
            "tableColumnName": "OWNERSYSID"
        },
        {
            "attributeName": "PLUSCSOLUTION",
            "required": true,
            "persistent": true,
            "title": "Buffer Solution",
            "remarks": "Buffer Solution Flag",
            "sameAsAttribute": "PLUSCSOLUTION",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCSOLUTION",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCSOLUTION"
        },
        {
            "attributeName": "IN26",
            "required": false,
            "persistent": true,
            "title": "IN26",
            "remarks": "Extra Field 26",
            "sameAsAttribute": "IN26",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN26",
            "tableName": "ITEM",
            "tableColumnName": "IN26"
        },
        {
            "attributeName": "SENDERSYSID",
            "required": false,
            "persistent": true,
            "title": "Sender System ID",
            "remarks": "Column used by ERP-Integration (APIs)",
            "sameAsAttribute": "SENDERSYSID",
            "sameAsObject": "ITEM",
            "viewColumnName": "SENDERSYSID",
            "tableName": "ITEM",
            "tableColumnName": "SENDERSYSID"
        },
        {
            "attributeName": "RECEIPTTOLERANCE",
            "required": false,
            "persistent": true,
            "title": "Receipt Tolerance %",
            "remarks": "The percentage value of items that can be received over the amount set in the initial agreement.",
            "sameAsAttribute": "RECEIPTTOLERANCE",
            "sameAsObject": "ITEM",
            "viewColumnName": "RECEIPTTOLERANCE",
            "tableName": "ITEM",
            "tableColumnName": "RECEIPTTOLERANCE"
        },
        {
            "attributeName": "IN27",
            "required": false,
            "persistent": true,
            "title": "IN27",
            "remarks": "Extra Field 27",
            "sameAsAttribute": "IN27",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN27",
            "tableName": "ITEM",
            "tableColumnName": "IN27"
        },
        {
            "attributeName": "IN24",
            "required": false,
            "persistent": true,
            "title": "IN24",
            "remarks": "Extra Field 24",
            "sameAsAttribute": "IN24",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN24",
            "tableName": "ITEM",
            "tableColumnName": "IN24"
        },
        {
            "attributeName": "IN25",
            "required": false,
            "persistent": true,
            "title": "IN25",
            "remarks": "Extra Field 25",
            "sameAsAttribute": "IN25",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN25",
            "tableName": "ITEM",
            "tableColumnName": "IN25"
        },
        {
            "attributeName": "IN22",
            "required": false,
            "persistent": true,
            "title": "Extra Field 22",
            "remarks": "Extra Field 22",
            "sameAsAttribute": "IN22",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN22",
            "tableName": "ITEM",
            "tableColumnName": "IN22"
        },
        {
            "attributeName": "IN23",
            "required": false,
            "persistent": true,
            "title": "Extra Field 23",
            "remarks": "Extra Field 23",
            "sameAsAttribute": "IN23",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN23",
            "tableName": "ITEM",
            "tableColumnName": "IN23"
        },
        {
            "attributeName": "ATTACHONISSUE",
            "required": true,
            "persistent": true,
            "title": "Attach to Parent Asset on Issue",
            "remarks": "Specifies whether to attach the item to the parent asset when the item is issued. If the check box is selected, the item becomes a subassembly of the parent asset upon issue. If the check box is cleared (the default), the item is not attached to the parent asset when issued.",
            "sameAsAttribute": "ATTACHONISSUE",
            "sameAsObject": "ITEM",
            "viewColumnName": "ATTACHONISSUE",
            "tableName": "ITEM",
            "tableColumnName": "ATTACHONISSUE"
        },
        {
            "attributeName": "SITEID",
            "required": false,
            "persistent": false,
            "title": "Site",
            "remarks": "SITEID",
            "sameAsAttribute": "SITEID",
            "sameAsObject": "SITE"
        },
        {
            "attributeName": "STATUSIFACE",
            "required": true,
            "persistent": false,
            "title": "Has Status Changed",
            "remarks": "Non persistent boolean field to indicate whether the status has been changed after the stateful object is fetched from the database.",
            "sameAsAttribute": "STATUSIFACE",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "OUTSIDE",
            "required": true,
            "persistent": true,
            "title": "Outside",
            "remarks": "Specifies whether the item is a consignment good. If the check box is selected, the item belongs to a contractor (or vendor), but it is stored on-site, and it is an item for which you expect to be charged for its use. If the check box is cleared (the default), the item is not owned by an outside party.",
            "sameAsAttribute": "OUTSIDE",
            "sameAsObject": "ITEM",
            "viewColumnName": "OUTSIDE",
            "tableName": "ITEM",
            "tableColumnName": "OUTSIDE"
        },
        {
            "attributeName": "HASLD",
            "required": true,
            "persistent": true,
            "title": "Has Long Description",
            "remarks": "Boolean flag to indicate if there is any long description for this record",
            "sameAsAttribute": "HASLD",
            "sameAsObject": "ITEM",
            "viewColumnName": "HASLD",
            "tableName": "ITEM",
            "tableColumnName": "HASLD"
        },
        {
            "attributeName": "PLUSCISINHOUSECAL",
            "required": true,
            "persistent": true,
            "title": "Internal Calibration",
            "remarks": "When selected, indicates that this tool is calibrated in house. This field can be used to sort tools that are calibrated internally or externally.",
            "sameAsAttribute": "PLUSCISINHOUSECAL",
            "sameAsObject": "ITEM",
            "viewColumnName": "PLUSCISINHOUSECAL",
            "tableName": "ITEM",
            "tableColumnName": "PLUSCISINHOUSECAL"
        },
        {
            "attributeName": "ORDERUNIT",
            "required": false,
            "persistent": true,
            "title": "Order Unit",
            "remarks": "Unit of measure used to order the item, such as DOZEN or CASE. Click the Select Value button to view a list of valid order units.",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ORDERUNIT",
            "tableName": "ITEM",
            "tableColumnName": "ORDERUNIT"
        },
        {
            "attributeName": "MAXISSUE",
            "required": false,
            "persistent": true,
            "title": "Maximum Quantity Issued",
            "remarks": "Total maximum quantity that can be issued to an asset.",
            "sameAsAttribute": "MAXISSUE",
            "sameAsObject": "ITEM",
            "viewColumnName": "MAXISSUE",
            "tableName": "ITEM",
            "tableColumnName": "MAXISSUE"
        },
        {
            "attributeName": "ITEMTYPE",
            "required": true,
            "persistent": true,
            "title": "Item Type",
            "remarks": "Item Type",
            "sameAsAttribute": "ITEMTYPE",
            "sameAsObject": "ITEM",
            "viewColumnName": "ITEMTYPE",
            "tableName": "ITEM",
            "tableColumnName": "ITEMTYPE"
        },
        {
            "attributeName": "RESOURCENAME",
            "required": false,
            "persistent": true,
            "title": "Resource Name",
            "remarks": "Identifies the craft, tool, or crew that is required to complete the work.",
            "sameAsAttribute": "ITEMNUM",
            "sameAsObject": "ITEM",
            "viewColumnName": "RESOURCENAME",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "RESOURCENAME"
        },
        {
            "attributeName": "ISSUEUNIT",
            "required": false,
            "persistent": true,
            "title": "Issue Unit",
            "remarks": "Unit of measure used to issue the item from the storeroom, such as EACH or ROLL. Click the Select Value button to choose an issue unit.",
            "sameAsAttribute": "MEASUREUNITID",
            "sameAsObject": "MEASUREUNIT",
            "viewColumnName": "ISSUEUNIT",
            "tableName": "ITEM",
            "tableColumnName": "ISSUEUNIT"
        },
        {
            "attributeName": "SKDWORKPLANEXTCAPID",
            "required": true,
            "persistent": true,
            "title": "Unique Id",
            "remarks": "Unique Id",
            "sameAsAttribute": "SKDWORKPLANEXTCAPID",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "SKDWORKPLANEXTCAPID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKDWORKPLANEXTCAPID"
        },
        {
            "attributeName": "ITEMSETID1",
            "required": true,
            "persistent": true,
            "title": "Item Set",
            "remarks": "Identifies the item set, or group of items, to which this item belongs. An organization is assigned to only one item set, but multiple organizations can use the same item set. Click the Select Value button to choose an item set.",
            "sameAsAttribute": "SETID",
            "sameAsObject": "SETS",
            "viewColumnName": "ITEMSETID1",
            "tableName": "ITEM",
            "tableColumnName": "ITEMSETID"
        },
        {
            "attributeName": "ROTATING",
            "required": true,
            "persistent": true,
            "title": "Rotating",
            "remarks": "Specifies whether the item is a rotating asset. If the check box is selected, the item becomes an asset tracked by item number and individual asset number. If the check box is cleared (the default), the item is not tracked as an individual asset.",
            "sameAsAttribute": "ROTATING",
            "sameAsObject": "ITEM",
            "viewColumnName": "ROTATING",
            "tableName": "ITEM",
            "tableColumnName": "ROTATING"
        },
        {
            "attributeName": "DESCRIPTION_LONGDESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Details",
            "remarks": "Long Description for Item Description",
            "sameAsAttribute": "DESCRIPTION_LONGDESCRIPTION",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "CONDITIONENABLED",
            "required": true,
            "persistent": true,
            "title": "Condition Enabled",
            "remarks": "Specifies whether this item has a value or worth you want to assign and track based on its physical condition. You can apply different rates to an item as its condition changes from use, such as from new to used. If the check box is selected, you must assign at least one full value (100%) condition code for this item, and any other codes you assign must be a percentage of that. If the check box is cleared (the default), the physical condition of the item is not tracked.",
            "sameAsAttribute": "CONDITIONENABLED",
            "sameAsObject": "ITEM",
            "viewColumnName": "CONDITIONENABLED",
            "tableName": "ITEM",
            "tableColumnName": "CONDITIONENABLED"
        },
        {
            "attributeName": "PRORATE",
            "required": true,
            "persistent": true,
            "title": "Prorate Service",
            "remarks": "Prorate Service?",
            "sameAsAttribute": "PRORATE",
            "sameAsObject": "ITEM",
            "viewColumnName": "PRORATE",
            "tableName": "ITEM",
            "tableColumnName": "PRORATE"
        },
        {
            "attributeName": "ITEM_DESCRIPTION",
            "required": false,
            "persistent": false,
            "title": "Description",
            "remarks": "Description of this item.",
            "sameAsAttribute": "DESCRIPTION",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "METERNAME",
            "required": false,
            "persistent": true,
            "title": "Meter",
            "remarks": "Identifies the meter associated with the item, for which a reading is to be recorded when this item is issued to an asset. A meter is a device designed to measure time, distance, speed, or intensity, or indicate and record or regulate the amount or volume, as of the flow of a gas or an electric current. Only non-rotating items can be associated with a meter.",
            "sameAsAttribute": "METERNAME",
            "sameAsObject": "METER",
            "viewColumnName": "METERNAME",
            "tableName": "ITEM",
            "tableColumnName": "METERNAME"
        },
        {
            "attributeName": "LANGCODE",
            "required": true,
            "persistent": true,
            "title": "Language Code",
            "remarks": "Language Column",
            "sameAsAttribute": "MAXLANGCODE",
            "sameAsObject": "LANGUAGE",
            "viewColumnName": "LANGCODE",
            "tableName": "ITEM",
            "tableColumnName": "LANGCODE"
        },
        {
            "attributeName": "COMMODITYGROUP",
            "required": false,
            "persistent": true,
            "title": "Commodity Group",
            "remarks": "Identifies the commodity group, or product category, associated with this item or tool. Click the Select Value button to view a list of valid commdity groups.",
            "sameAsAttribute": "COMMODITY",
            "sameAsObject": "COMMODITIES",
            "viewColumnName": "COMMODITYGROUP",
            "tableName": "ITEM",
            "tableColumnName": "COMMODITYGROUP"
        },
        {
            "attributeName": "HARDRESISSUE",
            "required": true,
            "persistent": true,
            "title": "Requires hard reservation on use",
            "remarks": "Indicates whether a hard reservation must be referenced when the item is issued from a storeroom.",
            "sameAsAttribute": "HARDRESISSUE",
            "sameAsObject": "ITEM",
            "viewColumnName": "HARDRESISSUE",
            "tableName": "ITEM",
            "tableColumnName": "HARDRESISSUE"
        },
        {
            "attributeName": "HIERARCHYPATH",
            "required": false,
            "persistent": false,
            "title": "Hierarchy Path",
            "remarks": "Sets value to HIERARCHYPATH, if the item has an associated CLASSSTRUCTURE record",
            "sameAsAttribute": "HIERARCHYPATH",
            "sameAsObject": "CLASSSTRUCTURE"
        },
        {
            "attributeName": "CLASSSTRUCTUREID",
            "required": false,
            "persistent": true,
            "title": "Class Structure",
            "remarks": "Class Structure identifier",
            "sameAsAttribute": "CLASSSTRUCTUREID",
            "sameAsObject": "CLASSSTRUCTURE",
            "viewColumnName": "CLASSSTRUCTUREID",
            "tableName": "ITEM",
            "tableColumnName": "CLASSSTRUCTUREID"
        },
        {
            "attributeName": "IN19",
            "required": false,
            "persistent": true,
            "title": "Extra Field 19",
            "remarks": "Extra Field 19",
            "sameAsAttribute": "IN19",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN19",
            "tableName": "ITEM",
            "tableColumnName": "IN19"
        },
        {
            "attributeName": "SKDPROJECTID",
            "required": false,
            "persistent": true,
            "title": "Project Id",
            "remarks": "Unique identifier of the Schedule.",
            "sameAsAttribute": "SKDPROJECTID",
            "sameAsObject": "SKDPROJECT",
            "viewColumnName": "SKDPROJECTID",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKDPROJECTID"
        },
        {
            "attributeName": "TAXEXEMPT",
            "required": true,
            "persistent": true,
            "title": "Tax Exempt",
            "remarks": "Select this check box if the item, the tool, or the service is not taxable. The buyer for your organization determines the tax-exempt status of items, of tools, and of services.",
            "sameAsAttribute": "TAXEXEMPT",
            "sameAsObject": "ITEM",
            "viewColumnName": "TAXEXEMPT",
            "tableName": "ITEM",
            "tableColumnName": "TAXEXEMPT"
        },
        {
            "attributeName": "EXTERNALREFID",
            "required": false,
            "persistent": true,
            "title": "External Reference ID",
            "remarks": "External Reference ID",
            "sameAsAttribute": "EXTERNALREFID",
            "sameAsObject": "ITEM",
            "viewColumnName": "EXTERNALREFID",
            "tableName": "ITEM",
            "tableColumnName": "EXTERNALREFID"
        },
        {
            "attributeName": "COMMODITY",
            "required": false,
            "persistent": true,
            "title": "Commodity Code",
            "remarks": "Identifies the commodity code associated with this item or tool. Click the Select Value button to view a list of valid commodity codes.",
            "sameAsAttribute": "COMMODITY",
            "sameAsObject": "COMMODITIES",
            "viewColumnName": "COMMODITY",
            "tableName": "ITEM",
            "tableColumnName": "COMMODITY"
        },
        {
            "attributeName": "ITEM_ID",
            "required": false,
            "persistent": false,
            "title": "Item",
            "remarks": "Inventory item number.",
            "sameAsAttribute": "ITEM_ID",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "INSTANCE",
            "required": false,
            "persistent": false,
            "title": "Instance",
            "remarks": "INSTANCE",
            "sameAsAttribute": "INSTANCE",
            "sameAsObject": "ITEM"
        },
        {
            "attributeName": "SKILLLEVEL",
            "required": false,
            "persistent": true,
            "title": "Skill Level",
            "remarks": "Identifies the level of skill or expertise in a particular craft.",
            "sameAsAttribute": "SKILLLEVEL",
            "sameAsObject": "CRAFTSKILL",
            "viewColumnName": "SKILLLEVEL",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "SKILLLEVEL"
        },
        {
            "attributeName": "IN21",
            "required": false,
            "persistent": true,
            "title": "Extra Field 21",
            "remarks": "Extra Field 21",
            "sameAsAttribute": "IN21",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN21",
            "tableName": "ITEM",
            "tableColumnName": "IN21"
        },
        {
            "attributeName": "IN20",
            "required": false,
            "persistent": true,
            "title": "Extra Field 20",
            "remarks": "Extra Field 20",
            "sameAsAttribute": "IN20",
            "sameAsObject": "ITEM",
            "viewColumnName": "IN20",
            "tableName": "ITEM",
            "tableColumnName": "IN20"
        },
        {
            "attributeName": "TYPE",
            "required": false,
            "persistent": true,
            "title": "Type",
            "remarks": "Identifies the type of resource that is required. Options include craft, tool, or crew.",
            "sameAsAttribute": "TYPE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "TYPE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "TYPE"
        },
        {
            "attributeName": "STARTDATE",
            "required": false,
            "persistent": true,
            "title": "Start Date",
            "remarks": "Identifies the start date and time when this additional resource is required.",
            "sameAsAttribute": "STARTDATE",
            "sameAsObject": "SKDWORKPLANEXTCAP",
            "viewColumnName": "STARTDATE",
            "tableName": "SKDWORKPLANEXTCAP",
            "tableColumnName": "STARTDATE"
        }
    ],
    "viewinfo": {
        "autosect": true,
        "viewwhere": "skdworkplanextcap.resourcename=item.itemnum and skdworkplanextcap.itemsetid=item.itemsetid "
    },
    "outgoingRelationships": [],
    "incomingRelationships": [
        {
            "name": "SKDEXTRACAPTOOLVIEW",
            "source": "SKDPROJECT",
            "remarks": "Relationship to the SKDExtraCapToolView table, used to find the extra capacity for the schedule.",
            "whereClause": "skdprojectid=:skdprojectid",
            "cardinality": null
        }
    ]
}